### ISSUE TITLE
Timezone problem with the playlist creation date

### ISSUE THREAD

**Issue by paulijar** [daneren2005/Subsonic#1001]
When viewing details of a playlist, the list creation time is shown as UTC time, just as the server returns it. On the other hand, when viewing details of a bookmark, the creation time is converted to the user local time.

I believe that the timestamp presentation format has been fixed for the bookmarks on #472 but the playlists were missed at that time.

Tested on DSub 5.3.2 as versions newer than that are not compatible with the Nextcloud/ownCloud Music server.

**Comment by daneren2005** [comment]
Yep I can reproduce this one
