### ISSUE TITLE
How Could I Shuffle All Music in Library?

### ISSUE THREAD

**Issue by githubA3B5** [daneren2005/Subsonic#1009]
How Could I Shuffle All Music in Library?

**Comment by Faeb35** [comment]
Go to Library and use the button on the top right (two crossing arrows).

**Comment by githubA3B5** [comment]
> Go to Library and use the button on the top right (two crossing arrows).

it only shuffle 20 songs add to playlist

**Comment by daneren2005** [comment]
It adds more as you listen to music. It it a revolving list.
