### ISSUE TITLE
Title, artist and thumbnail missing with the new media notification

### ISSUE THREAD

**Issue by llucps** [daneren2005/Subsonic#1010]
With the new media notification (Android 5.0+) update all the metadata including the thumbnail is missing:

With the old notification:
![old](https://user-images.githubusercontent.com/25823659/94110558-1a8e0380-fe43-11ea-8cb9-427238eb2a00.png)

And the new:
![new](https://user-images.githubusercontent.com/25823659/94110576-224da800-fe43-11ea-9d6e-d2943324ab6f.png)

**Comment by daneren2005** [comment]
What device are you using?

**Comment by githubA3B5** [comment]
> What device are you using?

my device has same problem but it is a main activity, my device is android 10,

**Comment by llucps** [comment]
Asus Max Pro M1 with Lineage 16 (Android 9)

**Comment by SteveDinn** [comment]
I am having the same issue. Sorry for the large screenshots.
![Screenshot_20200922-100626](https://user-images.githubusercontent.com/3911507/94169105-c85dda00-fe64-11ea-9f9b-f650929ee31d.jpg)
![Screenshot_20200922-101120](https://user-images.githubusercontent.com/3911507/94169126-cf84e800-fe64-11ea-8166-995cfe129029.jpg)

**Comment by daneren2005** [comment]
Jeeze Google why can nothing you make sure work the way your docs say they do.

**Comment by Faeb35** [comment]
Same on Galaxy Note 3 with LineageOS Android 9.
Thank you @daneren2005  for still improving DSub!

**Comment by daneren2005** [comment]
Possible fix for people to try out: https://github.com/daneren2005/Subsonic/releases/tag/5.5.1-beta2.  I can't really since Android 11 behaves way differently.

**Comment by SteveDinn** [comment]
5.5.1-beta-2 has fixed this issue for me. Thanks!

**Comment by Faeb35** [comment]
It's fixed on my device as well! Awesome!! 
Thank you so much!

**Comment by llucps** [comment]
Yes, it works. Thanks!

**Comment by daneren2005** [comment]
Anyone want to share a screenshot so I can see what it looks like?

**Comment by SteveDinn** [comment]
![Screenshot_20201003-143038](https://user-images.githubusercontent.com/3911507/94997981-1ff6f680-0585-11eb-9037-2230079fe82f.jpg)

**Comment by daneren2005** [comment]
Sweet thank you. That looks about how I would expect it to.

**Comment by Efreak** [comment]
> Possible fix for people to try out: https://github.com/daneren2005/Subsonic/releases/tag/5.5.1-beta2. I can't really tell since Android 11 behaves way differently.

Looks the same to me on android 9, so it's not just an android 11 thing. I haven't tried the beta yet, as I'm on the fdroid release (and so far as I can tell, there's no easy way to export the database of downloaded media--or is that not needed?)
