### ISSUE TITLE
Next song does not play automatically

### ISSUE THREAD

**Issue by jdrexmo** [daneren2005/Subsonic#1013]
I've been searching for help with this and have seen many *similar* issues but most with some extra complication and none with a solution that seemed to work for me yet. But I'm generally very new to this, so apologies if this is a stupid user problem.
I'm using DSub on Android 11 on a Pixel 2 XL to access an AirSonic server. The AirSonic web player works fine, but when connecting via DSub, at the end of any song on any playlist, playback stops. The play/pause button becomes a stop square, text above it reads, "Downloading - 0B," and it stays that way until I do something. Pressing the next track button plays the next track normally, even if pressed immediately. Let me know what other info I can provide to help troubleshoot.

**Comment by khers** [comment]
This might be related to #1003

**Comment by jdrexmo** [comment]
I actually haven't been able to reproduce the error for the last couple days, so unless there was an update since I posted this then I'm assuming this was some brand of ID10T error. Not going to close this issue ticket for a little while still, just in case.

**Comment by jimmysmallse3** [comment]
I'm actually having the same issue. Seems to have just started a few days ago but I've tried everything I can think of to fix it.

**Comment by khers** [comment]
I suggest that this is related to #1003 because I see DSUB try and cache the playlist and fail to do so.  Then when it tries to play song 2 on the list, the cache cannot be found and it does not try to download it again.

**Comment by jimmysmallse3** [comment]
I was looking at #1003 and saw that part of the issue had been fixed and I still had the issue and assumed I had the latest version since I got it from the play store but I'm still on 5.4.4 so that's my bad. Any idea how long it takes for the play store to get the newer versions? Only reason I do it through there is because of Android auto.

**Comment by daneren2005** [comment]
I usually do rolling updates over a day or so.  After that it should auto update fairly quickly on your phone.  I am closing this now since you said you were just on an old version when this was happening.

**Comment by khers** [comment]
The update fixed this problem for me.

**Comment by khers** [comment]
This issue has started reoccurring for me.
