### ISSUE TITLE
Is there a plan for supporting Chinese language?

### ISSUE THREAD

**Issue by githubA3B5** [daneren2005/Subsonic#1019]
I can't see any option settings for language?

**Comment by daneren2005** [comment]
I haven't done any of the languages honestly, I only have been doing community translations. If you want to do a translation, even a partial one I would accept it but no I'm not planning on doing a Chinese translation myself.

**Comment by githubA3B5** [comment]
> I haven't done any of the languages honestly, I only have been doing community translations. If you want to do a translation, even a partial one I would accept it but no I'm not planning on doing a Chinese translation myself.

I would like to,such as poeditor.com is a good way to translate by multi people.
