### ISSUE TITLE
Playback stops when screen locks

### ISSUE THREAD

**Issue by ericzlot** [daneren2005/Subsonic#1022]
Pixel 3 since latest update, daub playback stops when the screen locks automatically or if I manually lock it. Any fix?

**Comment by daneren2005** [comment]
I had another user report that taking DSUb off the battery restricted in the background list helped with this. Can you check in DSubs advanced app info settings to make sure it isn't restricting background usage.

**Comment by ericzlot** [comment]
That seems to have fixed it. Thanks

**Comment by daneren2005** [comment]
Do you remember getting a prompt to turn it on our anything or do you think it turned on on its own? Wondering if this is something I can change so it don't get put on the list in the first place.

**Comment by ericzlot** [comment]
I might have done it on my own but it wasn't a problem until the latest
Android update.
