### ISSUE TITLE
UI: App doesn't fill screen

### ISSUE THREAD

**Issue by AMoonRabbit** [daneren2005/Subsonic#1023]
As per the title, the app does not utilise the entire screen on the Pixel 4, there's a black bar at the bottom, or two black bars down either side when landscape. 

![Screenshot_20201013-230245](https://user-images.githubusercontent.com/3766988/95921323-fde14d80-0da8-11eb-8d0d-d64db8a03210.png)
![Screenshot_20201013-230237](https://user-images.githubusercontent.com/3766988/95921327-ffab1100-0da8-11eb-8384-bf70740d945e.png)

**Comment by daneren2005** [comment]
Is that with the fullscreen option on?  I noticed that in my playing around with that toggle last night.

**Comment by AMoonRabbit** [comment]
Yes both with full screen toggled on and off.

**Comment by AMoonRabbit** [comment]
Just updating this. I switched to the Google Play version of the release and this has resolved the issue with the app not filling the screen.
