### ISSUE TITLE
Feature Request: Revert to non-sensitive notifications

### ISSUE THREAD

**Issue by sean-v8** [daneren2005/Subsonic#1024]
With the recent update, media buttons are no longer accessible from the lock screen unless the system-wide "Show sensitive content when locked" setting is enabled, which of course is not desirable for many users.

I recall being able to set this sensitive/non-sensitive behavior on a per-app basis at some point in the past but it seems this ability is gone as of Android 10.. hope I'm not missing something obvious..

**Comment by daneren2005** [comment]
Fixed with PR #1026

**Comment by sean-v8** [comment]
Thanks! :)
