### ISSUE TITLE
dsub randomly closes/hangs/stops playing

### ISSUE THREAD

**Issue by dverbeeck** [daneren2005/Subsonic#1025]
Seeing a few issues on my Pixel 4 XL ever since updating to 5.5:

1. As soon as I open the app, it typically hangs and shows the "downloading" notification with details stating 0 songs are being fetched. dsub will then sometimes start normally after 30 seconds or crash out.

2. Sometimes stops after a single track, but this has improved slightly in 5.5.1 vs the last release

3. dsub arbitrarily closes mid playback. Sometimes happens when app loses focus, sometimes when it still has focus. I do not have dsub configured to take action on focus loss.

**Comment by daneren2005** [comment]
Look at the responses to https://github.com/daneren2005/Subsonic/issues/1022

**Comment by dverbeeck** [comment]
Hey there, it's not being restricted at all when in the background
actually. Checked that last week when it started happening again on the
latest build.

**Comment by daneren2005** [comment]
Anything special you can suggest i try to reproduce? I haven't been seeing this at all on a pixel 3 with the latest Android.

**Comment by dverbeeck** [comment]
Scott,

     Is there any way I can build a debug apk from a pull of 5.5.1? 
Maybe I can catch some logs to look into. Additionally, might I be so 
bold as to suggest re-opening this issue? It's happening even when 
screen is not locked sometimes, though all I can provide are screenshots 
unless we can take a look under the hood. I'm more than willing to help 
diagnose from that angle.

-Derek
