### ISSUE TITLE
Playback issue

### ISSUE THREAD

**Issue by mononoke22** [daneren2005/Subsonic#1027]
Hello,
There's an issue sometimes, when switching track (using the "next track" button), it jumps a track for no reason.
Let's say you're playing track 2 from an album, pressing the "next track" button, it jumps to track 4. It's acting like 3 was missing or something.

It happens at random, whatever if it's bluetooth/wifi, or if the tracks are on the actual phone.
It happens with touchscreen controls but also using physical buttons on a connected bluetooth speaker.

Cheers

**Comment by daneren2005** [comment]
I have never seen this and can't reproduce.  Unless someone else is having the same issue I am going to assume device specific issue that I can't track down/solve.
