### ISSUE TITLE
DSub doesn't appear in "Android Auto for phone screens"

### ISSUE THREAD

**Issue by ParadingLunatic** [daneren2005/Subsonic#1032]
I've seen that DSub is supposedly listed/working for cars with Android Auto, but unfortunately it doesn't appear in the Android Auto for phone screens app. I'm guessing this isn't a big issue as it seems most are using it with an actual Android Auto capable head unit.  Unfortunately, I replaced the head unit in my car before Android Auto came out, and I'm really not interested in buying yet another head unit just for Android Auto support.  It would be nice to see it compatible with the Android Auto for phones app.  Just a convenience factor.  

I would just use my Emby server and app (as it's the only thing with my music library listed), but every time I launch it after it closes I have to go back in and reselect whatever music or playlist I would like to play.

**Comment by daneren2005** [comment]
As far as I can tell there is nothing special that I can do to make it enabled for auto for phones, and I can't even install it.  I am just registering to be available for Android Auto, and that is still valid.  Since nothing special I can configure to make this happen, I am closing this.

**Comment by popeen** [comment]
Just to add to this, I am seeing DSub in both Android Auto and Android Auto for phone screens. I am guessing you sideloaded DSub?

Android Auto has a limitation where the app must be installed from Google Play or it will not show up, this is because Google wants to be in full control of what can be shown on Auto for safety reasons. I am guessing that they have the same limitation on Auto for phone screens.

**Comment by ParadingLunatic** [comment]
> Just to add to this, I am seeing DSub in both Android Auto and Android Auto for phone screens. I am guessing you sideloaded DSub?
> 
> Android Auto has a limitation where the app must be installed from Google Play or it will not show up, this is because Google wants to be in full control of what can be shown on Auto for safety reasons. I am guessing that they have the same limitation on Auto for phone screens.

That was the issue.  I figured I'd grab the most up to date right from github.  Apparently that was my downfall.  
Thank you very much!

**Comment by daneren2005** [comment]
Ack I don't know why I keep forgetting about that when people bring this up.  Thank for you reminder and checking it out for me Popeen!

**Comment by amoranvalero** [comment]
If you set your android auto application in debug mode and modify the display mode to be development, it appears as an available application.

**Comment by popeen** [comment]
Well I clearly need to go look at the documentation again, I had no idea this was a thing in auto but you are right. This fixes it right up, also makes it a lot easier to run dev builds on my main phone so thank you!
