### ISSUE TITLE
Feature request for internal server address?

### ISSUE THREAD

**Issue by surfrock66** [daneren2005/Subsonic#1035]
I have a working airsonic setup.  Everything is great and it's accessible from inside and outside the LAN.  Inside the LAN I have a dns server, so I can access the the server from DSub both internally and externally from the same address, it works great.

When I try to cast to my chromecast audio, it just buffers forever and fails.  I believe this is because the chromecast refuses to use my internal DNS and is hardcoded to go straight to google's DNS; as a result when trying to resolve my server name from inside the LAN, it's getting the WAN IP and failing.

I have multiple chromecasts, some 1st gen, some audio, and some ultra.  They have different wifi capabilities.  I have 2 SSID's in my house, a 2.4GHz one and a 5GHz one.  If I set the LAN address to the server to the IP, it works but because of the 2 SSID's sometimes it doesn't.  It depends what the chromecast is connected to AND what my phone is connected to.

This would be resolved if we could have multiple entries for the "Local Network SSID" in the server settings of DSub.  Would that be possible?

**Comment by GunbleR** [comment]
A bit off-topic, but i use padavan/rt-n56u router firmware on 25$ xiaomi and it does proper port forward when i type my external ip.
Apperantly Protocol called nat loopback/nat hairpin, should also be on std wrt firmware, but i didnt used wrt long enough to check.

**Comment by surfrock66** [comment]
I actually have it proxied using apache so it's on 443.  Makes it super easy.

**Comment by daneren2005** [comment]
So I just checked and it does work if you have the different SSID's separated by a comma.  It is important that there is no space in between comma and the two SSIDs.

**Comment by surfrock66** [comment]
I had no idea you could do that, thank you so much!
