### ISSUE TITLE
dSub Crashes when moved to background on S20+ and Pixel 4XL

### ISSUE THREAD

**Issue by dverbeeck** [daneren2005/Subsonic#1036]
dsub (latest from Google Store) continually crashes when being moved to the background after starting playback.

This is occuring on both my Pixel 4XL and Galaxy S20+

**Comment by daneren2005** [comment]
I had another user report that taking DSUb off the battery restricted in the background list helped with this. Can you check in DSubs advanced app info settings to make sure it isn't restricting background usage.

**Comment by dverbeeck** [comment]
Why was this closed? It is still an issue if I'm streaming.  Only goes away
in offline mode
