### ISSUE TITLE
Top header hides under notification bar

### ISSUE THREAD

**Issue by jacroe** [daneren2005/Subsonic#1037]
With DSub 5.5.2, the top header now hides under the notification bar on a Pixel 4 running Android 11.

Screenshots attached.

![Screenshot_20201204-033226](https://user-images.githubusercontent.com/1142635/101141155-e45ac600-35e1-11eb-8ae2-13b97bfe1362.png)
![Screenshot_20201204-033257](https://user-images.githubusercontent.com/1142635/101141162-e58bf300-35e1-11eb-8437-b775449bd44e.png)

**Comment by jmccoy555** [comment]
Same issue on Galaxy A70 - Android 10. 

p.s. thanks for the app and updates though.

**Comment by daneren2005** [comment]
I honestly don't know how I didn't notice that when using it.  Now that I see it I can't unsee it lol

**Comment by tzw9373** [comment]
Same for me, OnePlus 6 on Android 10.

**Comment by jacroe** [comment]
Oddly enough, it pops down when a long-press selection is made.

**Comment by llucps** [comment]
yep same for me too

**Comment by daneren2005** [comment]
Having trouble tracking this down but I am still working on it.

**Comment by jacroe** [comment]
Can confirm fixed on my phone. Thanks very much!
