### ISSUE TITLE
Random files being marked as unavailable

### ISSUE THREAD

**Issue by khers** [daneren2005/Subsonic#1038]
On my Pixel 3, random songs in my library are highlighted red and cannot be played.  However they are available to other phones and to the user logged in on DSub when using the Subsonic web interface.  Refreshing the library or the album does not seem to fix the problem, how can I convince DSub that these files are available?

**Comment by daneren2005** [comment]
IIRC the only case where songs are marked as red is if they were down thumbed, and they are auto skipped since you down thumbed them.  Can you check if they are 1-star rated or down thumbed?

**Comment by khers** [comment]
This is indeed the case, is there a way to clear a thumbs down?

**Comment by daneren2005** [comment]
Yes change it to not be 1 starred

**Comment by khers** [comment]
They aren't 1 starred, they were thumbs downed.  AFAICT there is no UI for undoing that.

**Comment by daneren2005** [comment]
Click the 3 dot menu on the song and set rating and remove the 1 star. That is what thumbs down is since subsonic has no concept of thumbs up or down

**Comment by khers** [comment]
Thanks this worked.
