### ISSUE TITLE
Playback notification disappears after pausing and playback is sporadically not resumed via Bluetooth

### ISSUE THREAD

**Issue by tobiaspc** [daneren2005/Subsonic#1039]
Version: 5.5.2 (from Github)
Android: 10
Device: OnePlus 6T

**First issue:**
When pressing the Pause button in the notification, the notification itself disappears immediately. Therefore, resuming playback is not possible without opening the app again.

**Second, possibly related issue:**
A similar issue happens when playing music over Bluetooth: After pausing playback using the headphone button, resuming it via a repeated press is not working. This is only happening sporadically, I found no way to reproduce it. Waiting a longer time (a few minutes) between pause/play seems to trigger this behavior more often.

**Expected**: Notification stays and playback over BT resumes. This is the default behavior with any other music app (Google Play Music, YT-Music, YT-Premium in background play).

**Comment by SteveDinn** [comment]
There's a setting in the "playback" section of the settings that controls this behaviour (Persistent notification). You will want it to be checked.

**Comment by tobiaspc** [comment]
Oh well, thanks!
