### ISSUE TITLE
DSub not working with Airsonic Advanced

### ISSUE THREAD

**Issue by Maarten90** [daneren2005/Subsonic#1042]
Environment:
Android 11 / Pixel 3XL
DSub 5.5.2

When trying to login to an Airsonic Advanced system, the app always tells me that the credentials are wrong. Other apps like Ultrasonic work fine. Could you please have a look into this? Thanks in advance!

**Comment by daneren2005** [comment]
There is another closed issue #1029. This is an Airsonic Advanced issue that they need to fix. They broke part of the API that we used but some apps like Ultrasonic do not.

**Comment by Maarten90** [comment]
Thanks for getting back to me. I switched the password encryption to AES as suggested in the linked issue, this made it work. Thank you!
