### ISSUE TITLE
ids with hyphens seem to be interpreted

### ISSUE THREAD

**Issue by sentriz** [daneren2005/Subsonic#1043]
hey thank you for DSub

I have a subsonic server which returns a similar response to `search3.view`
```
<subsonic-response status="ok" version="1.15.0" xmlns="http://subsonic.org/restapi" type="gonic" gonicVersion="v0.11.1">
    <searchResult3>
        <artist id="ar-38" name="Lene Lovich"></artist>
    </searchResult3>
</subsonic-response>
```

containing an artist result with id `ar-38`

then after clicking the result dsub makes the request `getArtist.view?c=DSub&id=38`, requesting the artist with id `38` not `ar-38` like the server returned. so the server failed to recognise that id

is there a reason dsub interprets the id like that to just take the digits after the hyphen? 

thanks!

**Comment by daneren2005** [comment]
I'm not really seeing anywhere where it would be stripping the "ar-" from the result.  Care to share a dummy account where I can see the results directly with dsub.android@gmail.com?

**Comment by sentriz** [comment]
sent! thanks

**Comment by daneren2005** [comment]
I don't see it. Are you sure you sent to dsub.android@gmail.com?

**Comment by daneren2005** [comment]
Nevermind checked in spam and found it

**Comment by daneren2005** [comment]
Looks like in order to get the search content provider to work I added "ar-" to the ids on one end and removed them on the other.  I fixed it by just adding a dsub prefix to my custom addition to the ids.  This will be fixed in the next release

**Comment by sentriz** [comment]
great! thanks very much for looking into this
