### ISSUE TITLE
DSUB screen overlays notification bar on Xiaomi Mi 10 Lite

### ISSUE THREAD

**Issue by csjjpm** [daneren2005/Subsonic#1046]
Good morning,
  love your app by the way.  I got a new phone last week and the the DSub menu is overlaying (slightly) over the notification bar of the phone.  If I am accurate and tap the bottom edge I can get into settings etc.
![Screenshot_2021-01-13-08-54-38-256_github daneren2005 dsub 1](https://user-images.githubusercontent.com/2385260/104429552-a60bdb80-557d-11eb-89ec-71c9b0ce6c0d.jpg)

The screen dimensions listed on the Mi website for this model:
6.57" AMOLED TrueColour display
AMOLED
2400×1080 20:9
Gamut: 98%(typ)
Contrast ratio: 4,300,000:1(typ)

I hope you can include this in the next release.
thank you
Paul

**Comment by daneren2005** [comment]
Can you try the latest version listed under releases on GitHub?

**Comment by csjjpm** [comment]
Hi,
  Yes 5.5.2.R2 has worked.  Really sorry for wasting your time.
thanks again
Paul

**Comment by daneren2005** [comment]
No problem!
