### ISSUE TITLE
Access favorite/starred songs from overview 

### ISSUE THREAD

**Issue by metalheim** [daneren2005/Subsonic#1050]
I'd like a way to access all my favorite/starred songs, preferably from the "overview" pane.

Am I missing something? In the overview pane, I only find "Albums" and "Videos".
It feels wrong, that I can "star" songs from dsubs UI, but I'm unable to access them afterwards. 

I know this is more of a question/feature request, but I didn't know where else to put this.
Please let me know if that's the wrong

**Comment by daneren2005** [comment]
From the Home tab there is an option for Starred.  If it isn't there it is most likely due to using a non Subsonic server which claims to be an older version of the API before that was added.
