### ISSUE TITLE
Android Auto voice commands not working anymore

### ISSUE THREAD

**Issue by amoranvalero** [daneren2005/Subsonic#1053]
I have noticed from last integrated version of Android Auto that command voices do not work in D'sub. Assistant accept commands like "play AC-DC" do not work when in previous version operated properly in D'sub.

Has anyone experimented this behavior too? I love android auto integration for D'Sub but this feature is critical for all drivers I guess. Can you investigate whether is a defect or variation on how Google assistant/android auto provide the commands integration.

My experiments were carried out in English and Spanish and no response at all.

**Comment by amoranvalero** [comment]
After last Google Assistant update service is working like a charm again. Just a pitty Google's position on products not theirs. :) Thanks guys

**Comment by daneren2005** [comment]
Glad to hear that!  Sorry I hadn't gotten around to pulling up the Auto emulator to try this out
