### ISSUE TITLE
DSub doesn't load files from server

### ISSUE THREAD

**Issue by hungryandgrumpy** [daneren2005/Subsonic#1073]
Env: Android 11 on Asus Rog 5, Dsub 5.4.4

Dsub can connect and shows everything such as Artist, Albums etc fine. It also plays fine but it doesn't download the files. When I select a song Dsub just displays "Downloading - 0 bytes" but nothing ever happens.

I've already tried several times to uninstall and reinstall after clearing cache. I tried it without rebooting, with rebooting. Dsub is a great app and I love it to bits, been using it for years. 

Please advise - I'd love to continue using this nifty app

**Comment by womble75** [comment]
I've had this a few times, in my case it's usually my server (airsonic) that's the problem. Restarting the airsonic service and/or checking the music drive is mounted/mapped and accessible to airsonic fixes it for me

**Comment by hungryandgrumpy** [comment]
Thank you @womble75, I just did that and also the full ritual of uninstall and reinstall after clearing cache. But the result is still "Downloading - 0 bytes"

**Comment by hungryandgrumpy** [comment]
For no apparent reason, somehow Dsub downloads files just fine. After countless uninstall and reinstall and restarting airsonic service, I let it rest for a few weeks. And suddenly, it works fine again.
