### ISSUE TITLE
DSub App Genre -> Artists?

### ISSUE THREAD

**Issue by juzipar** [daneren2005/Subsonic#1084]
Hi,
I'm new to the DSub Android App.
I'm using ampache as my subsonic-compatible server.

When I Chooses Genres -> <a particular genre>
The app shows all albums in that genre. Is there a way to configure the app s.t. it lists all the artists in that genre?
Or would I have to configure ampache diffrently, s.t. it lists the artists?
Actually, when I click on an genre (Tag) in the in the ampache web-UI it lists all the artists first. 

Thanks in advance

**Comment by GEkuL** [comment]
@juzipar 
Hi, have you found the answer to the issue?

**Comment by juzipar** [comment]
No, I ended up not using DSub but stick with my logitech media server and the Orange-Squeeze app for the time being.
