### ISSUE TITLE
DSub sync/cache with Airsonic 11 dumps all files into main cache folder with no artist\album sub-folder structure

### ISSUE THREAD

**Issue by MitchMcHenry1** [daneren2005/Subsonic#1093]
Note: I originally [posted this in the Airsonic Advanced project](https://github.com/airsonic-advanced/airsonic-advanced/issues/873#issue-1180957241) and was directed that the problem is with DSub, not Airsonic Advanced.

I suspect it's also the reason for [DSub can't differentiate songs with same title #1077](https://github.com/daneren2005/Subsonic/issues/1077#issue-994289919).  Poster didn't mention server version, but sounds like same symptom.

## Problem description

Finally upgraded from vanilla Airsonic 10.6 to Advanced 11 this week and found a major problem syncing/caching new albums to DSub.  All newly synced/cached albums showed the same cover art in DSub even though it was correct in web.  Turns out with Airsonic 11 all synced/cached files get dumped into the main cache folder in DSub without any sub-folder structure (no artist\album folders).  Because all files are piled into one folder there's only one albumart.jpg, so all newly synced albums show same art.  And obviously, thousands of mp3s in a single folder with no organization is less than ideal.

### Testing/research steps
* Reverted back to _vanilla_ 10.6 and confirmed that syncing with DSub correctly reproduces artist\album subfolders in DSub cache
* Upgraded to _advanced_ 10.6 and confirmed that artist\album subfolders in DSub cache are still created as expected
* Finally, upgraded to 11 again and confirmed artist\album subfolders are no longer created in DSub cache and all files are dumped in main cache folder
* Thought transcoding could possibly have something to do with it, but confirmed transcoding settings and bins are same in all 3 cases (default flac -> mp3 settings with recent ffmpeg)

### Steps to reproduce

1. Connect DSub to Airsonic 11 server
2. In DSub, manually select any track or album to cache or use any of the automated syncing features
3. After DSub download completes, check cache folder.  Files will be in main cache folder instead of artist\album sub-folders
4. Do the same with any 10.6 server (vanilla or advanced) and cached files will be in artist\album sub-folders (expected behavior)

## System information

 * **DSub version**: [5.5.1](https://github.com/daneren2005/Subsonic/releases/tag/5.5.1) (latest on Play store), Galaxy 20+ Android 12
 * **Server version**: [airsonic.war.11.0.0-SNAPSHOT.20220320083637](https://github.com/airsonic-advanced/airsonic-advanced/releases/tag/11.0.0-SNAPSHOT.20220320083637)
 * **Operating system**: Windows 10
 * **Java version**: 17.0.2
 * **Proxy server**: IIS
 * **Language**: English

**Comment by daneren2005** [comment]
DSub caches files based on https://github.com/daneren2005/Subsonic/blob/edge/app/src/main/java/github/daneren2005/dsub/util/FileUtil.java#L342.  I haven't messed with this code in a while, but it looks like it is basing the cache location on the path if it exists, and falling back to the album/artist if those don't exist.  Here is an example of what the real subsonic API is returning: http://www.subsonic.org/pages/inc/api/examples/directory_example_2.xml.  My guess is that Airsonic decided to not require one of those fields that DSub relies on to work.  Without seeing what their API is returning I can't help too much.

In the beginning I was willing to make changes for different servers, but it has become too crazy with all of the different servers just doing whatever they want with the API lately.  Unless it is something DSub is really doing wrong, I don't intend on making any changes for subsonic-like API's breaking with the official API.

**Comment by MitchMcHenry1** [comment]
@daneren2005 - thanks for the info and quick response. I tried calling the API myself and it seems to be returning expected results.  But still anything synced ends up in root of cache folder.  Anything else I can try or provide that would help debug this?  

GET https://MyAirsonic11/rest/getMusicDirectory?id=76327
200 OK
```
<?xml version="1.0" encoding="UTF-8"?>
<subsonic-response
    xmlns="http://subsonic.org/restapi" status="ok" version="1.15.0">
    <directory id="76327" parent="76317" name="Talking to a Stranger" playCount="13">
        <child id="76357" parent="76327" isDir="false" title="Talking to a Stranger" album="Talking to a Stranger" artist="No Zu" track="1" year="2020" genre="Electronic" coverArt="76327" size="58123739" contentType="audio/flac" suffix="flac" transcodedContentType="audio/mpeg" transcodedSuffix="mp3" duration="254" bitRate="1804" path="No Zu\Talking to a Stranger\01. Talking to a Stranger [No Zu - Talking to a Stranger].flac" isVideo="false" playCount="7" created="2021-10-31T00:07:44.549Z" albumId="5798" artistId="1886" type="music"/>
        <child id="76358" parent="76327" isDir="false" title="Sensation" album="Talking to a Stranger" artist="No Zu" track="2" year="2020" genre="Electronic" coverArt="76327" size="73282088" contentType="audio/flac" suffix="flac" transcodedContentType="audio/mpeg" transcodedSuffix="mp3" duration="323" bitRate="1793" path="No Zu\Talking to a Stranger\02. Sensation [No Zu - Talking to a Stranger].flac" isVideo="false" playCount="6" created="2021-10-31T00:07:44.558Z" albumId="5798" artistId="1886" type="music"/>
    </directory>
</subsonic-response>

```

**Comment by daneren2005** [comment]
You are right, that looks completely valid to me.  Could you create a temp username/password I could use to connect to your server to debug?  You could email it to dsub.android@gmail.com so it isn't public, and as soon as I am done with my testing you could delete it.  It also doesn't need any admin permissions or anything.

**Comment by FacialLeather** [comment]
Hey there, it appears that subscribing to your repository, we are auto subscribed to each thread and its updates? At first I thought this was related to my question (4 days ago) on the cache location. My intention is not to hijacks this thread, but I have been receiving notifications for it since the beginning. cheers

**Comment by MitchMcHenry1** [comment]
> You are right, that looks completely valid to me. Could you create a temp username/password I could use to connect to your server to debug? You could email it to [dsub.android@gmail.com](mailto:dsub.android@gmail.com) so it isn't public, and as soon as I am done with my testing you could delete it. It also doesn't need any admin permissions or anything.

Done. Sent email with details.  Thanks so much for looking into this.

**Comment by daneren2005** [comment]
Looks like it is because base Subsonic always returns the path as forward slashes even on Windows installations where it really is a backslash, and this version of Airsonic is returning the paths as backslashes.  Are you installing Airsonic on a Windows machine?

**Comment by MitchMcHenry1** [comment]
>Are you installing Airsonic on a Windows machine?

Yep, Windows 10.  Thanks so much for tracking this one down.  I really appreciate it.

**Comment by MitchMcHenry1** [comment]
Just wanted to confirm that 5.5.3 solves this problem and cached files are ending up in artist/album folder structure as expected.  Thanks again for looking into this and turning it around so quickly

**Comment by gorman42** [comment]
Happened on this page while checking for DSub/Airsonic compatibility/troubleshooting.

Wasn't aware that Dsub had been updated, I was still at 5.5.1. Isn't it updated anymore on GooglePlay?
