### ISSUE TITLE
Play Next option is not available for tracks, only for complete albums

### ISSUE THREAD

**Issue by sigsergv** [daneren2005/Subsonic#1097]
In track context menu the only play option is Play Last. For albums there is also Play Next.

The same thing for multiple tracks selection menu.

![image](https://user-images.githubusercontent.com/1030732/162867938-c30c7fdf-e0e5-4c3c-b03f-526e2614a465.png)

**Comment by daneren2005** [comment]
There is an option under settings appearance for that

**Comment by sigsergv** [comment]
Thank you!
