### ISSUE TITLE
Can't connect to server using Letsencrypt SSL

### ISSUE THREAD

**Issue by SenorSmartyPants** [daneren2005/Subsonic#1100]
I'm using DSub 5.5.3 trying to connect to my server using an SSL certificate issued by letsencrypt.org (using the SWAG container to get the cert). DSub will say "Connection failure. Problem occurred communicating with the server...." 

I tested the REST API by going to https://navidrome.example.com/rest/getLicense?u=XXX&p=XXX&v=1.12.0&c=myapp and that works fine in chrome, SSL is valid. I also can connect successfully to the same server url using Audinaut and Substreamer.

I'm not sure if this is related, but perhaps DSubs trusted certificates are out of date?
https://letsencrypt.org/2020/09/17/new-root-and-intermediates.html

**Comment by GEkuL** [comment]
@SenorSmartyPants hi there,

I have the same setting and DSub works perfectly fine.

Perhaps you've not set up _https://_ at the beginning of you server address, or you didn't set up force SSL on you NPM.

**Comment by SenorSmartyPants** [comment]
I had the address set correctly yesterday but it wasn't working. Tried it again today on two different devices and it's working fine. So IDK what happened.
