### ISSUE TITLE
Opus (replay)gain not working again?

### ISSUE THREAD

**Issue by dblacknc** [daneren2005/Subsonic#1142]
This is DSub 5.5.3 downloaded here.   I have some native Opus files and also prefer to transcode to Opus.
I'd also like to use replaygain with Opus.   I saw an earlier issue closed, saying Opus replaygain now worked.

Trying every combo I can think - and looking at the code, seems like something should indeed work.  None of them do:

1. R128_TRACK_GAIN=(value)
2. playback gain=(non_zero_value) and no other tags
3. R128_TRACK_GAIN=0 and playback gain != 0

Applying the usual REPLAYGAIN_* tags to MP3 and Vorbis files works fine.   I've also tried using ffmpeg libopus as well as opusenc to encode, and r128gain to calculate gain and tag.

**Comment by dblacknc** [comment]
Looks like I can't attach the test .opus files, so I'll provide output of opusinfo for each.  I also verified they are cached on my phone as is (as below):

$ opusinfo test.opus
Processing file "test.opus"...

New logical stream (#1, serial: 3071bd51): type opus
Encoded with libopus 1.3.1
User comments section follows...
        R128_TRACK_GAIN=-1126
Opus stream 1:
        Pre-skip: 312
        Playback gain: 0 dB
        Channels: 2
        Original sample rate: 44100Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   1000.0ms (max),  986.2ms (avg),  600.0ms (min)
        Total data length: 340472 bytes (overhead: 0.941%)
        Playback length: 0m:28.577s
        Average bitrate: 95.31 kb/s, w/o overhead: 94.42 kb/s
Logical stream 1 ended

$ opusinfo test-pbgain.opus 
Processing file "test-pbgain.opus"...

New logical stream (#1, serial: 3071bd51): type opus
Encoded with libopus 1.3.1
User comments section follows...
        R128_TRACK_GAIN=0
Opus stream 1:
        Pre-skip: 312
        Playback gain: -4.39844 dB
        Channels: 2
        Original sample rate: 44100Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   1000.0ms (max),  986.2ms (avg),  600.0ms (min)
        Total data length: 340472 bytes (overhead: 0.941%)
        Playback length: 0m:28.577s
        Average bitrate: 95.31 kb/s, w/o overhead: 94.42 kb/s
Logical stream 1 ended

$ opusinfo test-pbgain+no_r128.opus 
Processing file "test-pbgain+no_r128.opus"...

New logical stream (#1, serial: 3071bd51): type opus
Encoded with libopus 1.3.1
Opus stream 1:
        Pre-skip: 312
        Playback gain: -4.39844 dB
        Channels: 2
        Original sample rate: 44100Hz
        Packet duration:   20.0ms (max),   20.0ms (avg),   20.0ms (min)
        Page duration:   1000.0ms (max),  986.2ms (avg),  600.0ms (min)
        Total data length: 340451 bytes (overhead: 0.935%)
        Playback length: 0m:28.577s
        Average bitrate: 95.31 kb/s, w/o overhead: 94.42 kb/s
Logical stream 1 ended

**Comment by dblacknc** [comment]
Closing - I saw the second issue now, fixed as of April 22... and DSub 5.5.3 was released on April 1.

**Comment by dblacknc** [comment]
Confirmed - just built from the master and the Opus replaygain tags now work - thanks!

**Comment by daneren2005** [comment]
Yeah I really need to do some updates to the API versions so I can release a new version with all of the latest fixes.  The store version is pretty far behind at this point.
