### ISSUE TITLE
Hide album cover art from Android Gallery

### ISSUE THREAD

**Issue by EchelonForce** [daneren2005/Subsonic#115]
Is there any way to obscure the cached album art so it is less visible in the photo gallery?

As it stands, with a cover.jpg in every artist/album folder, the photo gallery adds these as a a whole bunch of top level "Albums"...sort of defeating the purpose of that view. 

Personally I'd be satisfied with a single albums folder in the sdcard/subsonic directory (as is done in the basic app). It still shows up in the photo gallery but is less impactful. 

Ideally I'd like it to simply use the album art in file tags (if they're available in the cache copies from the server)...That's the whole reason I spent hours of my life adding good images to my libraries meta data...

**Comment by pwepwe973** [comment]
same problem.
but it's a shame that it's all or nothing, why there is no possibility to just hide the images, without hiding the audio files at the same time as the images. because maybe I don't want to see the images but want to be able to use the audio files with other application.
