### ISSUE TITLE
Android Auto doesn't show DSub as an option (FDroid edition, even with dev mode on)

### ISSUE THREAD

**Issue by Vista2003** [daneren2005/Subsonic#1166]
Version 5.5.3
Android version: 14 (Pixel 7a)
Android Auto version: 12.3.642634

I'm having an issue where DSub doesn't show up in the Android Auto menues, I've tried the developer option > Unknown sources option and that doesn't seem to work either as seen below:
![Screenshot_20240727-184723](https://github.com/user-attachments/assets/25fd81fa-61e2-4b1b-8ed6-77bbefa46b55)
![Screenshot_20240727-184732](https://github.com/user-attachments/assets/e155340d-c791-4723-97d6-c1dabff3f445)

**Comment by daneren2005** [comment]
It's been a while since I've played with this, but I'm pretty sure Android Auto requires the Google library which FDroid removed from their build to keep it pure open source

**Comment by Vista2003** [comment]
I've just reinstalled the app from the GitHub version and it does show in the Android Auto launcher.


Thanks!
![Screenshot_20240730-090735.png](https://github.com/user-attachments/assets/0ed6d052-7b89-47c5-80ae-341a9726aaf6)
