### ISSUE TITLE
Inclusion into the F-Droid repository

### ISSUE THREAD

**Issue by Rovanion** [daneren2005/Subsonic#432]
Good evening!

I've modified the DSub app so that it no longer depends on the Google Play services. This removes the support for the Chromecast.

The reason why anyone would do this is to include it in the F-Droid app repository. A collection of completely free and open source applications. For it to be included in this repository it cannot link to non-free libraries. Note that F-Droid has nothing against the Chromecast or communication with it; only against non-free software.

I'm wondering if you're interested in maintaining the noPlay branch in your repository or if I should maintain it in my fork: https://github.com/Rovanion/Subsonic/tree/noPlay

**Comment by daneren2005** [comment]
I'm not sure if that is possible to specify compile time arguments like that, but I will look into it.
