### ISSUE TITLE
Recent versions of DSub are missing from F-Droid

### ISSUE THREAD

**Issue by rbarlow** [daneren2005/Subsonic#442]
Hello!

I noticed recently that you have made several releases since the last version that is available in [F-Droid](https://f-droid.org/repository/browse/?fdfilter=dsub&fdid=github.daneren2005.dsub). According to that page, it's due to the dependency on Google Play Services, which is not available to users who don't have the Google Play Store.

Would you consider if it's possible to either drop this dependency, or make it an optional dependency? Your fans love DSub, and we'd love to see your new releases in F-Droid!

Let me know if there's any way I can help, and thanks for making great free software (Version 4.3 is still pretty sweet)!

**Comment by daneren2005** [comment]
No that is up to them.

**Comment by rbarlow** [comment]
There are Android users who do not have Google Play services who now cannot use updates from DSub. I, for example, am one of these users. I do not trust Google and I do not want their closed source software on my device because I do not know what it is doing with my personal information.

However, I really like DSub! I wish I didn't have to choose between freedom and proprietary software.

As I understand it, Google has been removing libs from AOSP and proprietizing them, restricting developers from enabling their users to choose freedom. Is this what happened in your case? Was there a lib that got moved into play services that you depended on? If so, I'd like to learn more about this so that perhaps we can develop a solution that allows everyone freedom.

**Comment by rbarlow** [comment]
In other words, I'd like to help if I can!

**Comment by daneren2005** [comment]
Chromecast support just requires play services. I already don't require it to be on the system to run DSub. It still runs just fine without it, but in order to support Chromecast you still have to link against the support libs. FDroid wants me to maintain a separate branch without that linkage and that I refuse to do. I understand your ideology about Google, but I am not doing extra work just because of it ;)

**Comment by peterrus** [comment]
This might be easier using a plugin/service locator like architecture to which the google play portion (encapsulated as a seperate library) identifies at runtime. Just a thought

**Comment by daneren2005** [comment]
It does identify if it is installed at runtime. I'm not requiring users to download a separate plugin just for this though.

**Comment by rbarlow** [comment]
On 03/15/2015 10:16 AM, Scott Jackson wrote:
> It does identify if it is installed at runtime. I'm not requiring users
> to download a separate plugin just for this though.

Interesting. Would it be possible to achieve an "included plugin" of
sorts? I'm imagining something where it's not a separate download for
users who have Google Play, but users who don't can continue to use the
features that do not depend on those libraries. Essentially, it would be
the same APK that would work for both kinds of users, and some of them
would just be presented with more features than others.

Would that be feasible?

-- 
Randy Barlow

**Comment by daneren2005** [comment]
https://github.com/daneren2005/Subsonic/blob/master/src/github/daneren2005/dsub/util/MediaRouteManager.java#L66

It already does that.  If there are no GooglePlayServices installed on the device, it marks ChromeCast as unavailable and doesn't try to use it.

**Comment by rbarlow** [comment]
On 03/15/2015 06:01 PM, Scott Jackson wrote:
> https://github.com/daneren2005/Subsonic/blob/master/src/github/daneren2005/dsub/util/MediaRouteManager.java#L66
> 
> It already does that. If there are no GooglePlayServices installed on
> the device, it marks ChromeCast as unavailable and doesn't try to use it.

Oh cool, so is it just a matter of how it gets built for f-droid?

Is it possible to use pre-compiler macro-style statements in Java to
include or dis-include the import statements that deal with Play
services, so that f-droid could still build the app? I'm mostly a Python
guy these days, so forgive me if that's a silly question.

Thanks for letting us know the details of the issue!
