### ISSUE TITLE
Duplicates in Podcasts list

### ISSUE THREAD

**Issue by Uddasa** [daneren2005/Subsonic#445]
I've got an issue with the podcast list.
Since I've migrated my Subsonic server all the entries are doubled when I'm offline (see screenshots below).

If I remove a podcast from one folder, it's also removed in the duplicate.

![2015-01-27 09 36 38](https://cloud.githubusercontent.com/assets/1932226/5916376/c0d2e670-a610-11e4-93a3-b56f6ad13b33.png)
![2015-01-27 09 36 50](https://cloud.githubusercontent.com/assets/1932226/5916377/c0d333e6-a610-11e4-8107-0f91779f5b45.png)

**Comment by daneren2005** [comment]
Does the new server have a different url than the old one (ie: not just a hardware swap)?

**Comment by Uddasa** [comment]
Yes it's a different IP address.
And to be precise it's was not a "real" migration, I just installed Subsonic on a new server and set the same parameters (as it's just a few podcasts and one music folder it was easier this way).

**Comment by daneren2005** [comment]
I started looking at this, and I'm not sure what the screenshots are supposed to convey.  I don't see any duplicates there...

**Comment by Uddasa** [comment]
In the first screenshot you see my online podcasts list, which is OK.
But in the second one my offline list which is not OK : you see "Morceaux Choisis" and "Le Player Club" twice, but there should be only one of them.
![c0d333e6-a610-11e4-8107-0f91779f5b45](https://cloud.githubusercontent.com/assets/1932226/5971855/fe4068bc-a84e-11e4-84ae-2562db8fa042.png)
