### ISSUE TITLE
[New Feature] Add podcast count

### ISSUE THREAD

**Issue by Uddasa** [daneren2005/Subsonic#447]
I think it may be useful to display the number of podcasts inside a folder directly in the list.

Here is a quick mockup of what I mean:
![2015-01-27 09 36 38](https://cloud.githubusercontent.com/assets/1932226/5939057/bcb6a41e-a700-11e4-80c5-a56eb3d7a779.png)

**Comment by daneren2005** [comment]
That is not a part of the metadata sent by Subsonic so I will not be adding this.

**Comment by Uddasa** [comment]
Hi,

Just a quick update on that one, which is still annoying me a lot ;)

I know that subsonic API doesn't give you the count of the podcasts directly, but I don't understand why you can't do it. I don't agree with your response in fact (even if it's from a year ago).

In "getPodcastChannels" when you request the list of podcasts, why don't you set the parameter "includeEpisodes" to "true", and then in your PodcastChannelParser "parse" method you could just count the number of "episodes" objects?
Of course you would need to add a field in "PodcastChannel" object to store it, and append it to the name when it's displayed.

Maybe I'm missing something but I think that it's possible to implement that.
I may consume a bit more data but it could be reaaaaly nice to see the count on the podcasts title, and avoid us to go through each podcast till we find one with items inside.

I know it's not a blocking issue, but in the future, if you could take a look at it, it would be nice.

Regards,
Uddasa.
