### ISSUE TITLE
Use of all entries in a list for shuffled playlists

### ISSUE THREAD

**Issue by magnumforce2006** [daneren2005/Subsonic#449]
Currently, the behavior for creating a shuffled list of certain areas (genres, decades, etc.) will only pull from the first number of entries in the list. This results, often, in playlists that only include entries starting with the first number of letters in the alphabet.

It would be nice to have the feature include the entire list in the generation of the shuffled playlist, or have that option.

**Comment by daneren2005** [comment]
That could take a very long time though.  Those list are of arbitrary length, and there is a limit for how many I can query for at a time.

**Comment by daneren2005** [comment]
I'm not going to implement this because it would be impossible to control how long it would take or if it would ever finish in some cases.
