### ISSUE TITLE
search doesn't work when using spaces

### ISSUE THREAD

**Issue by marlop** [daneren2005/Subsonic#455]
search doesn't work when using spaces, doesn't matter where the space is positioned

DSub 4.9.2 (https://github.com/daneren2005/Subsonic/releases/download/4.9.2/DSub.4.9.2.apk)
server: Madsonic 5.1.5200 (can't test with subsonic)
moto x 2ºgen
android 5.0

the error is: Illegal character in query at index96: https://server-url/rest/search2.view?u=user&p=password&v=1.2.0&c=DSub&query=seu jorge&artistCount=10&albumCount=20&sonCount=25

if you need any more info just ask

**Comment by daneren2005** [comment]
It works on everything I own on both Subsonic and Madsonic servers.  My guess is you have a corrupted install and reinstalling will fix it.
