### ISSUE TITLE
NullPointerException when attempting to play anything

### ISSUE THREAD

**Issue by mlg9000** [daneren2005/Subsonic#460]
After the most recent update whenever I attempt to play anything with Dsub I now get NullPointerException errors 100% of the time.  I'm a long time Dsub user and have not had issues before.  I'm connecting to a Subsonic 5.1 server.

**Comment by daneren2005** [comment]
I'm pretty sure I have a fix.  If you email me I can give you a test apk and make sure before releasing the fix.
