### ISSUE TITLE
Request for support for rest/getVideos.view?

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#463]
Request for support for rest/getVideos.view?  to be able to retrieve my Ampache Videos catalog.  I have a Videos catalog in my Ampache server and when I navigate to Library -> Select Folder -> Videos Folder, DSub requests:

/ampache/rest/getMusicFolders.view?
/ampache/rest/getIndexes.view?

Subsequently, it just shows empty.

UltraSonic (the only Subsonic app that can list and subsequently play them over MX Player) has a separate "Videos" catagory on it's main screen that sends the request:

/ampache/rest/getVideos.view?

Which correctly lists my video catalog.﻿

**Comment by daneren2005** [comment]
That videos aren't showing up in the folders sounds like it is most likely an Ampache issue since videos do show up from Subsonic servers.  I will add the other request to the todo list.

**Comment by dhsc19** [comment]
Thanks.  Very much appreciate your work on this app!

**Comment by Afterster** [comment]
Mhh UltraSonic is getting videos through getVideos request whereas DSub doesn't seem to do so. How do you determine that the server has videos then?

**Comment by daneren2005** [comment]
Videos show up just like normal songs do in a library, and you click on them to play them.  The difference is Ultrasonic has a giant list of every video found anywhere on your server you can browse.
