### ISSUE TITLE
EQ settings do not persist when loading new playlist and other quirks

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#467]
I'm noticing that the EQ settings do not persist when loading a new playlist, even though the EQ check box indicates that it is on and the sliders have not changed from where I left them.  Also, after loading a new playlist, moving the sliders make no audible difference.  Then, if you were to uncheck then re-check the EQ box, the sliders remain "grayed out" and cannot be moved.  You would have to go back to the playlist screen, then return back to the EQ screen (where you will now see the EQ box unchecked).  Then re-enabling EQ will resume normal operation and moving sliders will once again work and audible differences can again be observed.

A more detailed steps to reproduce:
1.  Load an album
2.  Turn on EQ
3.  Boost a setting or settings that will give you an obvious change in tone.
4.  Go back to the playlist screen.
5.  Remove all.
6.  Re-load the same album (you can load any other album that you wish, but loading the same album will help you notice the audio differences much easier)
7.  Notice that the EQ checkbox is still ON.
8.  Go into the EQ screen and move the sliders.  Notice that moving the sliders make no audible changes.
9.  While still in the EQ screen, uncheck the Enabled box.  Then, while still in the EQ screen, check the Enabled box again.  Notice that the slider remain "grayed out" and you cannot move them.
10.  Return to the playlist screen.
11.  Go back to the EQ screen.  Notice the Enabled box is now unchecked again.
12.  Check the Enabled box.  You will now see the sliders light up and moving them will once again allow you to hear audible changes.

I'm using a Samsung S4 mini.  Maybe someone else with a different phone could verify this is not an isolated problem specific to my phone.

**Comment by daneren2005** [comment]
I have a few different devices and was unable to reproduce this issue on any of them.

**Comment by dhsc19** [comment]
Ok.  Thanks for looking into it.  I guess it may just be my phone.

**Comment by daneren2005** [comment]
You could send me a log immediately after switching to a new playlist when the EQ settings are supposed to be on.  It might be throwing an internal error, though it might or might not be one I can fix depending on the nature of the error.

**Comment by dhsc19** [comment]
It seems to happen on Bluetooth, and not with regular plugged in headphones.  How do I pull logs from the app?

**Comment by daneren2005** [comment]
Home -> menu -> Send Log. Though if it only happens on Bluetooth there is an even higher chance it is a system issue I can't work around.

**Comment by dhsc19** [comment]
Sorry it took a while, I just sent the log.
