### ISSUE TITLE
Widget Activation Pauses Running Song

### ISSUE THREAD

**Issue by ghuacc** [daneren2005/Subsonic#468]
Pressing on the song cover or name/info of any widget pauses playing the current song when the player main window pops up. Also browsing through the library and pressing on the song cover/name on the bottom-of-the-page-player pauses. Seems to be an regression bug in 4.9.3.

**Comment by daneren2005** [comment]
Not on anything I own

**Comment by ghuacc** [comment]
After uninstalling, removing all app data and re-installing DSub, the error does not occur anymore.
