### ISSUE TITLE
Sharing missing?

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#469]
I have show sharing in menus enabled, but I can't find it in any menu for individual song or full album.

**Comment by daneren2005** [comment]
There is a server permission "User is allowed to share files with anyone".  If that is not set on the user the option is automatically hid.  Can you check on the server and make sure it is?

**Comment by dhsc19** [comment]
I'm using Ampache server and I can create share links with Ultrasonic.  Can you tell me what the difference is between how DSub handles this versus Ultrasonic (what DSub is looking for specifically)?  Maybe this is something I can bring up to Ampache dev if they need to update their Subsonic API compatibility.  Thanks.

**Comment by daneren2005** [comment]
DSub checks permissions where Ultrasonic does not. What is an example getUser returned by Ampache? Here is an example of what stock subsonic returns and DSub expects: http://www.subsonic.org/pages/inc/api/examples/user_example_1.xml

**Comment by daneren2005** [comment]
Ampache supposedly added a way to tell Ampache from Subsonic. If I know what they return different I can handle it. I imagine its going to be a issue for more than just sharing.

**Comment by dhsc19** [comment]
I'm not sure if this is the correct format:

https://xxx.xxxxxxx.xxx/ampache/rest/getUser.view?u=user&p=enc:xxxxxxxxxxxxxx&v=1.2.0&c=DSub&id=200001695

But it is returning:

<subsonic-response type="ampache" version="1.11.0" status="failed"><error code="10" message="Required parameter is missing."/></subsonic-response>

I'll ask Ampache dev if there is any further info regarding getUser.

**Comment by daneren2005** [comment]
That format looks correct, but you did not include anything (or it just doesn't appear on Github) after "returning:"

**Comment by dhsc19** [comment]
Let me see if a screen shot would work.  Looks like github is hiding the xml  https://cloud.githubusercontent.com/assets/10291198/6655107/8094b902-caab-11e4-8970-647de42d7746.png

**Comment by daneren2005** [comment]
Do you want to just email a temp username/password and I can fix it more easily.  I can also look at the other permission based functions and make sure they work with Ampache too.

**Comment by dhsc19** [comment]
OK.  I'll email you the info.  Thanks!

**Comment by daneren2005** [comment]
After putting it I see what was wrong with how you created the url.  There is no id, you pass in a username. 

ex:
https://xxxxx/rest/getUser.view?v=1.2.0&c=DSub&username=subsonic&u=xxx&p=xxxx

\<subsonic-response type="ampache" version="1.11.0" status="ok"\>\<user username="subsonic" email="daneren2005@gmail.com" scrobblingEnabled="false" adminRole="false" settingsRole="true" downloadRole="true" playlistRole="true" coverArtRole="false" commentRole="false" podcastRole="false" streamRole="true" jukeboxRole="false" shareRole="false"/\>\</subsonic-response\>

This does appear to be labeling sharing as false though.

**Comment by daneren2005** [comment]
In the Ampache issue it was confirmed that there should be a way to change the share permission, so this isn't a compatibility issue.  It is either a user or server error, so I am going to close this issue.

**Comment by dhsc19** [comment]
Ok.  Thanks.
