### ISSUE TITLE
Now Playing: Batch Mode

### ISSUE THREAD

**Issue by daneren2005** [daneren2005/Subsonic#476]
Add batch Delete Cache, Remove, etc.. to Now Playing list.

**Comment by DeadDjembe** [comment]
I second this.  It would be great to download the entire Now Playing list on wifi to save on data.  A work around is possible by setting the Number of Songs to Preload on Wifi to unlimited, but having an option in the Now Playing list menu to do it on demand would be ideal. 

Also, I did not see a way to add a random list of songs to the end of the now playing list.  When generating a new random song list, it automatically creates a new Now Playing list.  Amending the current playlist would be a nice feature (add to next or add to end)
