### ISSUE TITLE
Play at Plug in headphones

### ISSUE THREAD

**Issue by 876974** [daneren2005/Subsonic#477]
Customize. Automatic application launch and play the latest music when headphones are connected to the phone

**Comment by daneren2005** [comment]
Personal notes:

http://stackoverflow.com/questions/4202046/which-permission-required-in-order-to-get-action-headset-plug-inside-broadcast-r
https://github.com/jakebasile/hearing-saver/blob/master/src/com/jakebasile/android/hearingsaver/RegistrationService.java#L46
