### ISSUE TITLE
Download option in create share dialog

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#483]
I've communicated with Ampache dev about the possibility of allowing the Subsonic API in Ampache to have the option allow/disallow downloads when creating a shared object through the mobile app.  In the Ampache web interface, you can enable or disable allow downloads when creating a shared object.  I don't know if Subsonic has the same feature.  Since, DSub currently does not have this kind of option when creating shared objects, I'm hoping you might be able to coordinate with Ampache devs to see if this might be a possible feature that can be added.

**Comment by daneren2005** [comment]
I honestly do not want to add Ampache specific functionality at this time.  My Madsonic user base is much greater and there is plenty of Madsonic specific functionality I haven't even gotten around to adding yet.

**Comment by dhsc19** [comment]
Not a problem.  Completely understandable.  Maybe keep it in the back burner and reconsider when time/resources become available in the future.  Definitely appreciate your work.
