### ISSUE TITLE
Kepp whole library in sync

### ISSUE THREAD

**Issue by bwadrochit** [daneren2005/Subsonic#484]
Hi,
I trie to use DSub to keep synchronized all my subsonic music files. I found that there is no specific option for this neither any way to do it manualy (e.g. a 'select all' option in any view, and 'synchronize selection' or something like that). And selecting 3000+ files manually is not an option.
I found a sort of workarround consisting of a script executed daily on my server that generates a playlist with all my music files, and the built-in daily playlist import of Subsonic. This way I can have an up to date playlist with all my music files. 
If I tell DSub to keep this playlist synchronized, then all my new music files are downloaded during the night. This works great. However DSub fails to synchronize deletions, which results in local files that have no more correspondences on the server. I know that the files removed from a synchronized playlist are supposed to be unpinned, but it appears to be not realy reliable, and it is not the behavior that I'm looking for as unpinned songs are not automatically deleted.
One could think of several ways to fix this. But maybe a 'garbage collector' for automatic deletion of 'orphin' files (with no more correspondences on the server) would be enough for me. Of course a specific option in the settings for keeping a whole media folder in sync would be ideal.

Thanks for the good work.

**Comment by daneren2005** [comment]
I am not going to add a entire library sync as that is not even remotely what I am designing DSub for.  If you can find a way to reproduce the playlists not unpinning removed songs feel free to open up a ticket for it since that I definitely will fix.  Since there is no way to check for orphan files besides crawling the entire server I will not be adding that either.

**Comment by bwadrochit** [comment]
Ok I understand you want to avoid any feature that may bee too heavy and keep the app lightweight. In the end my problem is more about what kind of controll the user have over the cached files, whatever the size that is in sync. Currently DSub offers an aproach based on the size off the cache folder. And so my request should rather be about DSub also offering an approach based on the set of files that are cached. I am not sure if I should open another issue for this.
