### ISSUE TITLE
Sort albums by year not working?

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#485]
I have the option to sort albums by year turned on, but I'm still seeing this:

![screenshot_2015-04-04-15-04-41](https://cloud.githubusercontent.com/assets/10291198/6994906/e872ecf4-dade-11e4-89f5-d8bd22fce52e.png)

A bug?  Or Ampache limitation?

**Comment by daneren2005** [comment]
Pretty sure it is a Ampache bug.  Example with no year information:

    <directory id="100001431" name="Michel Petrucciani"><child id="200001821" album="100 Hearts" title="100 Hearts [1984]" name="100 Hearts" isDir="true" coverArt="200001821" songCount="6" duration="3224" artistId="100001431" parent="100001431" artist="Michel Petrucciani" averageRating="0"/><child id="200001798" album="Au Theatre Des Champs-Elysees (disc 1)" title="Au Theatre Des Champs-Elysees (disc 1) [1995]" name="Au Theatre Des Champs-Elysees (disc 1)" isDir="true" coverArt="200001798" songCount="3" duration="3631" artistId="100001431" parent="100001431" artist="Michel Petrucciani" averageRating="0"/>

**Comment by daneren2005** [comment]
PS I found another issue.  If you are wondering why the artist bio picture is not loading, in getArtistInfo the artist picture is labeled as https://****/ampache/play/art//artist/1431/thumb.jpg.  See the double dash in between art and artist?  That is also an Ampache bug that will need to be fixed if you want the artist art to show up correctly.
