### ISSUE TITLE
For scroll bar to be able to skip to specific letter in the Alphabetical Album List view

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#486]
I'm wondering if it is possible to have the scroll bar in the Alphabetical Album List view to be able to skip to specific letter index the same way the Library view allows you to do so for the artist names?

**Comment by daneren2005** [comment]
No I do not want to add that since that your not really supposed to have a thousand albums under a artist.

**Comment by dhsc19** [comment]
Just for clarification, I'm not referring to the album lists under specific artists, but the "Alphabetically" category under "Album Lists" in the Home screen:

![screenshot_2015-04-06-09-06-29](https://cloud.githubusercontent.com/assets/10291198/7007880/6c5d6e36-dc42-11e4-9eb6-f0ed49eae7c9.png)

Hope you will reconsider :D

**Comment by dhsc19** [comment]
Just got the latest update.  Thanks for this.  There's a few things I'm wondering about regarding some fine tuning of this function.  In the Alphabetical Album List view, I notice that only 20 items at a time are loaded.  The indexed scrolling doesn't seem to activate until I've swiped down the list far enough to load another 20 items.  When the indexed scroll bar appears, the initial index will only cover the 40 items shown.  The list does dynamically update to add another 20 more items once it reaches to bottom and I'm holding down the scroll bar until the whole list has been retrieved.  Then, I am able to scroll through the index the same way I can in the Artist List view (from #-Z).  Is there a way to just have it load the entire Album list the same way it is able to load the entire Artists list?  I think it would make more sense that way.

**Comment by daneren2005** [comment]
No the API does not allow loading it all at once
