### ISSUE TITLE
Adding the "radio" selection to the android app

### ISSUE THREAD

**Issue by vferg** [daneren2005/Subsonic#488]
I noticed with the release of 5.0 (maybe5.1) they added the biography and similar artists info below each artists page that's pulled from one of the music info sites.  They also added a radio link which seems to basically take all the similar artists and create a playlist out of them in shuffle.  I always thought this feature was amazing before subsonic and was sad it was never added into it which I thought was due to not using tags but now that they were able to add it would it ever be possible to see this feature added into the dsub application on android?  Its such a great feature and always thought it was the 1 thing missing that would make this complete.  Thank you for all the hard work and support, the application is amazing.

**Comment by daneren2005** [comment]
It was added several versions ago right next to the play button...

**Comment by vferg** [comment]
I apologize. It appears I have not updated since 4.8.6.  Thank you again.

**Comment by daneren2005** [comment]
Yeah that is pretty old. NP.
