### ISSUE TITLE
Cannot shuffle play when selecting specific Library folder

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#490]
I can create a shuffle playlist when I select All Folders in the Library screen.  But it doesn't seem to work if I select a more specific folder.  I email a log capture.

**Comment by daneren2005** [comment]
With your test account I can confirm that it just isn't returning any results with a folder id:

    <subsonic-response type="ampache" version="1.11.0" status="ok"><randomSongs/></subsonic-response>
