### ISSUE TITLE
Music controls / fullscreen art on lock screen disappear on Samsung Galaxy 5

### ISSUE THREAD

**Issue by breenyoung** [daneren2005/Subsonic#491]
Hi there, 

As a long time fan of Dsub, I recently upgraded from an HTC One XL to a new Samsung G5.  I seem to be having an issue with the music controls persisting on the lockscreen.  If I fire up DSub pick a playlist, begin playback and turn my screen off when I click the power button again the lock screen shows with the full screen music art and music controls as expected.

If I attempt to hit the 'prev/next' controls to skip to another song, the song changes but the music controls and the full screen art disappear and i see my normal lockscreen wallpaper.  Playback continues normally and at this point the only way I can switch songs is via the small controls in the notification pulldown or via DSub itself.

As an experiment I built a playlist of the cached songs Dsub had downloaded and tried playing it with Samsung's 'Music' app that came with the phone.  The lock screen music controls and full screen art behave normally and allow track skipping without the problems above.

This is a really annoying problem as I love Dsub and it's part of my daily commute to work.  Any tips or advice would be awesome.  Would be willing to try experimental APK's for a fix!

Thanks.

**Comment by daneren2005** [comment]
I honestly have to no idea what to do about that as DSub fully obeys the lockscreen API and works on dozens of other phones just fine.  Has your G5 gotten Lolipop yet?

**Comment by breenyoung** [comment]
Thanks for the reply,

The G5 is still running 4.4.2 atm.  I found another user with this same problem on your forums from awhile back (http://forum.subsonic.org/forum/viewtopic.php?f=16&t=14369&p=62874)  but there was no traction on the thread.

It's very odd, i was trying to go back and start loading older APKs of your program in case it was something that got introduced at some point.  No luck so far.

**Comment by daneren2005** [comment]
I rarely change the lock screen stuff. Yeah that looks like another G5 user. I am getting a G6 in a day or two that I can see if it has the same issue. G5s should be getting a new android update which does away with the lock screen API altogether and just displays notifications there instead. Which version of the G5 do you have?

**Comment by breenyoung** [comment]
It's a SM-G9000W8

I refrained from grabbing the Lpop update so far as I read some issues with it, some around notifications although it may have been people not understanding how the notification system changed in Lpop.

Just as a side note to the issue.  When I tap 'prev/next' buttons on the lock screen (when the music control and art are first displaying), the next song's art does appear for a split second then it disappears and you're left with no audio controls + your default lock screen wallpaper.

**Comment by daneren2005** [comment]
It doesn't appear to be an issue on a S6 with Android 5.0.  If the issue has been fixed be a OS update, I am not going to make any changes to DSub for it.
