### ISSUE TITLE
[4.9.6] Play Controls on Notification won't work anymore

### ISSUE THREAD

**Issue by nRaecheR** [daneren2005/Subsonic#494]
The play controls (Previous,Play/Stop,Next) in the notification area won't work anymore after updating to 4.9.6 from 4.9.5.

Steps to reproduce : 

1. Open DSub
2. Play the current playlist
3. Swipe down the notification area.
4. Tap on any play control items.

Tested on Nexus 10 with Android 5.02 and Samsung Galaxy S4 with Android 5.01.

**Comment by keckelt** [comment]
I can confirm that on my Moto G with Android 4.4 (and permanent
Notification turned on).
Am 21.04.2015 20:09 schrieb "nRaecheR" <notifications@github.com>:

**Comment by daneren2005** [comment]
7df02047502ae6aff26d90466abdff468c73462a
