### ISSUE TITLE
Crash when trying to view albums alphabetically from home

### ISSUE THREAD

**Issue by mshick** [daneren2005/Subsonic#504]
Without fail this crashes. I've tried flushing every cache, rebuilding my subsonic db, nothing helps.

Clicking the menu item immediately leads to a crash. Looking through the report, looks like this [line](https://github.com/daneren2005/Subsonic/blob/master/app/src/main/java/github/daneren2005/dsub/adapter/AlbumListAdapter.java#L108) is the problem. 

I'm on a Nexus 7 gen 2.

**Comment by daneren2005** [comment]
97026ad3b3b6ca29881f5415b6862a410c219231

**Comment by mshick** [comment]
Ah, sorry. Looking forward to the new version!
