### ISSUE TITLE
Permanent Cache on sd card

### ISSUE THREAD

**Issue by Iskenof** [daneren2005/Subsonic#518]
I would like to change the Cache location to sdcard (example /storage/extSdCard/Music)
In the options works well but if you mark a song to permanet cache, it does not work.

Device: Samsung Galaxy S5
Android: 5.0
Dsub 4.3.5

**Comment by keckelt** [comment]
I don't experience this problem on my 1st Gen Moto G Lte.
Path: /storage/sdcard1/music
Android: 4.4.2
Dsub: 4.9.7

Maybe you should update your App and try again.
Am 29.05.2015 09:18 schrieb "Iskenof" <notifications@github.com>:

**Comment by Iskenof** [comment]
I try it again with the new version.
And send the logfiles.

**Comment by daneren2005** [comment]
I'm not taking issues from year old versions
