### ISSUE TITLE
Caching fails with very long track titles

### ISSUE THREAD

**Issue by evertvp** [daneren2005/Subsonic#519]
When trying to cache the Sufjan Stevens song "The Black Hawk War, or, How to Demolish an Entire Civilization and Still Feel Good About Yourself in the Morning, or, We Apologize for the Inconvenience but You're Going to Have to Leave Now, or, 'I Have Fought the Big Knives and Will Continue to Fight Them Until They Are Off Our Lands!'" it downloads the track but it doesn't ever save it. I presume this is because of a maximum allowed filename length.

**Comment by daneren2005** [comment]
File name size limits are 255 for ext3/fat32
