### ISSUE TITLE
Pin button in play queue is overlapped by scrollbar

### ISSUE THREAD

**Issue by Row** [daneren2005/Subsonic#520]
It is inconvenient when you are trying to remove a song, and the the scroll jumps to a new position instead of showing the track menu. Using a samsung s4 with lollipop.

**Comment by keckelt** [comment]
I love to be able to swipe the tracks out of the queue to delete them.
Would be more convenient if I want to delete multiple entries.
Am 08.06.2015 13:50 schrieb "Jon Borglund" <notifications@github.com>:

**Comment by daneren2005** [comment]
If all you care about is for removing songs, I have implemented swipe to remove for the next update: #232

**Comment by keckelt** [comment]
Thank you!
Am 10.06.2015 02:35 schrieb "Scott Jackson" <notifications@github.com>:

**Comment by Row** [comment]
Awesome!
