### ISSUE TITLE
Simulated media buttons not working

### ISSUE THREAD

**Issue by Belkaar** [daneren2005/Subsonic#522]
After the update from 4.5.5 to 4.9.1 I noticed that simulated media button presses are no longer working. I tried tasker and the pebble app as sources. Media buttons on bluetooth devices still work.
a downgrade to 4.5.5 restores the functionality.

**Comment by daneren2005** [comment]
DSub was changed to listen to ACTION_UP instead of ACTION_DOWN to get around hardware issues. Whatever method you use to simulate Bluetooth media events needs to be changed to do a UP action.

**Comment by Belkaar** [comment]
Unfortunately most of the software I tried does not have that option. Notably the Pebble Smart watch app.
Could this be made into a config option?
