### ISSUE TITLE
Option for Thumbs Down to equal 1 Star rating

### ISSUE THREAD

**Issue by Adthrawn** [daneren2005/Subsonic#523]
Currently, as I can see it, the Thumbs Down will skip the track but it doesn't send anything to Subsonic itself to mark the track as unwanted. This may not jive with how everyone uses it, but perhaps a flag in the settings to choose whether to also send back to subsonic a 1 Star rating when the Thumbs Down is selected.

**Comment by daneren2005** [comment]
It does send a 1 star rating.  Subsonic does not show song ratings in the Web GUI
