### ISSUE TITLE
Feature : remove only selected item in download list

### ISSUE THREAD

**Issue by Uddasa** [daneren2005/Subsonic#525]
This is a feature request : in the download list you can only remove all the files, not just one.

So when I want to add multiple albums/tracks to cache, if by mistake I add a wrong one I must remove the whole download list and then add everything again which is not very user friendly.

So please add a new option in the long clic menu to remove the selected item (or any other way if you think its better, like check-boxes, your call).

Thanks.

**Comment by daneren2005** [comment]
You mean like "Remove from queue"?

**Comment by Uddasa** [comment]
Yes exactly, remove from queue, just for one item.

Because if we cancel all the list to remove the only item we don't want, we will also cancel current download, and need to add again everything.

Why did you closed it? Did I missed the option which already exists?

**Comment by daneren2005** [comment]
It is an option in the single song menu was my point...

**Comment by daneren2005** [comment]
In the next version you will also be able to swipe to remove.

**Comment by Uddasa** [comment]
Yes it's in the current playlist, but not in the download list.

**Comment by daneren2005** [comment]
Ah, I see what you mean now.  Somehow I was missing that you were talking about the Download tab.
