### ISSUE TITLE
Feature : stream podcasts

### ISSUE THREAD

**Issue by Uddasa** [daneren2005/Subsonic#526]
Maybe it has already been asked/answered but here it is :

Is it possible with the current Subsonic API to stream the podcast instead of caching it completely?
This could save us a lot of data on our mobile plan.

If you close this ticket please tell us if it's because you can't do it, or if it's just too complicated.

Thanks.

**Comment by daneren2005** [comment]
It is possible but everything is currently set up to cache and I don't really intend to add a way to just stream. Do you actually listen to partial podcasts enough that it would save bandwidth? There are also various options to cache ahead to save on bandwidth by caching while on WiFi.

**Comment by Uddasa** [comment]
Well I'm using podcasts a lot in the car everyday (between 1 and 2 hours) and play/resume them at work also. So indeed I already try to cache them on Wi-Fi at home/work.

The thing is I have sometimes errors while playing podcasts and they are deleted in DSub (I should report that one day, but as it happen in the car I don't have time to check and send the log).
So I need to download the whole podcast again, even if I was already at half of it and that's long and kill my data plan.
Also it can be nice just to listen to one part of a podcast without downloading the whole thing.

Well it's not a really big deal but if someday you don't know what to do, you may want to implement streaming (just download a buffer and pause the download till it's at half of it or something more clever). And Maybe not only for podcasts but for music also.

Thanks for reading me.
