### ISSUE TITLE
Performance enhancement

### ISSUE THREAD

**Issue by kangyu** [daneren2005/Subsonic#528]
We are working on a project called PersisDroid (http://www.cudroid.com/PersisDroid/) for detecting potential performance issues. Our tool could find performance degradation caused by improper usage of asynchronous executions.
  We find that in some cases your app may suffer a long processing delay.

  Case:
  **Related source code** Class: [CacheCleaner](https://github.com/daneren2005/Subsonic/blob/master/app/src/main/java/github/daneren2005/dsub/util/CacheCleaner.java) Method: [clean](https://github.com/daneren2005/Subsonic/blob/master/app/src/main/java/github/daneren2005/dsub/util/CacheCleaner.java#L42)
  **Circumstance** In our testing, we found it sometimes takes long for the BackgroundCleanup task to be queuing for executed. 
  **Problem** *execute* method of AsyncTask is used for executing BackgroundCleanup task. This method executes multiple AsyncTasks in a default sequential queue. That means if two tasks are executed simultaneously, one task have to wait for another. Our testing suggest that the BackgroundCleanup task often conflicts with the task *WebViewClassic.setupPackageListener* (for Android version 4.x).
  **Suggested modification** Use *executeOnExecutor* instead of *execute* method.

**Comment by daneren2005** [comment]
CacheCleaner is the only instance of AsyncTask in DSub (and is not a problem if it takes a while to run), so I don't think it should be a problem in this case.  In your testing, does it take a long time to actually queue up the task (ie: does it block the main thread), or does it just take a while for it to actually run?

**Comment by kangyu** [comment]
The conflict instance of AsyncTask is in Android framework (WebKit) but not in your project. We found it takes a while for the task to run actually without blocking the main thread.

**Comment by daneren2005** [comment]
Taking a while to run is not a big deal for me as it is not a user facing action.  Thank you for the information though.  It's good that someone is doing checks on stuff like this.
