### ISSUE TITLE
Buffering Bug when switching to a new album

### ISSUE THREAD

**Issue by magnumforce2006** [daneren2005/Subsonic#530]
This is a seemingly intermittent bug that happens in the following scenario.

-A playlist/album is finished playing.
-A new album is selected to play
-The first song starts loading, and then the buffering message shows at the bottom of the screen.

However, nothing else happens. The state remains "buffering" even if the track fully loads. Only a restart of the app lets me play the album at this point.

Might be tough to replicate, but this happens to me a couple times a week.

**Comment by daneren2005** [comment]
I'll need you to send me a log after it happens because I have never seen that before and am unable to reproduce.
