### ISSUE TITLE
When switching to offline, automatically change to Library view

### ISSUE THREAD

**Issue by mavenius** [daneren2005/Subsonic#535]
When switching to offline mode, currently, the only option is to go back online. This requires a user to reopen the side menu and tap "Library." Every time I switch to offline, it is to play something, so it seems intuitive that the app would go to Library as soon as offline mode is selected.

**Comment by daneren2005** [comment]
I am going to put the offline toggle in the pull out drawer and if the user is on a online only tab (like home) then redirect them)

**Comment by mavenius** [comment]
That sounds perfect. Thanks!

Thank you,

Mark Avenius
