### ISSUE TITLE
Add option to skip non-cached tracks when not connected to wifi and mobile downloading is disabled

### ISSUE THREAD

**Issue by mavenius** [daneren2005/Subsonic#536]
In the interest of saving mobile data, I have Wi-Fi streaming only enabled. This means that if a track ever ends up in my playlist that is not cached and I am disconnected from Wi-Fi, playback stops, waiting for the track to be downloaded.

The obvious solution to this is to enter offline mode, but some features are limited when in this mode. For example, I cannot add to the playlist by genre when in offline mode.

What I propose is a new setting that will cause the player to skip non-cached tracks when Wi-Fi streaming is enabled and the device is on a mobile network.

With this set, a user could use the non-library album lists from the Home screen to add items to the playlist without having playback stop when a non-cached track is encountered.

**Comment by daneren2005** [comment]
Honestly, I'm not going t make that an option.  There is no reason to not just auto-skip to the next song.  I never use that option so I didn't know it didn't do that already.

**Comment by mavenius** [comment]
That works for me as well. The only implication I could see is if the entire playlist is not cached, it probably shouldn't just loop forever (I don't know how resource-intensive that would be.) Also, while it is looping, the user should be able to click an item (to clear the playlist, e.g.)

**Comment by daneren2005** [comment]
Yeah I will probably just make it do the look ahead at first, and if it loops all the way back to the start (which only matters if repeat is on) then just stop trying.

**Comment by mavenius** [comment]
This works for the use case that I originally submitted, but I just noticed that if non-downloaded songs are in the playlist and I'm offline, it still hangs on them instead of skipping.

**Comment by daneren2005** [comment]
The undownloaded songs are supposed to be automatically removed when going offline so they shouldn't be there is the first place. I will fix it in the next release.

**Comment by mavenius** [comment]
Sounds good; thanks!

Mark Avenius
Mark@Aveni.us
