### ISSUE TITLE
Multi-select in playlist view

### ISSUE THREAD

**Issue by magnumforce2006** [daneren2005/Subsonic#543]
Since we have Multi-select now enabled on the album/artist level, could we get this functionality in the playlist view? Definitely would be great for mass editing play lists on the go. Thanks!

**Comment by daneren2005** [comment]
There is multi select in the playlists. What could you possibly want to do to multiple playlists?

**Comment by magnumforce2006** [comment]
I mean from the actual view of a playlist. Selecting multiple songs therein:

https://dl.dropboxusercontent.com/u/5936941/2015-09-08%2020.33.56.png

**Comment by daneren2005** [comment]
Ah.  That already has a ticket #476.  The problem (and why I haven't implemented it yet) is that long select is already a action for drag and drop.

**Comment by magnumforce2006** [comment]
Gotcha, thanks.
