### ISSUE TITLE
Modifying  app for pay 

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#545]
Would anybody be interested in modifying this app for me for couple of bucks . I would like a home ui resign and couple of things twicked

**Comment by daneren2005** [comment]
This isn't really the place to ask, but tweaks such as?

**Comment by addisflava** [comment]
Hi Daneren Thanks for your replay . I know  its not the right place but am sysadmin and am finding it difficult to do it by my own . I have sent you an email with some of the task
