### ISSUE TITLE
Add go to artist option from album lists

### ISSUE THREAD

**Issue by mavenius** [daneren2005/Subsonic#548]
Currently, from the album lists (random, recent, etc.) there isn't a way to get to an artist. I usually have to add an album, then select a track from the playlist and go to artist.

**Comment by daneren2005** [comment]
Click the 3 dots for the album and it's already there.

**Comment by mavenius** [comment]
I could have sworn I checked there; sorry about that.

Thank you,

Mark Avenius
Mark@Aveni.us
