### ISSUE TITLE
add random songs to playlist

### ISSUE THREAD

**Issue by DeadDjembe** [daneren2005/Subsonic#549]
Greetings,

Currently, there is no way to add random songs to the end of your playlist without creating a new playlist.  To generate a random playlist from your entire music library, you must select "Library" from the menu, then click the "shuffle" button, however, this creates a new playlist.  It would be great to be able to add this to your current queue,  just as you can for an artist or album by clicking the three dots and then selecting either "Play Next" or "Play Last".  

Best,
Marc

**Comment by daneren2005** [comment]
I see no reason to add this.  When you listen to random songs from the entire library it automatically adds more songs as you go so there is never a reason to manually add more to the end.
