### ISSUE TITLE
Android lollipop modify cache folder

### ISSUE THREAD

**Issue by djdmd** [daneren2005/Subsonic#552]
On my galaxy s4 lollipop it's  impossible changing the cache directory always saying"invalid place for caching "

**Comment by daneren2005** [comment]
It has to be in a specific spot.  If it is internal/Android/data/github.daneren2005.dsub/ then you can only change it to <SDCard>/Android/data/github.daneren2005.dsub/ and nowhere else.  This is a system limitation.  The only thing DSub does to check if it is a valid location is it tries to create a file there and tell you if it is not allowed.
