### ISSUE TITLE
Make Chromecast button available on Library screens

### ISSUE THREAD

**Issue by Nairou** [daneren2005/Subsonic#553]
Currently the Chromecast button is only visible on the Now Playing screen, which means you need to start playing music before you can connect to Chromecast. It would be nice if we could connect to the Chromecast device **before** playing a track, so that we don't then have to pause or restart it. As with other apps (like Google Music), just connect to Chromecast first, then browse and select music, knowing that anything you play from that point on will play on the Chromecast.

**Comment by daneren2005** [comment]
There is just no more room for yet more buttons so I'm not adding it.
