### ISSUE TITLE
Add Lollipop "heads up" notification support

### ISSUE THREAD

**Issue by Nairou** [daneren2005/Subsonic#554]
In KitKat, you could see the status text for notifications. So each time a new song started playing, you would briefly see the title. Now, with Lollipop, that is no longer an option. If I want to see what new song is playing, I have to pull down the notification tray. It would be nice if DSub had the option of using the new popup notifications in Lollipop, to briefly announce each song on the screen as it used to.

**Comment by daneren2005** [comment]
I can add it as an option
