### ISSUE TITLE
Repeat all not working

### ISSUE THREAD

**Issue by Akegata** [daneren2005/Subsonic#556]
The repeat all option doesn't work in the latest version of DSub.
If only one song is on the playlist, it gets repeated, but if there are several songs, repeat all simply does not repeat the playlist.

**Comment by mavenius** [comment]
I just tested, and it works for a 20-track playlist for me.

Thank you,

Mark Avenius
Mark@Aveni.us

**Comment by Akegata** [comment]
So how would I go about troubleshooting this? This hasn't worked for quite some time for me.

**Comment by mavenius** [comment]
Which device(s) are you using? Are you playing on the device or casting?
Does it work when you play directly on the device? That's what I tested.
Which version of DSub?

Thank you,

Mark Avenius
Mark@Aveni.us

**Comment by daneren2005** [comment]
I've never seen it not work.  I would try reinstalling if it has been a problem for a long time.

**Comment by daneren2005** [comment]
If reinstalling does not work, let me know

**Comment by Akegata** [comment]
Not sure if I'm doing something wrong here, but anyway, I just reinstalled DSub and the behaviour persists. I'm using the latest version available on the play store.

I'm playing the music on my Samsung Galaxy S4.
I choose a full album to play. When a song has played, it is removed from the created playlist.

**Comment by mavenius** [comment]
In the upper-right corner when you're viewing your playlist, click the
hamburger button (three dots) and uncheck Remove Played Songs.

Thank you,

Mark Avenius
Mark@Aveni.us

**Comment by Akegata** [comment]
Yup, that was the problem, thank you!
This combination of features is kind of confusing. Maybe repeat shouldn't be possible to activate while the remove played songs feature is enabled?
