### ISSUE TITLE
Search Button hidden by new pull out Drawer

### ISSUE THREAD

**Issue by keckelt** [daneren2005/Subsonic#557]
Hi,
since I updated to the new 5.0.x versions, I miss the ability to search the database from artist/album view:
When you pull out the drawer, the top bar changes and displays a search button. But with the new pull out drawer, this top bar is like in the background and  I can no longer click that btutton.

Best,
keckelt

**Comment by mavenius** [comment]
Have you tried going to Library view? It works fine for me there. If you
are on the Home view (in Recently Added, e.g.) it changes to the play
button, but it works for me on Library out in the root of home.

However, I do have a big device, so maybe it's a screen space thing.

Thank you,

Mark Avenius
Mark@Aveni.us

**Comment by keckelt** [comment]
Sure, it works fine in Home and Library. I'm just used to be able to search
from every screen with the 'pull out drawer'-method and kinda miss it now :)


Klaus Eckelt
Brigittaplatz 23/7
1200 Wien
Klaus.Eckelt@gmail.com

2015-09-30 14:00 GMT+02:00 Mark Avenius <notifications@github.com>:

> Have you tried going to Library view? It works fine for me there. If you
> are on the Home view (in Recently Added, e.g.) it changes to the play
> button, but it works for me on Library out in the root of home.
>
> However, I do have a big device, so maybe it's a screen space thing.
>
> Thank you,
>
> Mark Avenius
> Mark@Aveni.us

**Comment by daneren2005** [comment]
That is part of the Android design guidelines so I am not going to change it.
