### ISSUE TITLE
Can no longer star entire artists

### ISSUE THREAD

**Issue by zoompig** [daneren2005/Subsonic#561]
First time posting a bug ... pardon the etiquette.  Haven't seen this posted alsewhere.
Can't seem to star an artist in 5.0.3.  Can only star individual albums.
Running CM 12.1.  Will gladly provide more info.

**Comment by daneren2005** [comment]
I noticed that it was broken a bit ago and already fixed it in https://github.com/daneren2005/Subsonic/commit/618bc94fa81983b6462c8b771763599e9584ac1f
