### ISSUE TITLE
Previous button inaccessible on lockscreen on Nexus 5

### ISSUE THREAD

**Issue by retropc** [daneren2005/Subsonic#570]
Hi,

On the Nexus 5 the previous button isn't accessible on the lock screen notification:

![screenshot_20151014-103905](https://cloud.githubusercontent.com/assets/3223769/10480113/535df2f2-7260-11e5-8e4f-8f4bb002d432.png)

I can attempt to drag down to get the other controls, but if I do that the unlock prompt immediately appears.

I realise there's limited space, but it's a really handy function.
Maybe an option to swap out the album art on the notification (given it's on the background) for a "previous button"?

Thanks

**Comment by daneren2005** [comment]
There is really only room for 3 buttons and I am not going to radically change the notification widget.  If you want a previous button turn off the option Persistent Notification
