### ISSUE TITLE
Auto Offline option

### ISSUE THREAD

**Issue by 876974** [daneren2005/Subsonic#571]
Most have problems with a stable internet connection on my phone. On this , I would like to have the opportunity to select the optional , automatic disconnection from the server SubSonic if this was specified in the Annex , and has not been turned off earlier.
Also , besides the above-proposed option , propose to make an optional choice, the number of attempts to establish connection with the server when connection is lost with him , having exhausted the number of which , the server will automatically disconnect .

**Comment by daneren2005** [comment]
Duplicate:  #461
