### ISSUE TITLE
Sidebar selected drawer styling

### ISSUE THREAD

**Issue by soupman2001** [daneren2005/Subsonic#579]
Should the selected drawer be both colored text and a different background?
I think it would look much better to have just one of those, preferably just the different background.

![screenshot_2015-10-20-14-20-59](https://cloud.githubusercontent.com/assets/13251721/10606903/3d825e70-7736-11e5-9e1e-9656b76c2def.png)

**Comment by daneren2005** [comment]
That styling is done by Google's NavigationView component so I assume that is how they think it should be.
