### ISSUE TITLE
Pausing turns off the now playing notifcation 

### ISSUE THREAD

**Issue by soupman2001** [daneren2005/Subsonic#581]
Having the notification stay visible for a few minutes when playback is paused through it would make more sense, most music players I've used seem to agree.

**Comment by keckelt** [comment]
Yeah. I sometimes pause from lock screen for a few seconds and need to
unlock to resume.
Am 20.10.2015 2:47 nachm. schrieb "hollander" <notifications@github.com>:

**Comment by soupman2001** [comment]
Either I missed it or it was added in 5.0.4 but there's an option in the Playback settings to have a persistent notification. I was using 5.0.3 from F-Droid without realising it was outdated.
