### ISSUE TITLE
Action bar changes when pulling out sidebar

### ISSUE THREAD

**Issue by soupman2001** [daneren2005/Subsonic#585]
https://youtu.be/0khUeccIlhM

The shuffle button disappears and the menu button transforms into what I assume is a back button, but it's not visible because the sidebar blocks it. In drawers that aren't "Home" drawer title changes to "DSub" when the sidebar is visible, you can see it change back when you close the sidebar. Seems unnecessary and it doesn't happen in my other apps that have material design.

**Comment by soupman2001** [comment]
I see now that

**Comment by keckelt** [comment]
Kinda mentioned that in #557 too.
Am 20.10.2015 3:51 nachm. schrieb "hollander" <notifications@github.com>:
