### ISSUE TITLE
Temporary loss of focus set to always lower volume still gets playback paused

### ISSUE THREAD

**Issue by soupman2001** [daneren2005/Subsonic#594]
Tested by opening a video file with MX Player. 
Playing something on Kodi using Yatse has also recently started pausing my DSub playback, I don't know whether DSub or Yatse is responsible. The YouTube app and youtube.com in chrome also pause DSub.

I disabled the "Play alone" feature in MX Player to make DSub continue playing.

Using the latest version from the Play Store.

**Comment by daneren2005** [comment]
It is only supposed to lower volume when being signaled for temporary loss of focus. Another app starting to play its own music or video is not temporary and should not be treated as such.
