### ISSUE TITLE
Unrecognized OPUS files

### ISSUE THREAD

**Issue by Xarin** [daneren2005/Subsonic#598]
Hi, I tried the forums but didn't seem to get very far. Subsonic currently is not picking up any .opus files. I'm sure the permissions are correct as its seeing everything else in the folder, and I tried a chmod 777. I have tried adding opus to the mp3 transcoder as well. all other file types I have tried are working and all codecs seem to be installed as mplayer will play the files fine. Is there something I'm missing, is this a bug? From what I understand subsonic does have opus support, any help would be appreciated.
Thanks.

**Comment by popeen** [comment]
I think you probably meant to post this over at Subsonic. This repo is for DSub, a Subsonic app.
You can find Subsonic here.
http://sourceforge.net/projects/subsonic/

That being said Daneren does have a Subsonic repo as well so maybe he can help you anyway, just thought you might want to know this isn't the official one.

**Comment by Xarin** [comment]
Ahh, thanks for your help!

**Comment by izderadicka** [comment]
For me opus files are working with Subsonic (5.3-KANG) and the original subsonic Android client -   for android they need to be transcoded to mkv container (Android supports them only in in MKV).  Also in subsonic you need to add opus extension to audio extensions - Settings /General/Music Files.

However opus audio does not seem to work in this DSub Android client.
