### ISSUE TITLE
Subsonic Account is resetted when entering DSub

### ISSUE THREAD

**Issue by Row** [daneren2005/Subsonic#600]
Samsung S6 with Android – Marshmallow, server MusicCabinet.

1. Open "Android Settings" -> Accounts -> DSub
2. Turn off Sync Playlist. 
3. Open DSub
4. Repeat 1.
5. Notice that the "Sync of playlist" is enabled again.

**Comment by daneren2005** [comment]
That is by design.  If you want to control it do it via the in-app settings.
