### ISSUE TITLE
Using bluetooth "skip" buttons to fast forward in podcasts broken

### ISSUE THREAD

**Issue by Uddasa** [daneren2005/Subsonic#602]
When playing a podcast: the bluetooth/remote buttons "next/previous" are now skipping to the next item of the playlist instead of skipping through the podcast like before.

If I remember correctly, in podcasts, these buttons were used to skip forward/backward (30 sec. I think) in one of the previous versions. I don't remember which one because I've been using Player FM a lot and switched back to DSub only recently to see the improvements.

**Comment by daneren2005** [comment]
It only behaves that way if there is only a single song in the playlist

**Comment by Uddasa** [comment]
Hi again,

There is some update on this issue (which was not an issue at first, just a misunderstood from me) :
I can't fast forward through podcasts anymore **with Bluetooth buttons only.**

Let me explain:
I can fast forward using the "skip" button on the screen, but with my Bluetooth remote only play/pause button is working.
On the other hand, if I'm playing music I can use the Bluetooth buttons to change track.

I know that it was working before, and yes I only have 1 podcast in my playlist.

Maybe it has something to do with Android because I think it started when I updated to a 6.0.1 ROM.

Do you need something from me (logcat)?

Regards,
Uddasa.
