### ISSUE TITLE
Hide media not working 

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#605]
Hi there The hide media from other apps option is not working correctly.  . It hides it sometime but for unknown response i star seening songs from  madsonic

**Comment by daneren2005** [comment]
It adds a .nomedia and it is up to other apps to respect it.

**Comment by addisflava** [comment]
Hi daneren 
The hide media option is disabled by default .  so users have to manually enable it after installation , I forked your project and have been trying to change this behaviour by changing the default value in settings.xml with no luck . I am using the app to share copyrighted material and its very important that users should not find this files easily on the device . Since you are very familiar with the code Could you please help me change this options and make the app at list save media files in a hidden directory(directory that starts with . ) or if possible encrypt the media  and also remove the option to specify a new directory (if possible only allow them to specify internal and external storage ) , please please help.

**Comment by addisflava** [comment]
it doesn't even create .nomedia file/folder in the music directory . it does create .nomedia folder in aviator & albumart directory but not in the music directory after choosing hide from others in settings.
