### ISSUE TITLE
Album not shown in Recently Added after tag change

### ISSUE THREAD

**Issue by agn4965** [daneren2005/Subsonic#610]
1) add album to library and it's listed in Recently Added on DSub
2) Change album tag in Subsonic
3) DSub continues to list the album with the old tag

Opening the album just shows "No data"
I had to scan media folders again to resolve this issue.

**Comment by daneren2005** [comment]
If scanning on the server fixes it then it has nothing to do with DSub. DSub only knows what the server tells it.
