### ISSUE TITLE
Jumps back to Now Playing screen after screen rotation

### ISSUE THREAD

**Issue by bengadbois** [daneren2005/Subsonic#615]
Browsing Recently added, a playlist, Library, or any of the other menus and rotate the screen.

Now I'm immediately on Now Playing, instead of on the screen-rotated-version of wherever I was. By pressing back I can get to wherever I was, but that's an extra step.

It's a debatable UX thing, but thought I'd bring it up if this wasn't a deliberate decision.

**Comment by daneren2005** [comment]
It's not a deliberate design decision and I am unable to reproduce.  Does this happen on multiple devices?  Or if you only own one which device/Android version are you seeing this on?

**Comment by daneren2005** [comment]
Nevermind, I think I figured out how to reproduce. It only happens if you enter DSub by pressing on the notification (or probably also the widget) correct?

**Comment by bengadbois** [comment]
Correct, after opening via the widget
