### ISSUE TITLE
Artist radio: add to playlist when end reached

### ISSUE THREAD

**Issue by mavenius** [daneren2005/Subsonic#620]
It would be nice if >20 tracks would play when using artist radio. More could be fetched when getting close to the end of the playlist (within 3?)

**Comment by daneren2005** [comment]
That is exactly what it does already...do you have any more details on a way to reproduce it not working like that?  Note that if you manually add stuff to the current playing list or toggle online/offline it will turn off.

**Comment by mavenius** [comment]
Sorry about that... It must have come to another version of the same song,
and I saw that the playlist was still only 20 long, so I assumed it had
repeated.

Is there any indicator that it is in radio mode?

Thank you,

Mark Avenius
Mark@Aveni.us

**Comment by daneren2005** [comment]
No there is no indication it is in radio mode
