### ISSUE TITLE
Song with % in title won't play

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#622]
I have a track, 100% by Sonic Youth, and it will not play in DSub.  However, I can play it just fine over Ampache web interface.  At first I thought there might be a problem passing the filename to the transcoder when playing over the mobile app (versus over the web interface) so I changed the filename from 100%.mp3 to 100.mp3.  It still would not play in DSub.

So, finally I tried using the "edit" option for the track on the Ampache web interface and changed the displayed title to 100.  Interestingly, it does not change the actual ID3 tag of the file, just the displayed title on the web page.  After I did that, the track played in DSub.

**Comment by daneren2005** [comment]
I tried changing a title to 100% in Subsonic and it works fine.  Probably is something specific with Ampache.  Can you email me a temp username/password and put let me know which file to try?

**Comment by dhsc19** [comment]
Server:  https://cloud.carlovirtucio.com/ampache
User: subsonic
Pass: daneren2005pass

Artist: Sonic Youth
Album: Dirty - Deluxe Edition (Disc 1
<https://cloud.carlovirtucio.com/ampache/albums.php?action=show&album=2806>

The track "100%" is in two places.  It is also found in "Hits are for
Squares".  And it appears that when I edit the track title in one album, it
is also changing in the other album.  I don't know if that is any clue.
RIght now I have it so that it appears as 100% and it will not play.  I can
change it to 100 if you need me to.

Thanks.

- Carlo


www.carlovirtucio.com

**Comment by daneren2005** [comment]
Yeah it does appear to be a problem on your end.  It is reporting that file as "Content Type: text/html; charset=iso-8859-1".  Opening it up in a browser it does not appear to be a valid download stream: https://cloud.carlovirtucio.com/ampache/rest/stream.view?v=1.2.0&c=DSub&id=300029686&maxBitRate=256&u=subsonic&p=daneren2005pass

**Comment by dhsc19** [comment]
Thank you for checking.

www.carlovirtucio.com

**Comment by daneren2005** [comment]
When you figure out what the solution was you should still post it here though for others to reference

**Comment by dhsc19** [comment]
Ampache dev was able to verify that the problem is with Ampache.  The title
contains a character that conflicts with a URL rewrite rule.

www.carlovirtucio.com
