### ISSUE TITLE
Request: option to remove a single track from the "Now Playing" list

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#623]
I can see the "remove all" option for the "Now Playing" screen, but it would also be nice to have a remove a selected track from the list.  Sometimes, I've added individually selected tracks for the Now Playing list that I want to save as a playlist, but some songs I change my mind and want to remove.  But I have no way of doing that.

**Comment by daneren2005** [comment]
Swipe to remove

**Comment by dhsc19** [comment]
LOL!  You're right.  I just figured it out and was about to remove it
myself.  Thanks!

www.carlovirtucio.com
