### ISSUE TITLE
Madsonic: Song Lists

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#624]
Hi 
could we please have support for rest2  getMostplayedSongs or getTopplayedSongs , it would make it much easier to access songs that are most listened to instead of browsing through different albums . I personally  have never used mostplayedalbums i rather listen to various collection of songs . could you please add this option . thanks

**Comment by T7000** [comment]
I am missing this too

**Comment by daneren2005** [comment]
For Madsonic 6+ add a 'Song Lists' section below 'Album Lists' for:

http://beta.madsonic.org/pages/api.jsp#getNewaddedSongs
http://beta.madsonic.org/pages/api.jsp#getLastplayedSongs
http://beta.madsonic.org/pages/api.jsp#getMostplayedSongs
http://beta.madsonic.org/pages/api.jsp#getTopplayedSongs

**Comment by addisflava** [comment]
Could you please add top rated songs option also . The last fix on issue #621 did not realy solve the problem and doesnt play top rated songs , i have left a comment on the ticket

**Comment by daneren2005** [comment]
I don't see an option for getTopRatedSongs so I can't really add it.
