### ISSUE TITLE
"search more on madsonic" message on artist bio 

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#629]
HI 
when connected to madsonic , when you select an artist it tries to load therer bio from (last fm i think ) but when it unable to find it shows "search more on madsonic" message , which always doest do nothing when you click on it but sometime get stack and crash . could you please remove this message if its unable to find artist bio . 
Thanks alot 
![screenshot_2016-01-23-22-29-27](https://cloud.githubusercontent.com/assets/13881665/12541839/ca61ec08-c2e9-11e5-8054-73ee5ef54a26.png)

**Comment by daneren2005** [comment]
If Madsonic has no bio info to display it needs to return no bio information. That is a server issue and I am not going to change anything for that.
