### ISSUE TITLE
Add an option to scrobble on offline mode

### ISSUE THREAD

**Issue by ttsda** [daneren2005/Subsonic#630]
Scrobbling uses little data, so it would be great if I could enable the last.fm scobbling functionality while using the app on offline mode

**Comment by daneren2005** [comment]
Is there any particular reason for this?  There is already an option under Settings -> Cache/Network > Wi-Fi streaming only so if you want all of the features from online mode but don't want to be downloading anything.

**Comment by ttsda** [comment]
The reason is I have a very big music library on my server,  and only a small subset of it is cached in dsub, so for it to be usable when I'm not using Wi-Fi I need to turn offline mode on to hide all the albums that are not cached.

**Comment by luckydonald** [comment]
Thats what I meant in #603

**Comment by daneren2005** [comment]
Yeah I think #603 is a much better solution to the issue
