### ISSUE TITLE
Song menus in playlist are too close to scrollbar.

### ISSUE THREAD

**Issue by craftyguy** [daneren2005/Subsonic#631]
When viewing the playlist, the song menus are too close to the scroll bar, making it incredibly easy to accidentally tap the scroll bar and "jump" your current view of the playlist elsewhere when trying to open a menu for a song.

See issue #628 for a screenshot.

**Comment by daneren2005** [comment]
To be honest this won't be perfect but I am not going to increase it anymore since it starts taking too much of the screen for the scrollbar.

**Comment by craftyguy** [comment]
Ah.. How about implementing the menu a different way, such as activating it when the user long-presses on an item in the list?

**Comment by daneren2005** [comment]
Long press already does something else

**Comment by craftyguy** [comment]
I know you hated my original suggested fix for this issue of relocating the menus to the left side, but could you at least make it user configurable (defaulting to how it is today)?
