### ISSUE TITLE
Question: what is the min API version DSub requires?

### ISSUE THREAD

**Issue by srinathh** [daneren2005/Subsonic#632]
If DSub is used to connect to other open source servers implementing a subset of subsonic API, what is the minimum API version DSub expects for smooth functioning? (eg. for browsing and playing by file structure)

**Comment by daneren2005** [comment]
I would probably say 4.8 for basics but I have implemented stuff from basically every version at this point so there is no minimum version.

**Comment by srinathh** [comment]
Thanks!

**Comment by luckydonald** [comment]
Btw works fine on ampache :+1:
