### ISSUE TITLE
Improve offline searching

### ISSUE THREAD

**Issue by fxthomas** [daneren2005/Subsonic#636]
As far as I can tell, the search function is very inefficient in offline mode, requiring the user to exactly type the song title word for word. It is especially useless for languages with complex glyphs (e.g. Chinese or Japanese), since they seldom use spaces.

It would be great if we could improve this, e.g. by using a better distance metric than the number of matching words. Has anything been tried regarding this before?

**Comment by daneren2005** [comment]
Yeah I already did some optimizations to online results with DSubSearchProvider and Util.getStringDistance.  I just need to apply similar optimizations to the offline search as well.

**Comment by fxthomas** [comment]
Awesome! Do you mind if I give it a try?

**Comment by daneren2005** [comment]
Sure go ahead
