### ISSUE TITLE
Turn notification dark when the theme is set to dark or black

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#639]

**Comment by daneren2005** [comment]
No.  There is an option to not color the action bar and status bar.  I am not going to break it out to separate pieces.

**Comment by T7000** [comment]
I'm talking about the notification, not the action bar and status bar.
http://i.imgur.com/x07xueb.jpg

**Comment by daneren2005** [comment]
Oh then definitely not. That is not supposed to change and is part of the system
