### ISSUE TITLE
Starred items are not reflecting "starred" status

### ISSUE THREAD

**Issue by dhsc19** [daneren2005/Subsonic#660]
When I star (big star) items in DSub, initially I will see the big star highlighted and I can see that it is being marked as "favorite" (with a heart) in Ampache.  However, when I refresh the view in DSub, the star becomes un-highlighted, but Ampache will still show that it is actually still marked as favorite.  Interestingly, in the Home -> Starred album list, all my starred items show up in there, but none of them show a highlighted star.  If I want to remove the star/favorite, I have to re-star and un-star.

**Comment by daneren2005** [comment]
That is an Ampache issue since it works against Subsonic just fine.

**Comment by Afterster** [comment]
Fixed with https://github.com/ampache/ampache/commit/558e2c882a0e9ce21be240032264fc44e592ff24.

**Comment by daneren2005** [comment]
Sweet that was fast!
