### ISSUE TITLE
Tracks bookmarked without my say-so

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#661]
What makes DSub bookmark tracks automagically?

**Comment by daneren2005** [comment]
Bookmarks are created if pausing in middle of podcasts or audio books

**Comment by T7000** [comment]
But I'm not listening to podcasts or audio books. So it's because the tracks are longer in length?

**Comment by daneren2005** [comment]
I had forgotten that it also auto bookmarks for anything over 10 minutes long
