### ISSUE TITLE
Hide media not working nomedia not created 

### ISSUE THREAD

**Issue by addisflava** [daneren2005/Subsonic#662]
I reported this issue a while back but you did not address the issue ,Hide media not working #605
[https://github.com/daneren2005/Subsonic/issues/605](url) 
currently There is no .nomedia file/directory being created in music folder when toggling hidemedia on.(yes i have unhidden all files but its not there, but i can create it manualy)
even in the avatar & artworks directory  its creating .nomedia directory  not file , which will be ignored by some apps , it should use file not directory

**Comment by daneren2005** [comment]
I don't know what to tell you.  It appears to create the file for me and it's not like the logic is that complicated.  Either it can create it or it can't.

**Comment by addisflava** [comment]
I have fixed the issue . The problem is in your its using ensureDirectoryExistsAndIsReadWritable method to create the .nomedia file in the artwork-directory

**Comment by daneren2005** [comment]
I was talking about you saying no .nomedia file is created in the music folder...
