### ISSUE TITLE
Browse By Tags: Show Artist Missing

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#664]
Gone from Recently Added, Recently Played, Random, Most Played, etc.

**Comment by daneren2005** [comment]
...just checked and they appear for me.  In fact, what do you mean gone?  They were never there before this latest update.

**Comment by T7000** [comment]
Could have sworn I was always able to go from an album on places like the the Recently Played list to the artist through the contextual menu by using the Show Artist option.

**Comment by daneren2005** [comment]
I am pretty sure it wasn't there before.  But either way you are saying you aren't seeing it as an option for DSub 5.1.6?  What server are you using since I have only tested it on Subsonic 6.0 Beta.

**Comment by T7000** [comment]
Yes I'm not seeing it as an option, I'm using 5.1.6.

**Comment by daneren2005** [comment]
Mind emailing me a temp username/password to DSub.android@gmail.com so I can try it and see what is going on?

**Comment by T7000** [comment]
Sorry I don't feel comfortable doing that.

**Comment by daneren2005** [comment]
Appears to not show when Browse By Tags is on.  That is why I didn't catch it I never use that option.
