### ISSUE TITLE
Cannot play music from ampache server

### ISSUE THREAD

**Issue by Larnal** [daneren2005/Subsonic#671]
I am running an ampache server with Subsonic back end. Everything worked fine and suddenly I cannot play nor download in cache any music. When I click on play a music, it stays at 0 B. 

Dsub works well with the demo server and the app Subsonic Music Streamer works well with my ampache server (playing and caching music). 

I run my ampache server with https protocole, so I tested the proxy settings but it didn't help. 

Can you help me solve this issue ? 
Thank you very much.

**Comment by daneren2005** [comment]
I really have no idea how Ampache sets everything up.  The most I can do is help you get a stream url and you will have to figure out why Ampache isn't providing a valid stream from it.  After trying to download something go to Home -> Send Logs.  You don't actually need to email the logs.  Click on the pastebin log and look for a line of the form: `http://domain.com/rest/stream.view?v=1.2.0&c=DSub&id=49244`.  DSub strips the username/password so you will need to add `&u=<username>&p=<password>` to the end of the url to get it to work.
