### ISSUE TITLE
audio won't play for some movie files

### ISSUE THREAD

**Issue by dln949** [daneren2005/Subsonic#675]
On my android device, using DSub, on SOME movie files (mp4), no audio plays.  Using the same android device, but using an alternative app - e.g., Emby - if I play the EXACT same movie file, the audio works just fine.  (Curiously I have the exact same problem with Subsonic's android app, on the exact same file.)  

DSub 5.1.6
Android 6.0.1
Subsonic 5.3

**Comment by daneren2005** [comment]
DSub is just passing a stream url for the Subsonic server to a 3d party video player.  I can't control Subsonic not outputting valid video or another player not being able to play it properly.
