### ISSUE TITLE
White border around all Widgets (Google Now Launcher)

### ISSUE THREAD

**Issue by z-vap** [daneren2005/Subsonic#677]
Not sure how this happened.  But for some reason I always have a white border around my DSub widgets.  I uninstalled and reinstalled but everything remains the same.  I even tried stopping the program in Settings, clearing the data and cache, uninstalling, then reinstalling.  Strange enough this does not wipe my Server settings.  Its like I never even did anything.    This is on a Moto X 2014 edition

**Comment by daneren2005** [comment]
I don't know what to tell you.  There is no white border in the layout definition and I have about 6 devices on various versions of Android that all don't have a white border.

**Comment by keckelt** [comment]
Do you use a laucher (e.g. Nova, Go, etc. ) other than the default one?

**Comment by z-vap** [comment]
Nope.  stock phone, running Marshmallow.   I just wonder why the uninstall doesn't remove everything. For example, I don't need to re-enter the server info.  If that's true then maybe whatever makes the Widgets is still hanging around after the uninstall also.

**Comment by daneren2005** [comment]
Looks like you aren't alone.  Someone else just reported the same issue on the forums: https://github.com/daneren2005/Subsonic/issues/677.  Is it only happening with the 4x3 widget like they appear to be using in that screenshot?  You say uninstalling doesn't remove the widget.  Have you tried manually removing the widget and putting it back on again?

**Comment by z-vap** [comment]
i just checked mine.  For me its occurring for all 4 widgets.

**Comment by daneren2005** [comment]
I am able to reproduce now that I installed all of the updates for my Nexus 5.  I don't see an obvious reason for this to be broken so I am asking on stackoverflow: http://stackoverflow.com/questions/36629189/google-now-launcher-white-border-on-widgets

**Comment by grumpwagon** [comment]
(I'm the person who reported this on the forum)

It was occurring for me on all sizes of the dsub widget. I was trying to say that it didn't happen for any other app's widget.

I'm curious z-vap if you saw something I saw before. Previous to this most recent Google Now Launcher update (where I started noticing the white outline), I would sometimes get a white bar across all homescreens in the position where I had the 4x1 widget, even the homescreens where the widget wasn't located.

So, I'd have the dsub widget across the top row on one homescreen, but if I swiped to the next home screen, there would be a semi-transparent white bar in the background of that screen. It didn't block other icons or widgets from being positioned there, it just looked like part of the background. That stopped happening when the white border started appearing.

**Comment by z-vap** [comment]
@grumpwagon yes I too had that occurring for me.  What type of phone do you have?

**Comment by grumpwagon** [comment]
LG G2, Android 5.0.2

**Comment by wildwoodashes** [comment]
I can't really add anything other than to say I've seen both of these issues with a Nexus 6P running 6.0.1 and using the stock Google Now Launcher. The grey background bar could be cleared by enabling homescreen rotation, but the white border seems permanent. 

![widget](https://cloud.githubusercontent.com/assets/18541180/14623053/8146379a-0583-11e6-8134-7b476a83ace0.png)

**Comment by NiknakSi** [comment]
I also have this issue. I've been using a Nexus 4 on Android 5.1.1 and it had the white outline issue (although only for the last few weeks), and I've just bought a new HTC 10 and installed DSub and have the same issue with all of the widgets.

Any ideas for a potential fix?

**Comment by daneren2005** [comment]
Someone on the forums mentioned this was fixed for them. Can anyone else comment on whether or not they are still having this issue?

**Comment by NiknakSi** [comment]
For me the issue has disappeared which is great. I only just realised after your comment though. My HTC 10 had a firmware update today so maybe that's related, but probably more likely is an update to the launcher at some point. But... I'm fairly sure I still had the white outline yesterday before the firmware update!

Who knows. Either way, it's all good on my HTC 10 running latest stock firmware with the Now launcher.

**Comment by jagerman** [comment]
Was not fixed for me this morning, but there was a "Google" app update available.  I installed it and the border is now gone.
