### ISSUE TITLE
Export Permanent Cache

### ISSUE THREAD

**Issue by dembeck** [daneren2005/Subsonic#679]
It would be helpful if there was a way to export/import a list of your permanent cached items. This would be helpful for a few reasons:

1. When switching to a new phone, you could just import your list and have it sync up
2. Allow you to delete what is currently cached, in order to re-sync everything. This would be for cases where multiple items skip or end early, due to downloading over poor quality cell service.

Bonus points for haveing it be in a human readable format. That would allow you to go through the list, and remove items you do not want to be resynced.

**Comment by daneren2005** [comment]
I have no intention in adding any sort of manual sync like this
