### ISSUE TITLE
Unnecessary heads up notification

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#680]
Happens when DSub gets paused (manually or by loss of focus), and when the app is exited from the menu.
I also don't think it's necessary to give a heads up when you're already in the app, like when you select a track to play or hit the next/previous buttons.

**Comment by daneren2005** [comment]
I am not sure I understand what you are talking about. On both my Nexus 5 and my Galaxy S6 it doesn't do heads up notifications and I don't specify to do heads up notifications. On the next version I added an option to do heads up notifications but it required special code to trigger them, which is not in any previous versions.
