### ISSUE TITLE
Search bar & results styling critique 

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#690]
The bar looks like it's too thin.
It has an out of place green border, and the less visible greyish border reminds me of KitKat.
When entering something, the X button that appears isn't in the same spot as the microphone it replaces.
The instant results icons are white on the light theme (need more contrast.)
The instant results overlap with the bar.
The DSub icon is a bit gaudy and unnecessary.
http://i.imgur.com/gKzktTy.png

Here's some inspiration:

- Gmail's search bar
http://i.imgur.com/UfmsOYm.jpg
- eBay's (I quite like the homepage header searchbar integration this app has)
http://i.imgur.com/y3aVzaW.jpg
- F-Droid's
http://i.imgur.com/yOGmznQ.jpg
- Google Maps'
http://i.imgur.com/X14v2eP.jpg
- Google Calendar's
http://i.imgur.com/2p2VIek.jpg
- Play Store's (very nice sidebar/back button combination & animation)
http://i.imgur.com/zVprNCA.jpg

**Comment by daneren2005** [comment]
Honestly I still am just using the default system search method from the Gingerbread days.  It looks like Google stopped updating it's theme a while back, so I will need to figure out what other apps do to achieve that look and switch.

**Comment by T7000** [comment]
This looks like it would have a straightforward implementation: https://github.com/zeapo/Android-Password-Store
