### ISSUE TITLE
Adding support for Simple Last.fm Scrobbler

### ISSUE THREAD

**Issue by HazWard** [daneren2005/Subsonic#692]
Is it possible to add support for [Simple Last.fm Scrobbler](https://play.google.com/store/apps/details?id=com.adam.aslfms)? I understand that Subsonic (and Madsonic) offer scrobbling but when listening to cached tracks in offline mode none of my scrobbles are sent.

**Comment by T7000** [comment]
They're synced and scrobbled when you go back to online mode, at least that's what supposed to happen and what happens on my setup.

**Comment by HazWard** [comment]
If I go to online mode and the server is unavailable what happens to the scrobbles?

**Comment by daneren2005** [comment]
Not sure why I didn't see this earlier.  Right now if the server is unavailable it loses the scrobbles.  It is on the TODO list to keep them and retry them again later.  I am not adding support for a third party scrobbler.  The regular Last.FM app just listens to the standard media player intents DSub sends out, so you can always use that and just turn off the option to use the server scrobbling in DSub's settings.
