### ISSUE TITLE
No audio playback on Android N Dev Preview 3

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#696]
I know this is probably something the Android devs have to fix but I'm praying there's a quick hack that would let DSub play back audio on the preview.

**Comment by Adthrawn** [comment]
Looks like it's a known issue, from the release notes. 

Audio
A platform audio player issue prevents some apps from functioning normally. For example, Skype and other apps are affected by this issue.


So looks like it would require some work to change how it's done since other apps work.

**Comment by daneren2005** [comment]
Judging by how they phrased that, I assume they admit it is a problem on their end and will be fixing it. I don't really intend on spending any time looking into this but I will leave it open so we can track whether it gets fixed in the next release.

**Comment by T7000** [comment]
After trying Google Play Music for a few days I love DSub even more.

**Comment by daneren2005** [comment]
Some people are reporting that wiping all data for the app has fixed it for them.  It may just be as simple as something being botched in the upgrade.  G+ Post: https://plus.google.com/u/0/115158133651819109867/posts/ZgM4kjCnpWu

**Comment by FoxBJK** [comment]
I made that G+ post, and can confirm that fix worked. Adding myself to this so that I'm reminded to re-test this as N betas are released.

**Comment by daneren2005** [comment]
Can people let me know fi this is still an issue after upgrading to http://www.androidpolice.com/2016/06/15/android-n-developer-preview-4-is-out-build-npd56n/

**Comment by FoxBJK** [comment]
I installed the update last night. Have been able to play files that were cached before the update without any problem (including over Android Auto)

**Comment by Mycah** [comment]
I just signed up for the Android N beta, and I have a weird as hell issue after clearing data.

If I play it in my car (over bluetooth), it'll play the first few seconds of a song, then the 2nd song in whatever playlist I'm listening to will start overtop of the song I'm currently listening to.  If I hit pause, it'll pause the first song, but the 2nd song will continue playing.

If I close the app, the 2nd song will keep playing until I hit the square button and swipe dsub off.  Then it'll stop.

**Comment by daneren2005** [comment]
That appears to be a new problem which only shows up on the N preview I need to take a look at

**Comment by garyo** [comment]
I was having the "no playback in N" issue. I wiped all Dsub data and reinstalled, and now am having this issue; two songs playing at once and no way to stop them without force quit. This happens even with regular (non-bluetooth) playback.
