### ISSUE TITLE
Fdroid build failling

### ISSUE THREAD

**Issue by jooola** [daneren2005/Subsonic#698]
And here i am again but with a better explanations and more info about my issue !

So the Fdroid Repo is building all they're app on they're own from the source code and the last build that passed is the 5.0.3.
[https://f-droid.org/wiki/page/github.daneren2005.dsub#5.1.1](url)

So the problem comes from the build metadata ( if i understand it right ? )
"Reason: patch does not apply "

So is they're a way to build this app easier ? ( Think the build process is a bit to difficult for the fdroid build server i guess )
Any way to patch the build metadata file ? ( i'm absolutely not a pro in this domain ... )

I saw that we may need to commit some changes to in the fdroid gitlab to reenable the build process .

[https://gitlab.com/fdroid/fdroiddata/commit/43db39dd26b7725807c9ad4921ace4a3a5dc8f57](url)
Best regards

**Comment by daneren2005** [comment]
If they can't build it that is their deal. I have no intention of babysitting every random service's build process.
