### ISSUE TITLE
Keep podcast files after listening to them

### ISSUE THREAD

**Issue by zeroepoch** [daneren2005/Subsonic#701]
I noticed in the options there is a way to tell D-Sub to keep the last X number of played music tracks, but that doesn't seem to work for podcasts.  The reason this becomes a problem is if I switch between podcasts and audiobooks it removes the cached podcast file when I switch to the audiobook.  This means I need to redownload the podcast when I come back to it.  This seems like wasted bandwidth (usually mobile) and would be nice to avoid.

My request is either to carry over the keep last X option to podcasts or add an option to not remove podcasts that are cached unless the user does it manually.  Any other ideas you may have that avoid this redownloading would be cool.

**Comment by daneren2005** [comment]
Podcasts only get deleted when you are within the last few minutes of the end. What exactly are you seeing?

**Comment by zeroepoch** [comment]
That's probably what's happening, but I was hoping to have an option or way to not delete the files as soon as they finish.  In case I want to go back and check something I heard in the podcast.  I know there is no way to "uncache" a given file, which is fine.  I'm perfectly happy clearing the cache from time to time myself.  I don't know if this is too specific of a request to support?

**Comment by daneren2005** [comment]
I don't really intend on adding this to be honest.

**Comment by zeroepoch** [comment]
Fair enough.  It's a minor inconvenience that's easy to work around.  Thanks for such a great app.
