### ISSUE TITLE
NullPointerException with start radio

### ISSUE THREAD

**Issue by sekisushai** [daneren2005/Subsonic#703]
Hello,
I'm having a "NullPointerException" message when trying to start a radio from artist page
see screenshot :
![2016-05-28](https://cloud.githubusercontent.com/assets/9271464/15629330/6e2df0f0-24e4-11e6-8ae8-f1b8884714f7.png)
I'm using Madsonic v6.1 and Dsub 5.1.7

**Comment by daneren2005** [comment]
Without some logs or idea what Madsonic is doing differently than stock Subsonic I can't so anything.

**Comment by sekisushai** [comment]
I've tested this bugfix on version 5.1.8, but the radio functionality disappeared ?

**Comment by daneren2005** [comment]
This should be fixed soon

**Comment by sekisushai** [comment]
Thanks, the button reappeared in 5.1.9. However, I've got now a "Playlist is empty" now when I select the Start Radio button, whatever artist is asked. I've joined a DSub log here. 
http://pastebin.com/5CuN2drZ
The serverlog of Madsonic doesn't mention anything..
Thank your for your help

**Comment by daneren2005** [comment]
I honestly don't have a Madsonic server running and I see nothing wrong with any of that.  If you want to create a temp username/password for me I can take a look at what Mad changed this time.  You can email me at dsub.android@gmail.com
