### ISSUE TITLE
Skip to next track with non-bluetooth headset

### ISSUE THREAD

**Issue by PeterBehrend** [daneren2005/Subsonic#705]
This is a feature I really miss in ANY :-) player: Skip to next track with double-click on NON-bluetooth (cabled) headset with a single button. Maybe even previous track with triple-click (or long-press or whatever). Possibly configurable. Would save 100's times pulling my phone from pocket just to skip a song. Must admit I am not sure if a double-click can at all be detected and reacted upon...?

Thank you so much for this excellent player. After adding Subsonic support to my Ampache server I stopped using all other players.  Also gapless playback is a breeze. Never looked back.

kind regards
/peter b.

**Comment by daneren2005** [comment]
I'm not sure what you mean by non-bluetooth headset.  What non-bluetooth headsets even have buttons in the first place?
