### ISSUE TITLE
Latest update no longer lists subfolders.

### ISSUE THREAD

**Issue by silviuvulcan** [daneren2005/Subsonic#707]
Hi,

I have my albums under the usual:
````
music
-- artist
---- year - album 1
---- year - album 2
````

After the latest update I can go in library and I see the list of folders for "artist" but going deeper shows
"no data"

If I pull-down to refresh the subsonic log shows:
```` 
[6/12/16 8:16:23 AM EEST]	WARN	RESTFilter	Error in REST API: NullPointerException
````

Running subsonic 5.3 on freebsd. The web interface works fine, and dsub worked fine on same configuration before yesterday's update.

Playing from playlists or random/recent albums works fine.

Any ideas?

**Comment by sumoneelse** [comment]
I've rolled back to 5.1.7 to work around this issue for now.  (Old APKs are available here in the repository.)  Thank you for taking the time to report this!  Rest assured it's not just you.
