### ISSUE TITLE
Option to change default action on song tap

### ISSUE THREAD

**Issue by Nairou** [daneren2005/Subsonic#714]
Right now, when you tap a song, DSub immediately plays the song, discarding all songs in the playlist. It can be annoying to be slowly adding songs to a playlist using the Play Last menu, and then you accidentally tap a song and lose the whole list.

It would be nice if there was an option to change what happened when you tap a song, so that Play Last could be set as a default. Even better if it could be smart enough to know when to do which one (Play Now if no song is playing, otherwise Play Last).

**Comment by jmvalente** [comment]
Yes, this would be great. It's really frustrating if you accidentally do this in the car (trying to switch between GPS, skip a song and miss, etc) and can't take the time to re-queue everything because you're driving.
