### ISSUE TITLE
Null pointer exceptions breaking useful functions

### ISSUE THREAD

**Issue by jebsky** [daneren2005/Subsonic#720]
I recently did some music library management and my subsonic database now has some flaws. This does not break the Web app but it does break dsub. I'm getting null pointer exceptions.

The starred list doesn't work at all and the recently added works until you scroll to the first anomaly.

This can probably be fixed with one or two try - catch statements.

I'll make you a debug account so you can try it out

**Comment by daneren2005** [comment]
I tried using your server and scrolling down on the recently added list and wasn't able to reproduce any issues.  Can you send me a log (Home tab -> Send Logs) right after triggering the error so I can see if that has any helpful information?

**Comment by daneren2005** [comment]
The NPE is from the server: `<subsonic-response status="failed" version="1.14.0"><error code="0" message="NullPointerException"/></subsonic-response>` so there is nothing I can change on my end.
