### ISSUE TITLE
GooglePlay-less version for F-Droid build

### ISSUE THREAD

**Issue by baldurmen** [daneren2005/Subsonic#722]
Hey!

Looking at the [F-Droid repo of your app](https://f-droid.org/wiki/page/github.daneren2005.dsub), I see that GooglePlay became a required dependency between 4.3.5 and 4.7.5. Looking at the changelog, I guess it happened when you added Chromecast, but I might be wrong on that.

Anyway, I was wondering if it would be possible to have a separate branch that removed GPlay dependencies (and thus GPlay dependent features) so that F-Droid could start building newer versions again.

I'm asking this very candidly since I don't know the code base at all and thus don't know how important GPLay is in the new versions of the app. All I know is that I know a lot of people using your app on F-Droid!

Thanks for your work on this app, I use it daily!

**Comment by daneren2005** [comment]
No. There are a few closed issues for this already that explain why.
