### ISSUE TITLE
Play Next adds the track to the end of the playlist

### ISSUE THREAD

**Issue by androideo** [daneren2005/Subsonic#723]
I don't know, if this bug is fixed in Version 5.2. But when i hit "Play Next" in the menu the track will be added at the end of the playlist

**Comment by daneren2005** [comment]
I just tried doing the songs option menu -> Play Next and it worked.  I then tried multi selecting a few songs and doing Play Next and that also worked.  I'm not saying there isn't a bug somewhere, but the basics work fine as far as I can tell, so I need some more specifics about what you are doing to get it to not work.

**Comment by androideo** [comment]
It seems to work fine, if i select a song/a few songs and hit play next. But when i hat "play next" for the whole album, it will be added at the end. I would like to give you some more information, but i don't know how. Are there some debugging logs that i can get with adb?

**Comment by daneren2005** [comment]
Your right I can reproduce if I don't select anything and press Play Next.
