### ISSUE TITLE
Allow variable playback speed instread of fixed speeds.

### ISSUE THREAD

**Issue by apastuszak** [daneren2005/Subsonic#726]
I LOVE the fact that variable playback speed was added.  I can now use Dsub for Podcasts and Audiobooks.

But I listen to my podcasts at 1.7 speed, and Dsub only does increments of 0.5.  Is there an easy way to make this a slider and you can pick increments of 0.1?

Now if only Subsonic would add variable speed playback support to the web interface...

**Comment by daneren2005** [comment]
What is the point of this?  I guess I don't see what the practical difference between 1.5 and 1.7 would be since they sound pretty identical to me.  Are there clients you use which allow you to specify the exact playback speed like that?

**Comment by apastuszak** [comment]
Yes.  I am using Pocket Casts now.  1.7x is the fastest speed I can do a podcast and still be able to understand the people.

**Comment by silviuvulcan** [comment]
Same here, I play at 1.7 - 1.8 depending on podcast/audiobook; I can't follow at 2.0 but a .3 difference over 1.5 at a 10h audiobook is still one hour.
