### ISSUE TITLE
replay gain question

### ISSUE THREAD

**Issue by yield65** [daneren2005/Subsonic#728]
Hi,
I'm starting to use mp3gain on linux and the man page says it supports writting the tag as ID3v2 and as APEv2 and it seems that many apps doesn't support APEv2 on mp3 with ID3v2 tags simultaneously and others just doesn't support APEv2 on mp3 files, so what is the best way to apply the replay gain tag to an mp3 file to be played with dsub?
Thank you.

**Comment by daneren2005** [comment]
ID3v2 tags is all DSub supports

**Comment by yield65** [comment]
Thank you for your replay, final question, in regard of ogg files, does dsub support the replay gain information saved as vorbis comments tag?

**Comment by daneren2005** [comment]
I haven't tested but I doubt it
