### ISSUE TITLE
DSub not loading music files from server

### ISSUE THREAD

**Issue by slashbuzz** [daneren2005/Subsonic#729]
Running DSub on a Samsung Galaxy S5

Android = 6.0.1
Dsub = 5.2

It is able to connect to the Subsonic server and sync the folder structure, playlists, etc.

However, if I select a song that has not been played on the phone before, it is unable to sync and sits at 'Downloading - 0 bytes' forever.

I noticed that other music players on the phone were having issues after updating to the latest version of Android; however, after uninstalling Subsonic and Neutron on the phone and reinstalling them, those apps are now working OK.

I uninstalled Dsub and reinstalled it, but it is still unable to download music...

I love the Dsub app and have been using it for years; how can I get it working again?

Please advise -

Thanks!

**Comment by daneren2005** [comment]
If reinstalling worked for the original Subsonic app, try clearing the data cache for DSub since it tries to use the Android Backup to keep your settings between devices/installs.

**Comment by slashbuzz** [comment]
Hi, I tried running Subsonic this morning, and it seemed to be having the same problem as Dsub; stays at 'downloading - 0 bytes' forever

:(

**Comment by slashbuzz** [comment]
tried clearing both cache and data.

after re-inputting the server credentials and testing the connection, i navigated to a previously unused library folder and clicked on a song.

it navigated the folder structure fine, and even displayed the album art; but it is stuck at 0 bytes...

**Comment by slashbuzz** [comment]
sorry - reopening issue...

**Comment by daneren2005** [comment]
What location are you trying to have DSub write to?  Can you go to Settings -> Cache -> Cache location and try both the Internal and External buttons to see if either one of those spots are writable?

**Comment by garyo** [comment]
I think I'm having a similar issue, not sure. I'm on Nougat, and I've done the clear-data-clear-cache-uninstall-reinstall thing several times. As @daneren2005 says, it's weird that after reinstalling, my server is still there, and my preferences. I wish there were a way to wipe everything and start from scratch.

What I'm seeing is a little different now though: I just get the "No data" screen for several recently added albums. Looking through my collection, it's something like 1 in 10 albums have "No data". I think (?) everything was fine until recently (I upgraded to Nougat and new version of DSub).

I've tried "rescan server", that doesn't seem to fix the problem. (It's also really quick, but maybe that's expected; I only have ~5000 songs.)

**Comment by daneren2005** [comment]
If after reinstalling you still have the server settings there it isn't actually clearing the cache.  Clear the cache/data *after* you have reinstalled the app and it should fix it.

**Comment by clint1337** [comment]
Hi Daneren2005, I also have issue with Dsub.
I've got Android 6.0.1 and latest Dsub, and latest Subsonic.

When in Dsub (LAN) I can test the connection and it works fine, but when i go in library it says no data.
When in Dsub (outside my LAN) everything works. 

I tried with cleaning cache/data when Dsub is installed, same result.
I tried with cleaning cache/data after a reinstall, same result.

**Comment by daneren2005** [comment]
@clint1337 No that sounds like something completely different.  Yours just sounds like you don't have the server setup correctly to handle LAN vs WAN connections.  It's probably either an issue with the router or the server's firewall.
