### ISSUE TITLE
No playback with Android 7.0

### ISSUE THREAD

**Issue by OpenAai** [daneren2005/Subsonic#730]
As mentioned on the [forum](http://forum.subsonic.org/forum/viewtopic.php?f=16&t=16686), playback on Android 7.0, with Dsub 5.2 and Subsonic 6.0, it is no longer possible to play music on Dsub. Is there a workaround for this problem?

**Comment by mycahb2** [comment]
On the Android N beta releases you could clear your data and reconfigure.  It'd sort of work but I still had other issues.

**Comment by garyo** [comment]
Same here, n6p, just updated to nougat, no playback. Skips from song to song in the UI. Help! No car audio without my dsub!

**Comment by daneren2005** [comment]
Can someone try turning off gapless Playback as well as make sure there are no dev options which might affect this (I know Marshmallow introduced a new experimental player at one point)

**Comment by OpenAai** [comment]
Turing off gapless playback didn't change anything for me.

---
Groetjes,

Arie 

Scott Jackson schreef op 24-08-2016 16:44:

> Can someone try turning off gapless Playback as well as make sure there are no dev options which might affect this (I know Marshmallow introduced a new experimental player at one point) 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/daneren2005/Subsonic/issues/730#issuecomment-242089560
[2]

**Comment by Mycah** [comment]
I cleared data, reset my server, and disabled gapless and everything works again.

I have developer options enabled but all the settings are currently default.

Android 7.0 build NPD90G

**Comment by OpenAai** [comment]
What do you mean with "cleared data"?
Groet,

Arie


-------- Origineel bericht --------
Van: Mycah Mattox <notifications@github.com>
Verzonden: 24 augustus 2016 17:28:29 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

I cleared data, reset my server, and disabled gapless and everything works again.

I have developer options enabled but all the settings are currently default.

Android 7.0 build NPD90G

**Comment by Mycah** [comment]
Clear data in the app options under settings.  It usually fixes the no playback issue when upgrading to 7.

You'll have to reconfigure your server settings, and recache your songs.

**Comment by daneren2005** [comment]
Mycah: Did disabling the gapless playback issue fix being able to play at all?

**Comment by Mycah** [comment]
Yeah, disabling gapless playback has the app working properly again.  No more multiplaying songs.

**Comment by OpenAai** [comment]
This didn't work for me. 
Groet,

Arie


-------- Origineel bericht --------
Van: Mycah Mattox <notifications@github.com>
Verzonden: 24 augustus 2016 20:22:12 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

Yeah, disabling gapless playback has the app working properly again.  No more multiplaying songs.

**Comment by daneren2005** [comment]
Mycah: Oh ok the gapless playback fixed the multiple playing songs issue.  Can you try out this apk and let me know if it fixes that issue with gapless playback enabled? https://dl.dropboxusercontent.com/u/23354647/DSub%205.2-fix.apk

OpenAai: Can you try going into Settings -> Cache/Network -> Cache Location.  Copy/Paste what the location you have there is.  Try clicking the Internal button and see if it changes anything.  If Mycah can copy paste in too that would be awesome for debugging purposes.

**Comment by Mycah** [comment]
Playing on headphones now, and its playing fine.  I'll test it in my car later over bluetooth.

**Comment by OpenAai** [comment]
Location: /storage/emulated/0/Android/media/github.daneren2005.dsub/music
Groet,

Arie


-------- Origineel bericht --------
Van: Scott Jackson <notifications@github.com>
Verzonden: 24 augustus 2016 20:26:05 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

Mycah: Oh ok the gapless playback fixed the multiple playing songs issue.  Can you try out this apk and let me know if it fixes that issue with gapless playback enabled? https://dl.dropboxusercontent.com/u/23354647/DSub%205.2-fix.apk

OpenAai: Can you try going into Settings -> Cache/Network -> Cache Location.  Copy/Paste what the location you have there is.  Try clicking the Internal button and see if it changes anything.  If Mycah can copy paste in too that would be awesome for debugging purposes.

**Comment by OpenAai** [comment]
OK. So I deleted all cache, uninstalled the app and installed your last'fix' all version. 
Although I expected a new configuration, my server config was added automagically. 
Still with the same result, so skipping all songs. I will send you new logs as well. 
Groet,

Arie


-------- Origineel bericht --------
Van: Scott Jackson <notifications@github.com>
Verzonden: 24 augustus 2016 20:26:05 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

Mycah: Oh ok the gapless playback fixed the multiple playing songs issue.  Can you try out this apk and let me know if it fixes that issue with gapless playback enabled? https://dl.dropboxusercontent.com/u/23354647/DSub%205.2-fix.apk

OpenAai: Can you try going into Settings -> Cache/Network -> Cache Location.  Copy/Paste what the location you have there is.  Try clicking the Internal button and see if it changes anything.  If Mycah can copy paste in too that would be awesome for debugging purposes.

**Comment by Mycah** [comment]
If your server info is still there you're not clearing data.  Hit the clear data button, it's not just the cache.  You have to delete all the configuration settings or it won't work.  I guess, make sure the app is closed as well in case its keeping the configuration loaded when you delete the files out from under it.

**Comment by daneren2005** [comment]
When we say delete cache we mean something like this: http://android.stackexchange.com/questions/20751/clear-application-cache-on-ics

**Comment by OpenAai** [comment]
So I've deleted the phone's cache with CCleaner, removed the servers listed in the Dsub app, deleted the cache location, and reinstalled the app. Still with the same result, online or offline, all songs are skipped. 
Groet,

Arie


-------- Origineel bericht --------
Van: Scott Jackson <notifications@github.com>
Verzonden: 24 augustus 2016 21:30:12 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

When we say delete cache we mean something like this: http://android.stackexchange.com/questions/20751/clear-application-cache-on-ics

**Comment by samdennen** [comment]
I cleared data, disabled gapless playback and everythings working fine.

**Comment by zbaylin** [comment]
I seem to have the same problem with the gapless playback. Songs will either play at the same time, or randomly skip to the next one after a short period of time (not constant). Also, if I exit out of the app with no music playing and enter back into it, music will start playing at once without the app in "play" mode. Disabling gapless playback does seem to fix this, but the "fixed" version posted does not seem to work for me. Any help would be appreciated.

**Comment by daneren2005** [comment]
Try this apk it should fix the issue completely.  https://dl.dropboxusercontent.com/u/23354647/DSub%205.2.1.apk

**Comment by samdennen** [comment]
Thank you, are you going to be updating this in the play story shortly or should I grab this apk now?

**Comment by daneren2005** [comment]
Can you try it now and let me know if it works?  I don't anything with N since I was counting on Google continuing support of the Nexus 5 :/

**Comment by zbaylin** [comment]
It does seem to work for me

via CloudMagic Email [https://cloudmagic.com/k/d/mailapp?ct=pa&cv=8.6.37&pv=7.0&source=email_footer_2] On Wed, Aug 24, 2016 at 7:53 PM, Scott Jackson < notifications@github.com [notifications@github.com] > wrote:
Can you try it now and let me know if it works? I don't anything with N since I was counting on Google continuing support of the Nexus 5 :/

**Comment by samdennen** [comment]
Sure, give me two minutes. I'm also working on an unrelated bug

**Comment by garyo** [comment]
I was also having this problem. Cleared cache completely, uninstalled. Installed new version (23354647/DSub%205.2.1.apk). Reconfigured, kept gapless enabled (it's great). All seems to be working fine now on N on my N6P!
Thanks daneren2005, great work!

(I know this isn't the right place for this, but any possibility of getting a 1.2x playback rate for podcasts?)

**Comment by samdennen** [comment]
All good here, 5.2.1.apk worked with gapless playback enabled.

**Comment by daneren2005** [comment]
Yeah I am planning on adding some more granularity to the playback rate options with https://github.com/daneren2005/Subsonic/issues/726.

**Comment by samdennen** [comment]
should I uninstall this and wait for your update to be available from the play store?

**Comment by daneren2005** [comment]
It is exactly what I am going to be uploading to the play store in a moment.

**Comment by samdennen** [comment]
Yeah but will this auto update in the future?

**Comment by daneren2005** [comment]
Yes

**Comment by samdennen** [comment]
Awesome, ok thank you

**Comment by OpenAai** [comment]
The problem isn't solved for me. Can you please have a look at the logs I'm sending you. 
Groet,

Arie


-------- Origineel bericht --------
Van: Scott Jackson <notifications@github.com>
Verzonden: 25 augustus 2016 02:14:08 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

It is exactly what I am going to be uploading to the play store in a moment.

**Comment by OpenAai** [comment]
OK, the problem is solved now. After clearing cache and data it's working again. Thanks Scott and everyone for the effort. 
Groet,

Arie


-------- Origineel bericht --------
Van: Arie Koppelaar <arie@koppelaar.org>
Verzonden: 25 augustus 2016 07:13:11 CEST
Aan: daneren2005/Subsonic <reply@reply.github.com>, Scott Jackson <notifications@github.com>, daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

The problem isn't solved for me. Can you please have a look at the logs I'm sending you. 
Groet,

Arie


-------- Origineel bericht --------
Van: Scott Jackson <notifications@github.com>
Verzonden: 25 augustus 2016 02:14:08 CEST
Aan: daneren2005/Subsonic <Subsonic@noreply.github.com>
CC: OpenAai <github@koppelaar.org>, Author <author@noreply.github.com>
Onderwerp: Re: [daneren2005/Subsonic] No playback with Android 7.0 (#730)

It is exactly what I am going to be uploading to the play store in a moment.

**Comment by daneren2005** [comment]
Alright glad another cache wipe fixed it for everyone!
