### ISSUE TITLE
Casting issues with Android 7.0

### ISSUE THREAD

**Issue by harrisiirak** [daneren2005/Subsonic#736]
Hello,

After upgrading to latest Android 7.0 release I'm unable to cast my Kodi based media center. The cast button is disabled. Worked like a charm with Android 6.0. I'm able to cast with other UPnP supported applications.

What I'm missing here?

BR

**Comment by daneren2005** [comment]
Try installing https://www.dropbox.com/s/e5ze12v2icz3t5z/DSub%205.2.2-fix.apk?dl=0 and let me know if it fixes your issue.  The library I use for DLNA connections had a bugfix release for Android 7.0.

**Comment by harrisiirak** [comment]
@daneren2005 thanks for the quick answer and the fix. Yep, it fixed the issue and now it's working as supposed.

**Comment by daneren2005** [comment]
I will close it once the fix has gone out to everyone.  Thank you for confirming that fixed it though!

**Comment by wildwoodashes** [comment]
@daneren2005 Does this fix apply to casting to Chromecast? I'm running into an issue when I try to cast to Chromecast all I get is "failed to load" after upgrading to Android 7.0. Dsub connects (tested on both a Chromecast (2015) and a Chromecast audio), but just displays "failed to load" and nothing starts playing.
