### ISSUE TITLE
half baked  video urls to Vlc?

### ISSUE THREAD

**Issue by gerroon** [daneren2005/Subsonic#741]
Hi

I am using Ampache's Subsonic backend. And Dsub seems to connect and play audio and list my videos however when I try playing videos (via Vlc) it looks liekt he urls are not passed properly. Because Vlc cant seem to be able to process the url and play the url as far as I can tell but if I login to ampache web and stream from the web interface to Vlc it works. 

thanks

**Comment by daneren2005** [comment]
That sounds like an Ampache issue not actually implementing the video urls correctly
