### ISSUE TITLE
Show all media - Show Artist Media even on VA Albums

### ISSUE THREAD

**Issue by rhyddic** [daneren2005/Subsonic#750]
Show all media only lists songs under a particular Album Artist.  Ideally, Titles from an Artist that appear on other albums, such as Various Artists compilations should be included in All Media.  Optionally, it'd be nice to see partial matches along with exact matches.  Personally, I would like to see David Guetta feat. Sia, and Sia feat. Sean Paul along with the rest of my Sia tracks.

**Comment by daneren2005** [comment]
This seems like a limitation of the API as I am just grabbing what Subsonic says is under that artist.
