### ISSUE TITLE
Add skip album button

### ISSUE THREAD

**Issue by idelsink** [daneren2005/Subsonic#753]
Add an album that skips the queued album. Just like the skip list in poweramp button. 

(make this button available via notification  and player itself)

**Comment by idelsink** [comment]
I usually use this in poweramp while randomly playing lists(albums)

**Comment by daneren2005** [comment]
I don't really intend on adding anything like this.  It seems like an incredibly niche use case to want to skip entire albums regularly enough to warrant using extremely limited UI space for something like this.
