### ISSUE TITLE
Caching tracks twice

### ISSUE THREAD

**Issue by T7000** [daneren2005/Subsonic#759]
Depending on where I play a track (album, playlist, top last.fm,) tracks sometimes don't appear cached even though they are and I end up with two files of the same track, but with different track numbers.

It's been happening for a few versions I think, I'm on the beta though.

For example: http://i.imgur.com/trtsr0Q.png

**Comment by daneren2005** [comment]
Mostly leaving this as a note for myself to fix: In the TopSongsParser I am re-purposing the tracks field even though it is used for deciding the filename.  I need to stop doing that as well as double check that it is not being done like that anywhere else.
