### ISSUE TITLE
Casting to ChromeCast Audio fails after first track

### ISSUE THREAD

**Issue by sumoneelse** [daneren2005/Subsonic#760]
Connectivity to my ChromeCast audio devices appears to be spotty at after the latest update.  Specifically I can normally connect to the CC Audio device and play the first track; when transitioning to the next track I get a toast that says "failed to load."  Sometimes the next track will play anyway.  Just now, when recreating the issue to describe it in as much detail as I could, the track names for the second and subsequent tracks all flashed in rapid succession and playback stopped after the first track.

I experience this on two CC Audio devices in my house, as well as on two different phones, so I'm reasonably certain it's DSub.  Is there anything I can do to help facilitate the identification of a root cause?

**Comment by daneren2005** [comment]
What version of DSub are you running?  I was having that issue after a Chromecast update but I fixed it already in the latest update.

**Comment by sumoneelse** [comment]
I just woke up and the update was available to me in the play store this morning (it wasn't last night).  I'm so happy to report it's fixed.  Nothing like having your problems solved overnight.  Thanks Scott!
