### ISSUE TITLE
Casting info window a little too big - "Stop streaming" button invisible

### ISSUE THREAD

**Issue by arno1979** [daneren2005/Subsonic#761]
I'll include a screenshot to make this more clear: Whenever I want to stop my phone from casting to my Chromecast the window that pops up when I touch the cast button is just a little too big to fit the screen of my phone. As the title says: the "Stop streaming" button is not accessible this way, I have to turn the phone around so the screen flips and the button becomes visible.
![streaming-button-missing](https://cloud.githubusercontent.com/assets/1838113/19697451/ab9d8ebe-9aeb-11e6-8e7b-82cca859004a.png)

**Comment by daneren2005** [comment]
What phone is this?  And did this just start being a problem on the last update?

**Comment by arno1979** [comment]
Fairphone 2 running Fairphone OS 1.8.1 (Android 5.1). This not a new problem, has been like this for a couple of versions, there was a time when the button was visible but I can't remember when, sorry.

**Comment by daneren2005** [comment]
Since the Google Support Library handles the creation of the dialog, I am not going to change this.
