### ISSUE TITLE
Incorrect 'byYear' request with Subsonic API 1.14.0

### ISSUE THREAD

**Issue by nicolasmartinelli** [daneren2005/Subsonic#764]
Hello,

When the server uses API 1.14.0 of Subsonic, the POST request received is incorrect for endpoint `getAlbumList2.view`, sort by year:
`/rest/getAlbumList2.view?u=toto&p=enc:toto&v=1.2.0&c=DSub&size=20&offset=0&type=byYear&fromYear=2010&toYear=2000`

 Values for parameters `fromYear` and `toYear` should be switched.

**Comment by daneren2005** [comment]
That is a valid part of the API.  I requested it at https://groups.google.com/forum/?fromgroups#!topic/subsonic-app-developers/5IvxMi9SJgQ.  It looks like it never officially got into the changelog, but it is now something Subsonic accepts as valid.

**Comment by nicolasmartinelli** [comment]
Good to know, thanks!
