### ISSUE TITLE
Some albums list no data on Android 7.0.  About 20% of library effected. 

### ISSUE THREAD

**Issue by chess1043** [daneren2005/Subsonic#769]
Love dsub but since switching to an LG V20 on android 7.0 some albums wont list the songs and state there is "no data." I can still access the songs by going to last fm top tracks and can see them in the search bar.  About 20% of library effected. I have tried uninstalling reinstalling, clearing cache before and after and all different order, still get the same issue. Please help.

**Comment by chess1043** [comment]
#729 Garyo seems to maybe be having the same issue that was not resolved?

**Comment by chess1043** [comment]
I am using subsonic, not madsonic.

**Comment by daneren2005** [comment]
I would need a temp username/password emailed to me at dsub.android@gmail.com to debug then since you are the only one to report something like this.

**Comment by flamingspaz** [comment]
I have been having this issue for a while, I think it may be related to file extensions or opus files, as when going into offline mode my app shows "No Data" for all .opus files (mp3 and ogg is fine, haven't tested opus with .ogg extension). This is with the latest official subsonic server, my transcoding setting:

Convert from | Convert to | Step 1 | Step 2
------------ | ------------- | ------------- | -------------
`flac mp3 wav` | `opus` | `ffmpeg -i %s -ab %bk -v 0 -f wav -` | `opusenc --quiet --bitrate 128 --downmix-stereo --title %t --artist %a - -`

**Comment by flamingspaz** [comment]
(Forgot to mention, this is with the Pixel on 7.1.2)

**Comment by daneren2005** [comment]
While I am at it, are there any other file types you guys are using that you can think of?

**Comment by flamingspaz** [comment]
I opened #818 to suggest some.
