### ISSUE TITLE
Permanent cache does not start downloading unless song is played

### ISSUE THREAD

**Issue by dengste** [daneren2005/Subsonic#770]
I think that in older versions I could just mark albums for permanent cache and then DSub would immediately start downloading. Now I have to actually start playing a song until downloading starts. It'd be nice if the old behavior could be restored.

**Comment by daneren2005** [comment]
I just tried it a few times with both multi select and using the item dropdown and it seems to work just fine so unless you can provide some more information I'm not sure what you are talking about.

**Comment by dengste** [comment]
Updated Ampache and reinstalled DSub on the phone and now it works. I am sorry for the noise.
