### ISSUE TITLE
Only TLS 1.0

### ISSUE THREAD

**Issue by hanspeter1** [daneren2005/Subsonic#772]
I am recently changed my Subsonic-Server to use only TLS 1.2. Now DSub cannot connect to my Subsonic-Server. So, I played around and found out that DSub on my Android 4.4.2 can only connect if I use TLS 1.0. Android 4.4.2 supports at least TLS 1.1, so it’s a DSub limitation.

**Comment by Yetangitu** [comment]
https://blog.dev-area.net/2015/08/13/android-4-1-enable-tls-1-1-and-tls-1-2/
