### ISSUE TITLE
Bookmark and Starred confusion (especially in French translation)

### ISSUE THREAD

**Issue by 3615pipou** [daneren2005/Subsonic#776]
I in the french version "Bookmarks" is translate by "favoris" and "Starred" also by "favoris". So there is a confusion.

Maybe you could translate "Bookmarks" by "Signets" and "Starred" by "Favoris".

But, in fact it still confuse because there is no  "bookmarks" feature in Subsonic. So the bookmarks are not sync with the server. Maybe bookmarks and starred function should be merge ?

Currently "bookmarks" are easy to find on the left panel but to find "stared" you have to go to home. Plus I can star an artist or an album but I can't bookmark them.

So maybe the bookmark feature is useless ? Maybe it could be replace by the "starred" ?

**Comment by daneren2005** [comment]
No bookmarks and starred items are completely different.  You can use stars as bookmarks sort of I guess but stars don't have a position associated with them and bookmarks do.  Bookmarks most definitely are synced to the server.  The web GUI just doesn't expose them.  If you switch to another DSub client on another device you will see that bookmarks are saved on the server.  There is also a ton of automatic bookmarking logic designed to make sure you don't lose your place when listening to long audio books or podcasts.  None of that would be possible using only starred items.

I'm not sure if it is just a language thing, but stars and bookmarks are nothing alike and really shouldn't be confusing at all.  You can choose to use either, both, or neither, but they have different meanings and functionalities which I feel are pretty well encapsulated by their names (at least in English).  It looks like main issue is the French translation got it wrong.  But that is a simple change.

**Comment by 3615pipou** [comment]
Thanks for the update !
