### ISSUE TITLE
Broken playback of FLAC files

### ISSUE THREAD

**Issue by Prior99** [daneren2005/Subsonic#783]
I deactivated the mp3 transcoder on my subsonic server and because of this DSub receives all music in FLAC format.

Everything works fine (Cover art, duration of song, meta data display, etc.), except for the playback which just generates some extremly painful sounds (The original music is still guessable, though).

The playback of the cached files via VLC and other players works without any problem on the same device, so the cached files are not broken.

**Comment by daneren2005** [comment]
DSub is using the native media player of the device and VLC and some others use their own custom media players.  While it is on the TODO list to use a custom media player engine, I have no way to fix device specific media playback issues such as this right now.
