### ISSUE TITLE
7.0 casting to subsonic jukebox pauses playback on call

### ISSUE THREAD

**Issue by gkeiner** [daneren2005/Subsonic#785]
I've noticed that since upgrading to Android 7.0, the behavior of dsub has changed on my Galaxy S7 such that when placing a call, the playback pauses when casting to a subsonic jukebox player.  Before the 7.0 update, playback would continue uninterrupted, as it should.  Is this behavior intended for some reason (if so, why?), configurable, or byproduct of an OS changed introduced with 7.0?

**Comment by daneren2005** [comment]
That has always been the behavior.  The intention is that usually the person who would be answering the call is also the one listening to the casted music, so it is better to pause instead of the user trying to fumble with their phone at the beginning of a phone call.
