### ISSUE TITLE
Feature request: 'Scan music folders' from in-app

### ISSUE THREAD

**Issue by transiti0nary** [daneren2005/Subsonic#791]
I was thinking it would be useful to have to option to 'Scan music folders' on demand from within the app, seeing as Subsonic itself only allows the automation of this once every 24 hours. What would be perfect would be the 'pull to refresh' on Library view to perform this automatically in the background, but any old button hidden somewhere would be enough. I guess it depends whether the Subsonic API supports this though.

**Comment by daneren2005** [comment]
I probably won't do it through the pull to refresh action since at least on Madsonic the scan makes the server unusable and I am guessing there is a decent change it does the same thing for Subsonic.  But yes this should be easy to add as a separate button.
