### ISSUE TITLE
Use Subsonic with Android Auto

### ISSUE THREAD

**Issue by Bjoern3003** [daneren2005/Subsonic#796]
Hi, I have found the Issue   #774 , that fixed the android auto function.

What setting do I have to set, that I can use subsonic with android Auto? My understand is, that Play Music sync the Music Library from Subsonic and Android Auto is playing Music from Play Music List.

**Comment by LemarinelNet** [comment]
Did you install DSub from play store or from APK ?
From my findings, it only shows in android auto if installed from play store (purchased )
It seems to be related to google and not dsub !

**Comment by daneren2005** [comment]
I am linking to the other closed issue for this: https://github.com/daneren2005/Subsonic/issues/807
