### ISSUE TITLE
Privacy?

### ISSUE THREAD

**Issue by gerroon** [daneren2005/Subsonic#797]
Hi

Sorry for asking about this here. Does the Github release apk collect privact data, analytics etc and ping home? I am privacy concious and I try to make sure that apps that need net connection is honest about what they do.

thanks

**Comment by daneren2005** [comment]
The Github release apk is the same one I upload to the Play Store.  I do not explicitly ping home about anything.  The only place I coded in sending sensitive data somewhere else is in the Send Logs function, which only runs if you manually click it.

Now as for implicit behavior...I have no idea.  I know that the Play Store collects data from user's about who is running what and they send logs whenever there is an app crash.  I have no idea if that is added to the apk when we upload it up, automatically collected if Play Services is installed on the device, or some other vector.

**Comment by gerroon** [comment]
Thanks for the follow up. I appreciate the input.
