### ISSUE TITLE
DSub doesn't show up in Android Auto

### ISSUE THREAD

**Issue by paride** [daneren2005/Subsonic#807]
As the title says, DSub doesn't show up in Android Auto. I tried installing Audible and and it does show up there, so my Android Auto is not broken. DSub itself is working fine (I can play music from the demo server without any problem).

Some information on my setup:

- Device: Nexus 6 with stock android 7.1.1
- DSub version: 5.3.5
- Everything is up to date from the play store
- Google Play Music is disabled (I'm not using it, I don't think it matters)

**Comment by boudafc** [comment]
Hello,
I encounter also this same problem. DSub is not listed in the android auto app.
My setup:

- Device: Sony Xperia Z3 Compact - Android 6.0.1
- DSub version: 5.3.5
- Everything is up to date from the play store
- Google Play Music is disabled

**Comment by daneren2005** [comment]
Are you guys side loading or installing from the Play Store? I don't know if it makes a difference but there is an option to enable it in the dev console so it might have to go through the Store to work

**Comment by paride** [comment]
I manually installed the latest apk from GitHub.

**Comment by boudafc** [comment]
I also installed it through apk from GitHub. I don't think so install it from playstore will improve the thing because when I select app compatible with android auto in playstore it is not suggested.

**Comment by boudafc** [comment]
Ok, so, I answer myself, android auto seems allow only app installed by play store (even if app isn't listed in compatible selection for android auto). 
So I purshased the (wonderfull) app and magic, DSub is available now in android auto.

So, I think this subject can be closed :)

**Comment by paride** [comment]
It's an annoying limitation and a workaround would be more than welcome, but I'll understand if @daneren2005 won't dedicate his time to it.

**Comment by daneren2005** [comment]
Yeah I don't think there is anything I can really do.  I imagine when uploading the app to the Play Store they inject something which allows Auto to work.  I can't really think of a work around for that.  Thank you for responding after you tried installing the version from the Play Store BTW.

**Comment by LemarinelNet** [comment]
Just to add my feedback : 
I just got a new car with android auto.
Was pleased to read that DSub should be supported, I did a test : 
Till now, I haven't bought DSub, and it did not shown in android auto.
As soon I bought DSub from play store, it did show in android auto !

**Comment by peher** [comment]
Hello 
This worked great for me : https://pixplicity.com/setting-install-vendor-debug-app/
adb push app.apk /sdcard/app.apk
adb shell pm install -i "com.android.vending" -r /sdcard/app.apk
adb shell rm /sdcard/app.apk

**Comment by TUISTERa** [comment]
> Hello
> This worked great for me : https://pixplicity.com/setting-install-vendor-debug-app/
> adb push app.apk /sdcard/app.apk
> adb shell pm install -i "com.android.vending" -r /sdcard/app.apk
> adb shell rm /sdcard/app.apk

This should go to some faq section :) Golden... 
Also , since android P , the app should be pushed to /data/local/tmp/app.apk instead of /sdcard/app.apk

**Comment by mojhale** [comment]
Sideloading with ADB worked like a charm for me on my Moto x4. I just got a Galaxy S10, and DSub doesn't show up. Any thoughts?

**Comment by popeen** [comment]
There is actually a hidden developer menu in Android Auto similar to the one in Android, from this menu you can enable unknown sources. 

Once you have enabled this go to the developer options menu in the Auto app and you should find the option unknown sources there. I don't really remember but you might need to restart auto and the app for it to show up.

Hope that helps :)


This how to enable devmode from the documentation at https://developer.android.com/training/cars/testing#test-auto

> Do one of the following to open the Android Auto settings, depending on the version of Android running on the device:
> 
> Android 10 or higher: On the device tap Settings > Apps & notifications > See all apps > Android Auto > Advanced > Additional settings in the app.
> Android 9 or lower: In the Android Auto app, tap the Menu, then tap Settings.
> Scroll to the About section near the bottom and tap Version to display all of the version and permission information.
> 
> Tap the Version and permission info section 10 times.
> 
> The Allow development settings dialog appears.
> 
> Tap OK.
> 
> Developer mode is now enabled and you can access developer options in the overflow menu.

**Comment by bitterroots** [comment]
> There is actually a hidden developer menu in Android Auto similar to the one in Android, from this menu you can enable unknown sources.
> 
> Once you have enabled this go to the developer options menu in the Auto app and you should find the option unknown sources there. I don't really remember but you might need to restart auto and the app for it to show up.
> 
> Hope that helps :)
> 
> This how to enable devmode from the documentation at https://developer.android.com/training/cars/testing#test-auto
> 
> > Do one of the following to open the Android Auto settings, depending on the version of Android running on the device:
> > Android 10 or higher: On the device tap Settings > Apps & notifications > See all apps > Android Auto > Advanced > Additional settings in the app.
> > Android 9 or lower: In the Android Auto app, tap the Menu, then tap Settings.
> > Scroll to the About section near the bottom and tap Version to display all of the version and permission information.
> > Tap the Version and permission info section 10 times.
> > The Allow development settings dialog appears.
> > Tap OK.
> > Developer mode is now enabled and you can access developer options in the overflow menu.

Worked perfectly!!
