### ISSUE TITLE
FR: Scan catalog

### ISSUE THREAD

**Issue by gerroon** [daneren2005/Subsonic#808]
Hi

It would be nice if we have catalog scanning update under admin tools to force a catalog scan on the server.

thanks

**Comment by daneren2005** [comment]
If you are running the latest version of Subsonic server there already is a Scan Server option.

**Comment by retro-78** [comment]
Hi

Is it only supported by the subsonic API ? I am using a libresonic server instance and I cannot find this functionnality within Dsub.

Thanks

**Comment by daneren2005** [comment]
Libresonic uses the Subsonic API and needs to be updated to the latest version to support it.

**Comment by retro-78** [comment]
OK thanks @daneren2005
