### ISSUE TITLE
Cache size exceeds limit with long play queue

### ISSUE THREAD

**Issue by bazsy01** [daneren2005/Subsonic#814]
After debugging the app I found the cause:
All items on the current play queue are treated as undeletable by the cache cleaner and as a result the cache size can exceed the set size limit or ignore the min free space limit.

Reproduce: 
1. set a low cache limit
2. add many songs with play next or play last
3. cache the songs by playing or preloading songs
4. about dialog shows the higher than allowed cache size

Possible fix:
Treat only the currently playing and the previous/next 10 or so songs as undeletable.

If you like this solution I can create a pull request.

**Comment by daneren2005** [comment]
I would be fine with not marking already played songs as undeletable, but I think we should keep everything we are going to play in the future as undeletable.  We wouldn't want to delete them just to re-download them in 10 minutes...

**Comment by bazsy01** [comment]
I also want to avoid unnecessary downloads so I ended up using a change that keeps the 20 upcoming song undeletable. With an average of 3 minutes per song that would keep the next ~60 minutes of songs undeletable.
I think it would be fair to require the user to increase the cache size if he wants to avoid more bandwidth usage.

This is the new method in DownloadService.java that's called from CacheCleaner.java:
```
public synchronized List<DownloadFile> getRecentDownloads() {
	int from = Math.max(currentPlayingIndex - 10, 0);
	int to = Math.min(currentPlayingIndex + 20, downloadList.size() - 1);
	List<DownloadFile> temp = downloadList.subList(from, to);
	temp.addAll(backgroundDownloadList);
	return temp;
}
```

**Comment by daneren2005** [comment]
I ended up tweaking your solution in https://github.com/daneren2005/Subsonic/commit/c04999f5859fe9d0569e77bcfaacc13af8439c42 to make sure if users have more then 20 songs preloading it won't just download/delete them repeatedly.  Thank you for the patch that made it much easier to implement on my end.
