### ISSUE TITLE
Cant't use chrome cast

### ISSUE THREAD

**Issue by pfrpfr** [daneren2005/Subsonic#821]
Hi,

I just bought sub for android and tried to cast music on my Chromecast devices.
The application mentions a load error at the player view and no music is played (forwarded) or casted.

I'm disappointed with buying such an app. I chose this one because of its said casting capabilities.

Please help !

**Comment by daneren2005** [comment]
Are you using an address with https?

**Comment by sfunk1x** [comment]
I'm encountering this also. Unfortunately, dsub fails to gather logs so I'm at a loss as to what is failing.
