### ISSUE TITLE
Unable to connect to host using self signed cert and SSL verification

### ISSUE THREAD

**Issue by marcopaganini** [daneren2005/Subsonic#827]
I host my subsonic server at home, and connect to it using NGINX configured as a reverse SSL->subsonic proxy. In this scenario, NGINX is configured using a letsencrypt cert and things work really well. The downside is that anyone who finds out about my "secret" URL gets access to my subsonic server (well, a username/password prompt of subsonic anyways).

I've decided to increase the security of this setup by configuring NGINX to listen on a separate port and use a self-signed (private CA, created using easyRSA) cert to do the forwarding. NGINX is configured to reject all connections on this port where the incoming cert's signature does not match my private CA signature. The android device has all the required certs installed (cert+key, CA cert), and the CA cert is marked as "trusted". I can open connections to Subsonic this way using the browser in the phone without any problems, but the app fails.

Upon closer inspection and a few tests, it appears that the app is unable to send the correct cert for the domain in question, and NGINX rejects the request as expected.

Is there a way to select the correct cert? Maybe even some basic matching using the cert's CN vs the domain would suffice.

I found #60 that seems similar to this, but it's not exactly the same problem. Feel free to merge this issue into that one, if appropriate.

**Comment by gerroon** [comment]
I use custom certs with apache reverse without any issue. Did you import the cert to android system?

**Comment by marcopaganini** [comment]
Yes, they seem to be properly imported and are offered when I access via
browser.

**Comment by daneren2005** [comment]
I have no intention of spending time on this

**Comment by marcopaganini** [comment]
Hmmm, but closing a report which is actually a bug may not be the best way
to deal with it either. Maybe you should have a low-priority, or "blue sky"
fixes? Otherwise, there's always the risk of other people reporting the
same bug.
