### ISSUE TITLE
Radio player does not go through the subsonic server

### ISSUE THREAD

**Issue by elafargue** [daneren2005/Subsonic#833]
Subsonic lets you stream Internet radio through the server, but it looks like in DSub, the app tries to contact the internet radio directly.

This means that if you are in a location where you cannot access that URL (IP restrictions for instance), Internet radio play will fail. Using the Subsonic web interface will work though.

**Comment by daneren2005** [comment]
There is no API to go through the Subsonic server.  There is only one to return the address to load radio stations from.

**Comment by elafargue** [comment]
Interesting. If you look at the Subsonic web interface, there is definitely an API to do this. On my home server, for instance: http://192.168.1.2:4040/internetRadioStream.view?id=2 . . This returns an audio stream that is served by the Subsonic server.

My use-case is for a local device that streams FM/HD radio stations throught Subsonic and is only available on the "localhost" loopback interface on the subsonic server.

**Comment by daneren2005** [comment]
That is not a public API.  That is an internal method which requires an active web session and I can't use it in a client.

**Comment by elafargue** [comment]
Cool. I'll speak to Sindre about this and see if there's something that
can be done! Thanks
