### ISSUE TITLE
Android TV

### ISSUE THREAD

**Issue by modestos** [daneren2005/Subsonic#837]
Hi all!
You are doing a great job on this app. I must admit it is the most featured and stable for subsonic/madsonic.

Althought it is not on the actual AndroidTV market, I installed it on a Sony x93.

The app loads up normally and playbacks as usual. The only problem is the navigation with a TV remote (tabbed mode) on the main View/Viewgroup where the content is presented (Home content, Library etc). It is imposible to go there by using the aforemention interaction method.

All best,
mod

**Comment by mlg9000** [comment]
I'll second a desire for and Android TV remote friendly UI option.  Between my phone, tablet, and Android Auto, that's all that's left.

**Comment by daneren2005** [comment]
I have had an open issue for this for quite a while: https://github.com/daneren2005/Subsonic/issues/336
