### ISSUE TITLE
Permanently cached songs unable to play through offline library

### ISSUE THREAD

**Issue by flvinny521** [daneren2005/Subsonic#838]
I have permanently cached a large playlist. I can verify that all the files (.opus) are present in the cache directory. Switching DSub into offline mode and browsing the library displays all of the artists, as expected. However, clicking any of the album names results in an error that there are no tracks available.

However, if I navigate to playlists instead of library (still offline), I can play the same tracks in a playlist that are unavailable through the library.

I assume this is because .opus support for Android is lacking, but DSub obviously can handle the files if they work in a playlist.

**Comment by twangboy** [comment]
It looks like they don't play in online mode either... if that's what songs highlighted in red means (we really need some docs).

**Comment by daneren2005** [comment]
@flvinny521 I don't have my server setup with any opus files and looking at the code it *should* be fine.  Would you mind emailing me a temp username/password to look at the problem more directly?  My email is dsub.android@gmail.com.

**Comment by daneren2005** [comment]
Nevermind, it looks it is already fixed with https://github.com/daneren2005/Subsonic/commit/ea42d3c01caa05b3ff155d2e12e6f0fb35f2ed22 and I just haven't done a release with that fix.  Here is a release I just created for someone else that should include the fix in it if you want to verify: https://www.dropbox.com/s/j0mvh73c3sgbahb/DSub%205.3.5-fix-url.apk?dl=0

**Comment by flvinny521** [comment]
@daneren2005 Thank you for weighing in. I actually was able to solve the problem earlier by simply using the opus encoder and specifying an extension of .ogg (`ffmpeg -i %s -map 0:0 -codec:a libopus -b:a 128000 -vbr on -f ogg -`) , so I don't have any files I can use to test this at the moment.

**Comment by daneren2005** [comment]
Alright I am decently sure that it will be fixed in the next release so closing
