### ISSUE TITLE
Pull off ampache now connection errors

### ISSUE THREAD

**Issue by Mycah** [daneren2005/Subsonic#839]
Just did a pull off ampache develop and dsub can't sync.  Worked fine, and will revert but just putting this in for a heads up in case of a change.

From Apache log:
[05/Dec/2017:15:56:04 -0800] "GET /rest/getAlbumList2.view?u=mmattox&p=enc:<<number>>&v=1.2.0&c=DSub&type=newest&size=20&offset=0 HTTP/1.1" 200 724 "-" "DSub"

Hit that url with Firefox and got:
```
<subsonic-response type="ampache" version="1.11.0" status="failed">
<error code="70" message="The requested data was not found."/>
</subsonic-response>
```

A little more info.  If I revert to: https://github.com/ampache/ampache/commit/6e65a7f41053bb43076d7ae7c64280751f201727

It works again, and I think https://github.com/ampache/ampache/commit/a4061483d8615ddd0713be37c6013ca2a48b661a specifically broke it.

Not sure if this is an issue with dsub or with ampache.

**Comment by specialtimes** [comment]
They reverted this change: https://github.com/ampache/ampache/commit/a0d4eb178ebe83b92a429711456818fdfecc71e0

Closing the issue.

**Comment by Mycah** [comment]
ampache project reverted the change: https://github.com/ampache/ampache/commit/a0d4eb178ebe83b92a429711456818fdfecc71e0

Please close this issue.

**Comment by daneren2005** [comment]
Alright thank you for the update
