### ISSUE TITLE
Feature Request: Support for mka (matroska) audio

### ISSUE THREAD

**Issue by jeffgt14** [daneren2005/Subsonic#847]
There are a lot of concert DVD's out there with audio only in ac3 format. Matroska has an audio only container (mka), that can contain the ac3 audio. It would be great to be able to rip the audio streams from these DVD's and play them back with DSub but it doesn't seem to be supported.

**Comment by daneren2005** [comment]
DSub will never support anything beyond the file formats your device already supports.  It is not a generic music player, but is for Subsonic servers.  A huge point of Subsonic is to transcode everything to the file format your devices can support and not vice versa.
