### ISSUE TITLE
How does sync playlist work?

### ISSUE THREAD

**Issue by Offerel** [daneren2005/Subsonic#851]
I must admit, I'm new to Ampache/Subsonic and D-Sub. My goal is it to create a Smart Playlist on the Ampache server and synchronize this Smart Playlist automatically to Android. Creating the Smart Playlist in Ampache was no problem. Included are all tracks that have not been played for more than 365 days or that have never been played before. The list is currently limited to 25 entries. This works quite well on Ampache so far.

Now I want all tracks in this list to be automatically synchronized with Android. All tracks of the list should be downloaded to Android for offline use, so that they can be played without an internet connection. This sync should only run if there is a connection via Wifi. The sync should start automatically as soon as there is a connection via Wifi. If all tracks are available offline, the sync should be terminated. The time stamp, when a song was last played in offline mode, should be transferred to Ampache during sync.

Would I be able to do that with D-Sub? If so, what do I have to setup and where do I have to do this? Can someone please help me to get this to work?

**Comment by nx6** [comment]
@Offerel 

This is done on the app on the Playlists screen. Hit the menu (three dots) for the specific playlist and choose "Keep Synched". The playlist will get the green push-pin icon and start downloading the tracks on the playlist at that time.

I don't think it updates immediately on changes to the playlist. I think DSub only polls the server occasionally (like once an hour) asking if there are any changes, but the developer would be able to answer that better. Once it sees new tracks it will download them following the normal rules for streaming. So if you have the "only stream over wi-fi" setting on it will download them if you are.

Kinda off-topic: can I ask how you create these Smart Playlists? I'd like to replicate one of my favorite features from iTunes in Subsonic, and would need the ability to make a live-updating Smart Playlist to do so. If this is a feature specific to Ampache please let me know.

**Comment by Offerel** [comment]
Hi there. Sorry i have missed the alert mail about this answer, so i found it today after logging in :-) 

I don't know, if Subsonic has such a feature, but Ampache has it. You can create in the WebGUI a Smart Playlist with parameters like "not played for x days" or "play count less 5". In pure theories, such a playlist should maintain itself. For example if you set it to "not played for 365 days", the list contains only songs you have not played the last year, from today on. As i have must learn, this did only work in the WebGUI correctly. The problem seems to be the API. If you use it just like me, to "sync" such a playlist to your smartphone, the API for a song is triggered, when you download the song. It is also triggered, if you haven't played the song as of yet. Every trigger, sets the play count of a song +1 and the last played timestamp to the trigger time. With this, the songs falls out of the playlist (since timestamp is less than 365 days) and the song isn't played...

With this behavior, the smart playlist feature is useless, at least for me. So will stick with MediaMonkey on the desktop, MediaMonkey Pro on the Android phone and sync such smart playlists without any issue. Since the database and the music files are saved on a SMB share on my Rasperry Pi, i can access them also with any other client. Its not a perfect solution and at least you must buy MediaMonkey Pro for wireless syncing (USB sync is for free), its the better solution for me currently.
