### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by gerroon** [daneren2005/Subsonic#854]
Hi

Can you make a new release please? The latest release was almost a year ago.

thanks

**Comment by ftoledo** [comment]
Abandoned project?

**Comment by gerroon** [comment]
There are still recent commits

**Comment by craftyguy** [comment]
I think it's effectively abandoned, or at least the developer is too busy (or doesn't care) to make new releases for others who have purchased the app.

**Comment by craftyguy** [comment]
For what it's worth, there are FLOSS alternatives to this app that are still maintained, like [Ultrasonic](https://github.com/ultrasonic/ultrasonic) and [Audinaut](https://github.com/nvllsvm/Audinaut), just to name a couple I have found.

**Comment by gerroon** [comment]
@craftyguy the only issue with those is that none of them offer casting :(

**Comment by craftyguy** [comment]
@trwnh 

2 things:

1) https://github.com/daneren2005/Subsonic/compare/5.3.5...master

2) If this project is no longer being maintained, then it's likely folks will experience issues at some point in the future since the subsonic API is still a moving target. Security issues with the app would go unaddressed too.

**Comment by trwnh** [comment]
@craftyguy so why not request those specific changes, then? DSub still works fine. If there's a bug or security issue, report that.

**Comment by craftyguy** [comment]
@trwnh 
You asked why people might want a new release, I provided a couple of reasons (are you familiar with the phrase "playing devil's advocate"?) There are a number of open issues in the ticket tracker here too.

**Comment by craftyguy** [comment]
@richy58729 
this is dsub, a subsonic client, not subsonic itself.

**Comment by richy58729** [comment]
@craftyguy Sorry, you're totally right, didn't notice that earlier!

**Comment by thrdroom** [comment]
@daneren2005 Please let us know if you have intentions to continue to support and update the app? I really really need this app so bad (for airsonic and subsonic) and i am willing to pay for major updates if it would be needed to keep the development going. Will there be updates for Android 8.0 and 9.0? Can and should we support the development via donations like patreon or something else? An answer would be really appreciated. TIA

**Comment by gerroon** [comment]
@thrdroom 

It is a bit sad tht the dev never bothers to at least answers our questions like this, not that we expect him to work on it indefinetelly.

**Comment by daneren2005** [comment]
Doing a new release, but doubt the bugs people are looking for are in it.  Will see if I have motivation to spend dozens of hours tracking down more undocumented changes between Android versions.

**Comment by daneren2005** [comment]
Guess nevermind.  Looks like I can't without doing a target version update which I need to do a ton of testing for first.

**Comment by daneren2005** [comment]
Looks like I am still within the time limit (by a few days) so I did the release after all.  The next release will need to update the version though which will involve a bunch of required changes.

**Comment by ftoledo** [comment]
I can help with testing maybe codign but i dont android skillss.. =(

**Comment by Adi3000** [comment]
This is clearly an EMUI incompatibility. I have two phone, same version and the rotate portrait - > landscape > portrait bugs every time.

I' think about posting information, screen shot and others whenever I'll be in a better place. 

I too have coding skill but not android...
