### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by ice954pw** [daneren2005/Subsonic#856]
Waiting on a new release? Quite a few bugs, misc crashes on oreo. Also, it would be nice if the listing would shot up in a seperate search, versus in the drop down menu, it's difficult when you have multiple versions of albums, songs etc. My library if around 10TB, catalogued perfectly, but it's irritating to have to scroll as some times I have lots of results, and the font to be a bit smaller as well.

**Comment by daneren2005** [comment]
Doing a release now, but doubt it has the changes you are looking for

**Comment by ftoledo** [comment]
good to know that are new commits =) thanks!
