### ISSUE TITLE
Recently Added / Most Played shows different entries than madsonic's web client

### ISSUE THREAD

**Issue by fr500** [daneren2005/Subsonic#859]
For some reason this has always happened to me:

Recently Added:

Web client:
![image](https://user-images.githubusercontent.com/1721040/38687210-bb62bdf2-3e3b-11e8-8966-464aa0f89859.png)

Android:
![image](https://user-images.githubusercontent.com/1721040/38687155-9a281614-3e3b-11e8-9b99-ad7c6bd24cd5.png)

Most Played:

Web client:
![image](https://user-images.githubusercontent.com/1721040/38687228-c6dc8712-3e3b-11e8-9344-07776f99a7ad.png)

Android:
![image](https://user-images.githubusercontent.com/1721040/38687764-06fa957c-3e3d-11e8-926f-b62485d3636f.png)

Actually about most played, I have the feeling that those come from last.fm... because I certainly don't listen to those as much nowadays...

**Comment by daneren2005** [comment]
Sounds like an API issue.  Not going to touch
