### ISSUE TITLE
Android Auto Library search ignores folder

### ISSUE THREAD

**Issue by acroyear** [daneren2005/Subsonic#869]
When in Android Auto browsing Library (musicDirectory version, not artist/album ID3 mode - I wrote/maintain SubFire, so I understand the API), select a music folder.  Then see the music directories:

Expected: the music directories for that folder.
Actual: the music directories for the last folder you looked at in normal Application mode (outside of Auto).

Was able replicate regularly - switched to a different folder in the main app, then back to auto, and Library -> some other folder -> directories still showed the directories of the last one I saw in the main app.

**Comment by otisbartleh** [comment]
I'm also having Library issues, will open a new "Issue", and details here as well:

http://forum.subsonic.org/forum/viewtopic.php?f=16&t=18051

**Comment by daneren2005** [comment]
Can someone try installing https://www.dropbox.com/s/i60geoapxaa9adb/DSub%205.4.1-auto-fix.apk?dl=0 and double checking that this fixes this issue for them?
