### ISSUE TITLE
DSub Library No Longer Working with Android Auto

### ISSUE THREAD

**Issue by otisbartleh** [daneren2005/Subsonic#872]
Using DSub on Android Auto, I am now, since the last update, unable to access my DSub library from within Android Auto. It used to work (although I often had to refresh my Library from within regular DSub to get all the Artists to show up in Android Auto DSub), but now, in Android Auto DSub, when I go into my Library, I can get to the Artist list, but when I select an artist, it flashes back to the Now Playing Screen if plugged in to my car, or just immediately closes down Android Auto if I am not plugged in to my car. 

So the only way I am able to select an artist is to open my phone, go into Dsub (outside of Android Auto), and queue up the artist, album, or song, and THEN DSub within Android Auto will play what I selected.

I have Subsonic Server version 6.1.3 installed.

**Comment by daneren2005** [comment]
I'm looking into it

**Comment by abegosum** [comment]
To add to this, I pulled this logcat when recreating the issue on my phone.  Looks like it's having trouble finding the `github.daneren2005.dsub.domain.MusicDirectory.Entry` class.

    08-10 10:34:45.266  3924  1969 E AsyncOperation: serviceID=65, operation=GetPlaceById
    08-10 10:34:45.266  3924  1969 E AsyncOperation: OperationException[Status{statusCode=ERROR, resolution=null}]
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at azok.b(:com.google.android.gms@12874032@12.8.74 (090400-204998136):1)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at azod.a(:com.google.android.gms@12874032@12.8.74 (090400-204998136):27)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at wcp.run(:com.google.android.gms@12874032@12.8.74 (090400-204998136):33)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at bcbi.run(:com.google.android.gms@12874032@12.8.74 (090400-204998136):2)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at pnd.run(:com.google.android.gms@12874032@12.8.74 (090400-204998136):28)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at psy.run(Unknown Source:7)
    08-10 10:34:45.266  3924  1969 E AsyncOperation:        at java.lang.Thread.run(Thread.java:764)
    08-10 10:34:46.491  3020  3020 E QtiImsExtUtils: getConfigForPhoneId phoneId is invalid
    08-10 10:34:46.491  3020  3020 E QtiImsExtUtils: isCarrierConfigEnabled bundle is null
    08-10 10:34:47.878  1907  1907 E AndroidRuntime: FATAL EXCEPTION: main
    08-10 10:34:47.878  1907  1907 E AndroidRuntime: Process: com.google.android.projection.gearhead:vanagon, PID: 1907
    08-10 10:34:47.878  1907  1907 E AndroidRuntime: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = github.daneren2005.dsub.domain.MusicDirectory$Entry)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Parcel.readSerializable(Parcel.java:2925)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Parcel.readValue(Parcel.java:2711)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Parcel.readArrayMapInternal(Parcel.java:3029)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.BaseBundle.unparcel(BaseBundle.java:232)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Bundle.getParcelable(Bundle.java:940)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.support.v4.media.MediaDescriptionCompat.s(SourceFile:67)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.support.v4.media.MediaBrowserCompat$MediaItem.d(SourceFile:11)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at oa.onChildrenLoaded(SourceFile:6)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at of.onChildrenLoaded(SourceFile:4)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.media.browse.MediaBrowser$8.run(MediaBrowser.java:682)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:873)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: github.daneren2005.dsub.domain.MusicDirectory$Entry
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.lang.Class.classForName(Native Method)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.lang.Class.forName(Class.java:453)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Parcel$2.resolveClass(Parcel.java:2916)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1615)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at android.os.Parcel.readSerializable(Parcel.java:2919)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        ... 17 more
    08-10 10:34:47.878  1907  1907 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "github.daneren2005.dsub.domain.MusicDirectory$Entry" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/lib/arm64, /data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    08-10 10:34:47.878  1907  1907 E AndroidRuntime:        ... 27 more
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: FATAL EXCEPTION: main
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: Process: com.google.android.projection.gearhead:vanagon
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: PID: 1907
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = github.daneren2005.dsub.domain.MusicDirectory$Entry)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Parcel.readSerializable(Parcel.java:2925)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Parcel.readValue(Parcel.java:2711)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Parcel.readArrayMapInternal(Parcel.java:3029)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.BaseBundle.initializeFromParcelLocked(BaseBundle.java:288)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.BaseBundle.unparcel(BaseBundle.java:232)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Bundle.getParcelable(Bundle.java:940)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.support.v4.media.MediaDescriptionCompat.s(SourceFile:67)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.support.v4.media.MediaBrowserCompat$MediaItem.d(SourceFile:11)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at oa.onChildrenLoaded(SourceFile:6)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at of.onChildrenLoaded(SourceFile:4)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.media.browse.MediaBrowser$8.run(MediaBrowser.java:682)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Handler.handleCallback(Handler.java:873)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Handler.dispatchMessage(Handler.java:99)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: Caused by: java.lang.ClassNotFoundException: github.daneren2005.dsub.domain.MusicDirectory$Entry
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.lang.Class.classForName(Native Method)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.lang.Class.forName(Class.java:453)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.resolveClass(ObjectInputStream.java:628)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Parcel$2.resolveClass(Parcel.java:2916)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.readNonProxyDesc(ObjectInputStream.java:1615)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.readClassDesc(ObjectInputStream.java:1520)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1776)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1353)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.io.ObjectInputStream.readObject(ObjectInputStream.java:373)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at android.os.Parcel.readSerializable(Parcel.java:2919)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       ... 17 more
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler: Caused by: java.lang.ClassNotFoundException: Didn't find class "github.daneren2005.dsub.domain.MusicDirectory$Entry" on path: DexPathList[[zip file "/system/framework/org.apache.http.legacy.boot.jar", zip file "/data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/base.apk"],nativeLibraryDirectories=[/data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/lib/arm64, /data/app/com.google.android.projection.gearhead-_4xYNTrRq8xzio2FHwYGfQ==/base.apk!/lib/arm64-v8a, /system/lib64]]
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    08-10 10:34:47.878  1907  1907 E GH.CrashHandler:       ... 27 more
    08-10 10:34:44.905   911   911 E wificond: NL80211_CMD_TRIGGER_SCAN failed: Device or resource busy
    08-10 10:34:47.935  1907  1907 E GH.CrashHandler: Car mode disabled
    08-10 10:34:47.951  1907  1907 E GH.CarModeSettings: Restore settings in crash
    08-10 10:34:47.967  1907  1907 E GH.CarModeSettings: Restore bluetooth not modified, no permissions or record failed.
    08-10 10:34:47.975  1907  1907 E GH.CrashHandler: Restored settings
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient: Error dispatching onNotificationPosted
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient: android.os.DeadObjectException
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transactNative(Native Method)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transact(Binder.java:1127)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at awj.transactOneway(SourceFile:27)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at bhc.onNotificationPosted(SourceFile:13)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at bhg.a(SourceFile:224)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at ckr.onNotificationPosted(SourceFile:28)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1985)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.os.Handler.dispatchMessage(Handler.java:106)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:48.026  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient: Error dispatching onNotificationPosted
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient: android.os.DeadObjectException
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transactNative(Native Method)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transact(Binder.java:1127)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at awj.transactOneway(SourceFile:27)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at bhc.onNotificationPosted(SourceFile:13)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at bhg.a(SourceFile:224)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at ckr.onNotificationPosted(SourceFile:28)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:1985)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.os.Handler.dispatchMessage(Handler.java:106)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:48.030  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient: Error dispatching onInterruptionFilterChanged
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient: android.os.DeadObjectException
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transactNative(Native Method)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transact(Binder.java:1127)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at awj.transactOneway(SourceFile:27)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at bhc.onInterruptionFilterChanged(SourceFile:30)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at bhg.b(SourceFile:268)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at ckr.onInterruptionFilterChanged(SourceFile:56)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2014)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.Handler.dispatchMessage(Handler.java:106)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient: Error dispatching onNotificationRankingUpdate
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient: android.os.DeadObjectException
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transactNative(Native Method)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.BinderProxy.transact(Binder.java:1127)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at awj.transactOneway(SourceFile:27)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at bhc.onNotificationRankingUpdate(SourceFile:22)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at bhg.a(SourceFile:246)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at ckr.onNotificationRankingUpdate(SourceFile:42)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.service.notification.NotificationListenerService$MyHandler.handleMessage(NotificationListenerService.java:2004)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.Handler.dispatchMessage(Handler.java:106)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.os.Looper.loop(Looper.java:193)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at android.app.ActivityThread.main(ActivityThread.java:6669)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at java.lang.reflect.Method.invoke(Native Method)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
    08-10 10:34:48.041  4018  4018 E GH.SharedNotifClient:  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)

**Comment by glennguy** [comment]
@daneren2005 I have no Java experience or knowledge but have been trying to hunt this one down and thought I'd report my findings in case it saves you a bit of time.

The Android Auto crash is happening for me here: https://github.com/daneren2005/Subsonic/blob/edge/app/src/main/java/github/daneren2005/dsub/service/AutoMediaBrowserService.java#L370 . Tested on my own Airsonic server 10.1.2 and the demo server. Happens once I click on an album to see its tracks.

I've tried to step into it to see exactly where but haven't had any luck pinpointing exactly where it is happening.

With the exception `java.lang.RuntimeException: Parcelable encountered ClassNotFoundException reading a Serializable object (name = github.daneren2005.dsub.domain.MusicDirectory$Entry)` I found this SE page which might be helpful: https://stackoverflow.com/questions/45373374/sending-serializable-object-between-applications-with-broadcast-receiver  
To me at least this makes sense as the crash only happens when sending the track list between apps. If this is the case, would that mean rewriting the `MusicDirectory` and `Entry` classes to use `Parcelable` or a 3rd party option instead?

**Comment by daneren2005** [comment]
I'm having trouble tracking down what is going on here because those classes most definitely exist and it works in development.  I am still working on it though.

**Comment by jackmort37** [comment]
I've just tested it, and it seems to work for me.
Thanks for the fix.

**Comment by glennguy** [comment]
Thanks @daneren2005, working well here.

**Comment by otisbartleh** [comment]
Sorry for the late response, been out of town for family, but the fix appears to be working all good here too, thanks @daneren2005  !!!

**Comment by garyo** [comment]
I'm running 5.4.4, but still getting constant crashes in Android Auto. Is this fix already in 5.4.4?
