### ISSUE TITLE
Filenames in playlists sometimes are named with "complete"

### ISSUE THREAD

**Issue by topas-rec** [daneren2005/Subsonic#873]
Hello everyone,

After successful syncing music from airsonic to android using dsub some music-filenames in the playlists text files (m3u files - located in playlists folder of dsub) contain the text ".complete." in their filenames.

Example (replaced artist and album with ...)
/storage/85C8-1DEB/Android/media/github.daneren2005.dsub/music/.../.../11-title.mp3
/storage/85C8-1DEB/Android/media/github.daneren2005.dsub/music/.../..../01-title.complete.mp3

Why is this an issue?
In general everything works as long as one does NOT want to freely chose the android music player to use. As far as I know in android the folders are scanned for playlists and music somewhere central. Then other apps use the scanned data. The central scan fails (result is an empty playlist in stock music app) when the files mentioned in the playlist file do not exist. It also fails if the file exists, but the filename or path in the playlist is wrong. (Contains ".complete." for example while file name does not)

I would like to be able to use any android music player, not just dsub. For that android has to be able to recognise the files of playlists. Dsub is very close to this. It works for all playlists that do not contain the ".complete." part in filenames.

This does NOT happen in EVERY playlist.
Repeat: it's about file name or paths INSIDE playlists files.

**Comment by daneren2005** [comment]
Others have mentioned this in the past, but honestly it would require a major rewrite of the entire cache system for what is a niche use case. I don't intend on doing this due to how big a pain in the butt backwards compatibility would be and how few people this would benefit.

**Comment by topas-rec** [comment]
I see. Thanks for the explanation.

I think this is not a good way to do things but I see there are good reasons not to make a change here.

For the people who come here and have the same problem that I have:

I tried to let https://ultrasonic.github.io/ do the sync and see if their files show up in android music system and they do. (This app definitely has issues too at the moment but I'll give it a try - maybe others who would also like to use third party audio players also want to try it)

**Comment by topas-rec** [comment]
I recently discovered that ultrasonic also uses the text ".complete." in its playlist files, but it looks like only for songs that are NOT SYNCED to the device. That is not a problem for android discovery since the files marked with ".complete." aren't present on the file system anyway. All other files are present and don't have the text in the playlists. That is why it works in ultrasonic.

@daneren2005
How is the ".complete." text intended to work in dsub. Perhaps I understood it in wrong way.
