### ISSUE TITLE
DSub crashes when minimized

### ISSUE THREAD

**Issue by manny44** [daneren2005/Subsonic#880]
DSub version 5.4.2
Android version 9
Pixel XL

Have had this issue for some time now. When DSub is minimized while music is playing, DSub crashes after about 30 seconds. This issue doesn't occur when DSub is in focus. I've tried playing around with numerous settings to attempt to fix the issue and nothing solves it.

**Comment by daneren2005** [comment]
Do you have the playing notification blocked in System Settings?  The service relies on that so it isn't killed by the OS automatically.

**Comment by manny44** [comment]
Nope, it's allowed. I've also tried enabling/disabling persistent notifications. And that didn't make a difference.

**Comment by daneren2005** [comment]
I honestly don't know how to reproduce or even see what is going on to cause it to crash for you.

**Comment by manny44** [comment]
Would the trace.txt be of any use?

> Android API level: 28
> Subsonic version name: 5.4.2
> Subsonic version code: 199
> 
> java.lang.IllegalStateException: Not allowed to start service Intent { cmp=github.daneren2005.dsub/.service.DownloadService }: app is in background uid UidRecord{a350ac8 u0a154 TPSL bg:+3m36s859ms idle procs:1 seq(0,0,0)}
> 	at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
> 	at android.app.ContextImpl.startService(ContextImpl.java:1532)
> 	at android.content.ContextWrapper.startService(ContextWrapper.java:664)
> 	at github.daneren2005.dsub.activity.SubsonicActivity.getDownloadService(SubsonicActivity.java:1006)
> 	at github.daneren2005.dsub.fragments.SubsonicFragment.getDownloadService(SubsonicFragment.java:562)
> 	at github.daneren2005.dsub.fragments.NowPlayingFragment.setControlsVisible(NowPlayingFragment.java:849)
> 	at github.daneren2005.dsub.fragments.NowPlayingFragment.onResumeHandlers(NowPlayingFragment.java:747)
> 	at github.daneren2005.dsub.fragments.NowPlayingFragment.onStart(NowPlayingFragment.java:740)
> 	at android.support.v4.app.Fragment.performStart(Fragment.java:2372)
> 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1467)
> 	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1759)
> 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1827)
> 	at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3244)
> 	at android.support.v4.app.FragmentManagerImpl.dispatchStart(FragmentManager.java:3206)
> 	at android.support.v4.app.FragmentController.dispatchStart(FragmentController.java:206)
> 	at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:605)
> 	at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:177)
> 	at github.daneren2005.dsub.activity.SubsonicActivity.onStart(SubsonicActivity.java:241)
> 	at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1391)
> 	at android.app.Activity.performStart(Activity.java:7157)
> 	at android.app.Activity.performRestart(Activity.java:7268)
> 	at android.app.ActivityThread.handleWindowVisibility(ActivityThread.java:4256)
> 	at android.app.servertransaction.WindowVisibilityItem.execute(WindowVisibilityItem.java:38)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1808)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6669)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
>

**Comment by daneren2005** [comment]
Since I was not able to reproduce, I can't be 100% sure that this will fix it, but based on https://stackoverflow.com/questions/46445265/android-8-0-java-lang-illegalstateexception-not-allowed-to-start-service-inten I am pretty sure it will.  Here is a test apk if you want to test this out.

https://www.dropbox.com/s/muq1i2wwavkjnk3/DSub%205.4.2-service-crash-fix.apk?dl=0

**Comment by manny44** [comment]
Yes! It works now. Thank you
