### ISSUE TITLE
Server address selection based on Wifi SSID is not working on android P

### ISSUE THREAD

**Issue by dpedu** [daneren2005/Subsonic#884]
When I upgraded my phone to Android P, the feature where DSub picks the server address based on what wifi network the device is connected to no longer works. Instead of picking the appropriate server, it always connects to the "Server address" value, never the "Local network address".

Furthermore, on the server settings page, attempting to update the "Local network SSID" setting by tapping the "Current SSID" button, the text "<unkown ssid>" is entered instead of the actual SSID.

**Comment by glennguy** [comment]
Workaround is to manually enable location permission for dsub in your phone's settings, had the same issue here
