### ISSUE TITLE
Streaming FLAC content does not work

### ISSUE THREAD

**Issue by lones710** [daneren2005/Subsonic#886]
First of all, thanks for this AMAZING app daneren2005!
I have an issue with FLAC streaming. MP3 content works fine, but my Marantz NR1607 won't accept FLAC files from DSub (the Marantz just says "filetype error"). Using BubbleUPNP works fine, selecting the corresponding files directly on the Marantz, too. How can I help troubleshooting and fixing this issue?

**Comment by daneren2005** [comment]
BubbleUPNP probably is transcoding the files so that they work.  I don't intend on adding any support for anything like that since that is the entire point of Subsonic to transcode the files on the server so the client doesn't have to.
