### ISSUE TITLE
Android Auto:  Album Art only displays for first track played

### ISSUE THREAD

**Issue by MinimalPTH** [daneren2005/Subsonic#939]
Android Auto only shows the album art for the first track I play.  When subsequent tracks begin playing, the spot that should show the album art is empty/blank.  In contrast, every other music app I've tried using with Android Auto shows cover art for every track, including Spotify, Tidal, and Google Play music.

Is there some sort of method to explicitly transmit an album art image along with the track tags with each track's playback?  If so, could you please implement?

**Comment by KBerstene** [comment]
What version of Android are you running?  Is it on a car head unit or on the phone?  I cannot reproduce this on my 9.0 phone, the album art changes without a problem for me.

**Comment by MinimalPTH** [comment]
OnePlus 6 with OS 9.0.4, Android Auto 4.1.590944 (although it has done this for every version of Android Auto since I purchased the vehicle.)

This happens on the head-unit of my 2019 Honda Accord EX.  

Your post got me thinking along the lines of eliminating my handset, so I set up my old Nexus 6P with my car and the problem persisted.  So, no luck there.

To illustrate the issue I have recorded a short video:  https://youtu.be/PfORMsTxo_c

 The first new track that plays is a subsequent DSub track.  Notice how the pop-up notification for the new track does not show an album art thumbnail in the left side of the bar.  Undesired behavior; album art isn't visible on my on-dash display, either.

Then, switching to Tidal and skipping to a new track, you can see the album art thumbnail on the left side of the next track notification pop-up bar.  (Desired behavior).  Album art also shows up on my on-dash display.

**Comment by KBerstene** [comment]
Thanks for the video! That's super helpful information. No promises I can
fix it, but I'll take a look and see if I can figure it out.

**Comment by MinimalPTH** [comment]
Just want to say thanks for showing up out of the blue and taking a crack at this issue.  There hasn't been an actual release of this since September so I'm not sure what's up with the original developer.  I'm really grateful to know this will hopefully be addressed whenever the next release comes.

**Comment by KBerstene** [comment]
I have been working on some stuff for myself in the app lately and have been looking for more problems to solve, so I'm glad that I might have been able to help with this. I think the main dev comes back every six months or so and works on the app again. Hopefully that will be soon for you - I don't want this app to die.

**Comment by MinimalPTH** [comment]
Thank you so much!  All is well!

**Comment by MinimalPTH** [comment]
I spoke too soon; word of warning to anyone running this build:  Casting to chromecast devices is not possible using this build.

**Comment by KBerstene** [comment]
Oh yeah, sorry, I forgot about that.  I think that I have to register with Google as a Chromecast developer or something (I think it's 5 bucks) to get a valid authentication code for it.  I think daneren2005 keeps that code out of the github repository for security reasons and puts it in before he does his final build.  Either that or I'm somehow building wrong, but I've never been able to do Chromecast from my own builds.
