### ISSUE TITLE
Suggestion: More modern look?

### ISSUE THREAD

**Issue by DOFfactory** [daneren2005/Subsonic#943]
I was windering whether for mobile users a more modern UI would be feasible. A good UI example is that of Soundcloud which we can take inspiration. Since we download files, it would be completely feasible to get a spectrum meter and fast-forward in it, sliding for changing the track, etc. See attached screenshots.

![Screenshot_20190331-131637](https://user-images.githubusercontent.com/10846169/55288446-40eef200-53b8-11e9-9363-eabed3c0df59.jpg)
![Screenshot_20190331-131719](https://user-images.githubusercontent.com/10846169/55288448-40eef200-53b8-11e9-885a-51304b65b083.jpg)

**Comment by daneren2005** [comment]
I have no intention of rewriting DSub to modernize the UI
