### ISSUE TITLE
Playback stops after a couple minutes

### ISSUE THREAD

**Issue by abrenoch** [daneren2005/Subsonic#951]
I have been getting this error for quite some time now. Seems to have started when updating to android 8 (og pixel xl). 

```
04-17 15:49:30.065  2256  7164 W DownloadService: Crashed getting current position
04-17 15:49:30.065  2256  7164 W DownloadService: java.lang.IllegalStateException
04-17 15:49:30.065  2256  7164 W DownloadService:       at android.media.MediaPlayer.getCurrentPosition(Native Method)
04-17 15:49:30.065  2256  7164 W DownloadService:       at github.daneren2005.dsub.service.DownloadService$LocalPositionCache.run(DownloadService.java:1588)
04-17 15:49:30.065  2256  7164 W DownloadService:       at java.lang.Thread.run(Thread.java:764)
```

It has made dsub basically unusable for me :(

Please let me know if there is any more info I could provide!

**Comment by KBerstene** [comment]
Are you on the latest version? I know there have been some fixes in the last release or two due to Android 8.

**Comment by abrenoch** [comment]
I just ran it for a while on my pixel 3a XL running the latest android Q beta and it seemed to play alright.

My last device (pixel XL) started to have some **very** weird issues associated with the audio driver, so maybe that was playing into whatever was going on.

I'll close this for now!
