### ISSUE TITLE
Development 

### ISSUE THREAD

**Issue by screwfaze** [daneren2005/Subsonic#959]
First of all just want to say this is a very good app thanks for making it, Is anyone else going to take over development or is this the last version we will see of this app?

**Comment by thrdroom** [comment]
Good question, i was thinking about the same.
Would donations help to keep the development of this app going?

If so, where and how should we donate?

**Comment by Koenvh1** [comment]
Given the commits in the edge branch, I see no reason to assume that this would be the last version.

**Comment by antgel** [comment]
> Given the commits in the edge branch, I see no reason to assume that this would be the last version.

Well, it wouldn't hurt to respond to the issues either. There seem to be many people willing to help.

**Comment by undersound** [comment]
I am willing to donate / help. Love this app
