### ISSUE TITLE
5.4.4 byYear is backwards

### ISSUE THREAD

**Issue by lachlan-00** [daneren2005/Subsonic#967]
Dsub decades page From and toyear are backwards. Making it impossible to complete.
```
GET /rest/getAlbumList2.view?u=user&p
=enc:354764396f63784c52&v=1.2.0&c=DSub&size=20&offset=0&type=byYear&fromYear=2019&toYear=2010
```

**Comment by lachlan-00** [comment]
I've worked around this in ampache develop by comparing both inputs.

Does dsub also always sen 1.2.0 as the version? I'm going to overwrite it to 1.13.0 which is the current ampache version

**Comment by daneren2005** [comment]
IIRC it does this because that is the way the Subsonic API returns the data.  I believe that if you pass 2010 - 2019 to Subsonic, it returns the results as 2010, 2011, 2012, etc... If you pass 2019 - 2018, it goes 2019, 2018, 2017 which is what we want.

**Comment by daneren2005** [comment]
And yes it always sends the same version.  The version in the API I believe is the oldest version that the client is designed to support.  If we pass 1.14 to a server that is at version 1.13, it will return an error so the client knows it won't work correctly.

**Comment by lachlan-00** [comment]
thanks for the clarifications
