### ISSUE TITLE
DSub does not fill available vertical space

### ISSUE THREAD

**Issue by CampinCarl** [daneren2005/Subsonic#975]
DSub 5.4.4 does not fill available vertical space on a large phone—Pixel 4 XL in this example—resulting in a black bar at the bottom of the app.

<img src="https://user-images.githubusercontent.com/11837803/71119861-24deeb00-21a9-11ea-89c3-c37b84db1c37.png" alt="Example" width="300">

**Comment by pbanj** [comment]
Same on my 3a

**Comment by MessiahMozgus** [comment]
Same issue here, OnePlus 7 Pro on Havoc rom. Didn't have this issue on stock rom.

**Comment by jacroe** [comment]
The [latest release](https://github.com/daneren2005/Subsonic/releases/tag/5.5.1-beta) fixed this for me on my Pixel 4.

**Comment by daneren2005** [comment]
Sweet that is good to hear. Going to close then.

**Comment by jmgant** [comment]
I have the latest dsub yet I have the same issue with the app not filling the screen.

**Comment by pbanj** [comment]
What phone and version of Android?
