### ISSUE TITLE
Slow playback

### ISSUE THREAD

**Issue by khers** [daneren2005/Subsonic#988]
AFAIK There is no control for playback speed so I don't think I set it by accident.  But I am finding that all playback is about 10% slower than it should be.  This happens regardless of file format or source.  Music is slow but pitch does not seem to be affected.  Podcasts are also significantly slower than they should be.

**Comment by popeen** [comment]
Actually there is a control for playback speed if you are using android 6 or newer. The icon for it looks like a clock and can be found on the now playing view between the star and bookmark icons, hope that helps

**Comment by khers** [comment]
This was the problem, thank you so much for pointing it out!
