### ISSUE TITLE
Apk with the lastest changes.

### ISSUE THREAD

**Issue by nonylours** [daneren2005/Subsonic#991]
Hi
I would like to know if there was an apk available with the changes made since the last release.   Especially one with the 2020s decades menu fix.
Thanks.

**Comment by dreamwraith** [comment]
Curious if there is any reason why this is years old on android play market when its still being sold on the market?

**Comment by daneren2005** [comment]
Will be working on a release soon.  Will be a while before I can do a release on Play Store since I'm not allowed to release there without doing a ton of updates first.
