### ISSUE TITLE
Decade 2020 missing

### ISSUE THREAD

**Issue by AvdWerfhorst** [daneren2005/Subsonic#997]
When I switch to decade view, I have no 2020 as decade to select. While I already do have my first 2020 albums in the collection.

**Comment by popeen** [comment]
This has been fixed in the code here on GitHub but has not made it to a compiled release yet.

Speaking of, @daneren2005 , it might be time to compile the current code to a new release? There have been several pull requests merged since the last release.

**Comment by daneren2005** [comment]
I am working on a release soon.  Going to close this since it is fixed in code already.
