### ISSUE TITLE
Empty Similar Artist list

### ISSUE THREAD

**Issue by MuadDibIII** [daneren2005/Subsonic#998]
Hello,

First of all, thanks for the app, it's the best Subsonic app available.

I'm writing because I'm having a issue with the similar artist feature on the app. Some of my artists doesn't seems to have any related artists, even if that's not the case on the web interface of Subsonic.

For example, with the artist "Iron Maiden", I'm having an empty similar artist list (and also empty artist radio list), even if it's not the case with the Subsonic web interface.

Do you have any clue on what might be happening?

Thanks in advance for your help,

Best regards,
Marc

**Comment by daneren2005** [comment]
If the API is returning the wrong response nothing I can do about it

**Comment by MuadDibIII** [comment]
Just a little update,, I figured out that the issue only happens when in folder view. If I use id3 tags, the radio function works as expected. Thanks
